miso-web/src/main/webapp/pages/editSequencerPartitionContainer.jsp
When you save a partition container, it will duplicate the contents of certain fields due to duplicate entries in the form.
=> Fix duplication of fields in partition container editor

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/RunProcessingUtils.java, spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/PoolControllerHelperService.java
- Fix Illumina samplesheet demultiplexing so that Pools with a barcoded single element will export their barcode correctly.
- Show barcode index information if present for single element pools in Edit Pools page.
=> MISO-194: Fix Illumina samplesheet demultiplexing

miso-web/src/main/webapp/scripts/box_ajax.js, miso-web/src/main/webapp/scripts/library_ajax.js, miso-web/src/main/webapp/scripts/sample_ajax.js
DataTables with hidden columns were setting a static table width on page load. Got ugly when the window was resized
=> fixed table widths

miso-web/src/main/webapp/pages/instituteDefaults.jsp, miso-web/src/main/webapp/pages/myAccount.jsp, miso-web/src/main/webapp/scripts/instituteDefaults_ajax.js
We had briefly discussed renaming GSLE "Tissue Type" to "Tissue Condition" (experimental condition of Primary/Reference/Metastatic/Xenograft Tissue) for increased semantic clarity, but decided that would be more of an annoyance than a benefit to the lab.
=> Replace "Tissue Condition" with "Tissue Type" on front end

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SampleAdditionalInfo.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleAdditionalInfoImpl.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleAdditionalInfoDto.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleAdditionalInfoService.java, sqlstore/src/main/resources/db/migration/V0010__sample_hierarchy.sql
Volume got added to Sample directly because it interacts with Boxes. This commit removes it from SampleAdditionalInfo as well.
This commit changes V0010__sample_hierarchy.sql .
=> Remove Volume from SampleAdditionalInfo

miso-web/src/main/webapp/pages/editKitDescriptor.jsp
Platform type was sending Enum back to server, so it was breaking when the Stringified Enum (all uppercase) did not match the String Enum key (regular case).
=> MISO-201 fix Illumina KD NPE

miso-web/src/main/webapp/pages/editPlate.jsp
Text no longer refers to Options menu when Options menu is not displayed.
=> fix plate Options text

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateIdentityDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateInstituteDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLabDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleNumberPerProjectDao.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/AllTestsSuite.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateIdentityDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateInstituteDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLabDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleNumberPerProjectDaoTest.java, sqlstore/src/test/resources/db-test-context.xml
Avoid attempting to autowire all of the Hibernate objects when performing
tests. They usually aren't required and autowiring them can create problems.
=> Reduce autowiring in tests

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/PlatformStore.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLPlatformDAO.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/AllTestsSuite.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLPlatformDAOTest.java
Note: Since Platforms get added as part of the migration scripts (before the test data is migrated), nextAutoIncrementId needs to be the ID after the last of the added Platforms since neither MySQL nor H2 roll IDs back.
=> SQLPlatformDAO tests

miso-web/src/main/resources/sql/db-config.xml
(https://github.com/TGAC/miso-lims/pull/137) removed the need to wire
emPcrDAO in the sqlLibraryDilutionDAO.
=> Correct wiring after LibraryDilution DAO tests

miso-web/src/main/webapp/pages/editLibrary.jsp, miso-web/src/main/webapp/pages/editPool.jsp, miso-web/src/main/webapp/pages/editProject.jsp, miso-web/src/main/webapp/pages/editRun.jsp, miso-web/src/main/webapp/pages/editSample.jsp
Allows non-admin users to delete their own notes on Sample, Library, Pool, Run, and ProjectOverview. This seems to have been the original intended behaviour, but was thwarted by copy pasta.
=> allow users to delete their own notes

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractSample.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleImpl.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/event/manager/ProjectAlertManager.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/SampleDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleValidRelationshipDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLSecurityProfileDAO.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/AllTestsSuite.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDaoTest.java
GLT-519 Update to allow hiberate and JDBC to work together within a single transaction.
GLT-519 Cascade saving child sample information.
GLT-519 Set the securityProfileId explicitly based on the provided SecurityProfile.
GLT-519 Avoid cloning hibernate specific portion of persisted Project.
GLT-519 Use existing transaction if one exists when retrieving sample valid relationships.
GLT-519 Use existing transaction if when is present when saving SecurityProfile.
GLT-519 Move call to query.list early in the transaction to avoid unnecessary auto flush.
GLT-519 Execute JDBC statements in session.doWork calls to avoid flushing and ending transaction.
GLT-519 Catching GenericJDBCException thrown by session.doWork calls.
GLT-519 addSample can now throw SQLException.
GLT-519 Handle giving samples …
=> GLT-519 Sample hierarchy transactions working again. Sample alias and name saved correctly.

sqlstore/src/main/resources/db/migration/V0019__more_platforms.sql, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLPlatformDAOTest.java, sqlstore/src/test/resources/db/scripts/schema_translator.groovy, sqlstore/src/test/resources/db/test_migration/V9000__miso_test_data.test.sql
- adds additional Platforms and updates PlatformDAOTests
- minor syntax fixes in V9000 test data
- updates Groovy script to ignore site-specific V8000-series migrations
=> GLT-529 add Platforms and update Groovy script to ignore site-specific migrations

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractSample.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Sample.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SampleAdditionalInfo.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleAdditionalInfoImpl.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleImpl.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleTissueNode.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleAdditionalInfoDto.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleDto.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleAdditionalInfoController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleController.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDao.java, sqlstore/src/main/resources/db/migration/V0010__sample_hierarchy.sql, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDaoTest.java, sqlstore/src/test/resources/db/test_migration/V9000__miso_test_data.test.sql
Moved parentId field to SampleAdditionalInfo, as it only applies to detailed samples. This also enables creating a composite unique key that is required (or at least helpful) for sample alias generation.
Also removed unused lastUpdated field from Sample. This field did not exist in the database, and the data is available via SampleChangeLog already
=> Glt 545 relocate parent

miso-web/src/main/webapp/pages/editSequencerReference.jsp
The 'add service record' menu is only displayed for users who have permissions to create service records (ADMIN and TECH). This prevents 'permission denied' errors for regular users.
=> GLT-585 Add Service Record only available to Admin and Tech in web ui

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/LimsUtils.java, miso-web/src/main/webapp/scripts/lims.js, miso-web/src/main/webapp/scripts/sample_ajax.js, spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/ContainerControllerHelperService.java, spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/DashboardHelperService.java, spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/PoolControllerHelperService.java, spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/PoolSearchService.java, spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/RunControllerHelperService.java, spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/SampleControllerHelperService.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLPoolDAO.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLPoolDAOTest.java
Rather than trying to guess (usually wrongly), it searches for the string as
provided and, if that yeilds nothing, searches using a base64-decoded string.
This removes all attempts to do base64 decoding in JavaScript.
=> Fix problem with potential base64-encoded strings in searches

miso-web/src/main/webapp/pages/instituteDefaults.jsp, miso-web/src/main/webapp/styles/style.css
- keeps tables from shifting up on Institute Defaults page while success checkmark is displayed
- merge this after GLT-581 PR
=> GLT-580 unshift institute defaults

spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/LibraryControllerHelperService.java
Library insert size was mistakenly set to be rounded to 2 decimal places. This commit undoes that change.
=> GLT-596 un-round library insert size

miso-web/src/main/webapp/scripts/lims.js
In the original ticket, it was requested to do the encoding. Since we have so many encoding mechanism (JSON, JSON containing HTML, and HTML written by JSPs), getting encoding and decoding HTML special characters consistently right is going to be very difficult and error-prone. I've opted for the lazy approach of just banning them in Parsley.
=> Avoid all HTML special characters in field names

miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditRunController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSequencerPartitionContainerController.java, miso-web/src/main/webapp/pages/editSequencerPartitionContainer.jsp, notification-consumer-services/src/main/java/uk/ac/bbsrc/tgac/miso/notification/consumer/service/mechanism/IlluminaNotificationMessageConsumerMechanism.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLRunDAO.java
On the Partition Containers page: displays a table of the runs associated with the container
- adds sequencing parameters to the view/edit run page only if the run already has an associated sequencer reference (ie. not on create, as that was causing a NPE -- GLT-590)
- also adds a check for container form existence before attaching a Parsley validator to the form (the form is only available on the create page)
=> GLT-278 add runs to containers page & GLT-590 new run NPE

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractLibrary.java, miso-web/src/main/webapp/scripts/library_hot.js, miso-web/src/main/webapp/scripts/sample_hot.js
Follows up on work in PR #216 and expands the correct save method to all saves/propagates in samples & libraries.
=> Proper success/error message display in all saves

sqlstore/src/main/resources/db/migration/V0022__library_design.sql
V0022 failed because `text`-type columns cannot have defaults. Since this was a recent commit, we've agreed to update the migration itself, manually do the changes required to fix our db: 
- compile with the commit below
- `DROP TABLE LibraryDesign`
- re-run the `CREATE TABLE LibraryPropagationRule` from [V0010](https://github.com/oicr-gsi/miso-lims/commit/4bcfd21f3480f89e8470e691cac62b29f79b13ea#diff-eeebc84bf2b2309ec4e54271f1cd2b65R334)
- run `flyway:repair` on the database, which will roll it back to V0021
- run migrations as usual
This way, we fix our db once and nobody in the future will have to fix this failed migration.
=> GLT-704 Fix bad migration

miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditBoxController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditPlateController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditPoolController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditRunController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/ListSamplesController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/MenuController.java, miso-web/src/main/webapp/WEB-INF/miso-config.xml
MisoAppListener is sometimes too slow (ie. one naming scheme is autowired into the LibraryControllerHelperService, and another into the SQLLibraryDAO).
Also sets properties in the controllers in a far cleaner way.
=> GLT-690 interpolate properties instead of waiting for MisoAppListener to set them

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/LibraryAdditionalInfo.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SampleAnalyte.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/LibraryAdditionalInfoImpl.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleAnalyteImpl.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/LibraryAdditionalInfoDto.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleAnalyteDto.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryAdditionalInfoService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleAnalyteService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/LibraryAdditionalInfoController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleAnalyteController.java, miso-web/src/main/webapp/pages/editLibrary.jsp, miso-web/src/main/webapp/pages/editSample.jsp, miso-web/src/main/webapp/scripts/sample_ajax.js, miso-web/src/main/webapp/scripts/sample_hot.js, sqlstore/src/main/resources/db/migration/V0026__groupId_groupDescription.sql
The original thought had been to control the vocabulary of Group ID and Group Description. However, this implementation would prove challenging for migration, and we will have to study the lab further in order to determine whether controlling this vocabulary would be useful.
With that in mind, this commit implements Group ID and Group Description as text fields on Sample Analyte (LibraryAdditionalInfo inherits these fields from Sample). The controlled vocabulary SampleGroup code has been commented out but left in place in case we end up making use of it later. (Thoughts on whether it should be deleted outright?)
=> GLT-700 use Group ID and Group Description as text fields

miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
Makes the DefaultSampleService more flexible in how parent information is specified (may be in sample.sampleAddtionalInfo.parent or sample.identity). Also includes binding fix for sample.groupId
=> fix sample service create method for propagation

miso-web/src/main/webapp/pages/bulkEditLibraries.jsp, miso-web/src/main/webapp/pages/bulkEditSamples.jsp, miso-web/src/main/webapp/pages/editBox.jsp, miso-web/src/main/webapp/pages/editExperiment.jsp, miso-web/src/main/webapp/pages/editLibrary.jsp, miso-web/src/main/webapp/pages/editPlate.jsp, miso-web/src/main/webapp/pages/editSample.jsp, miso-web/src/main/webapp/pages/editStudy.jsp, miso-web/src/main/webapp/pages/experimentWizard.jsp, miso-web/src/main/webapp/pages/importPlate.jsp, miso-web/src/main/webapp/pages/instituteDefaults.jsp, miso-web/src/main/webapp/pages/poolWizard.jsp, miso-web/src/main/webapp/pages/sampleReceipt.jsp
- GLT-619: remove stray breadcrumb on bulk create samples page
- GLT-638: use aliases in breadcrumbs (with names for hover-over)
- bonus: remove some unneeded imports
=> GLT-638 & GLT-619

notification-server/pom.xml, notification-server/src/main/java/uk/ac/bbsrc/tgac/miso/notification/service/IlluminaTransformer.java
The fork uses log4j and removes a mysterious `sleep` causing performance issues
=> Switch to Metrix fork

spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/LibraryControllerHelperService.java
The list may contain null barcodes. Do not be alarmed.
=> Fix NPE in prettyBarcodes

miso-web/src/main/webapp/pages/bulkEditLibraries.jsp, miso-web/src/main/webapp/pages/bulkEditSamples.jsp, miso-web/src/main/webapp/pages/editSample.jsp, miso-web/src/main/webapp/scripts/library_hot.js, miso-web/src/main/webapp/scripts/sample_hot.js
- visibility of Matrix (Identification) Barcode column in Handontable (sample & library) is turned off if these barcodes are auto-generated (set in miso.properties)
=> GLT-661 hide HOT IDBC col if BCs are autogenerated

spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/ContainerControllerHelperService.java, spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/RunControllerHelperService.java
Fix for the NPE that's returned when looking up a pool by an invalid barcode.
=> GLT-611 return "Pool not found" instead of NPE

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/type/PlatformType.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryAdditionalInfoService.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java, miso-web/src/main/webapp/pages/editLibrary.jsp, miso-web/src/main/webapp/pages/editSample.jsp
- fixes the enum error found when adding an OxfordNanopore container
- also finishes the fix for GLT-729 (corrects the check for resource writability)
=> GLT-608 fix OxfordNanopore enum & LibAddInfo save

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/PoolOrderCompletion.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/PoolOrderCompletionGroup.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/StatusImpl.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/type/HealthType.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/LimsUtils.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/PoolOrderCompletionService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultPoolOrderCompletionService.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditPoolController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/ListOutstandingOrdersController.java, miso-web/src/main/webapp/pages/editPool.jsp, miso-web/src/main/webapp/pages/listPoolOrders.jsp, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/PoolOrderCompletionDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolOrderCompletionDao.java, sqlstore/src/main/resources/db/migration/afterMigrate.sql
Instead of having simply requested and completed, provide pool order completion
counts for all possible sequencing states.
=> Allow multiple status in pool order completions

notification-server/src/main/java/uk/ac/bbsrc/tgac/miso/notification/service/IlluminaTransformer.java, notification-server/src/main/java/uk/ac/bbsrc/tgac/miso/notification/service/LS454Transformer.java
If you wish to have the canonical path reported, you can still accomplish this by setting the canonical path instead of using symbolic links in notification.properties.
Also replaced some Strings with constants
=> report configured path instead of canonical from notification server

miso-web/src/main/webapp/WEB-INF/applicationContext.xml, miso-web/src/main/webapp/WEB-INF/miso-servlet.xml, miso-web/src/main/webapp/WEB-INF/web.xml
You can now provide an external miso.properties file by adding the following parameter to ROOT.xml:
`<Parameter name="miso.propertiesFile" value="file:${CATALINA_HOME}/conf/Catalina/localhost/miso.properties" override="false"/>`
value must begin with `file:` and you must include `override=false`; otherwise, the parameter will be overridden by the default in web.xml (`classpath:miso.properties`). If this parameter is absent in ROOT.xml, the default in web.xml will be used as well, so current deployments will not be affected and may continue to use the packaged miso.properties file
=> added config for miso.properties location

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/event/manager/PoolAlertManager.java
- pools in watcher list are only ever accessed as read-only objects
- pool cloning is failing in production db
=> Remove unnecessary cloning

spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ControllerHelperServiceUtils.java, spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/BoxControllerHelperService.java, spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/LibraryControllerHelperService.java, spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/PlateControllerHelperService.java, spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/PoolControllerHelperService.java, spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/SampleControllerHelperService.java
This will hopefully solve the issue where prod is creating a folder called `ROOTtemp` at the same level as `ROOT` and saving the barcodes there.
=> Refactor finding of temp folder for id barcodes

miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-dto/src/test/java/uk/ac/bbsrc/tgac/miso/dto/DtosTestSuite.java, miso-web/src/main/webapp/scripts/sample_hot.js
Creating stock analyte on the bulk create sample page works again, and causes a parent tissue to be created in addition to the identity. All create and propagate methods should function correctly again
=> update Edit Sample (bulk) for required tissue in hierarchy

miso-web/src/main/webapp/scripts/sample_ajax.js
Fixes for a few bugs:
- non-detailed sample options (propagate samples; empty; archive) are not shown if detailed sample is not enabled
- multiple samples can only be edited if they are all of the same sample category
- Tissue Processing samples can only be edited if their sample class-specific columns do not collide (ie. can't do (LCM Tubes || CV Slides) + anything else
- Propagating samles: checks that a sample class is selected before continuing.
=> GLT-556 update List Samples page

migration/src/main/java/uk/ac/bbsrc/tgac/miso/migration/destination/MisoServiceManager.java, migration/src/main/java/uk/ac/bbsrc/tgac/miso/migration/util/SimpleLibraryNameGenerator.java, migration/src/main/java/uk/ac/bbsrc/tgac/miso/migration/util/SimpleLibraryNamingScheme.java, migration/src/main/resources/load-generator.properties
During migration, library alias validation must be skipped, and names such 'LIB123' must be generated. It was not possible to configure the existing naming schemes to achieve this, so I created a very simple one to use for migration instead
=> skip library alias validation during migration

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/UserImpl.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/security/LDAPSecurityManager.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/security/MisoAuthority.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/security/ad/ActiveDirectoryAuthoritiesMapper.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/security/util/LimsSecurityUtils.java, docs/_posts/2016-01-11-admin-manual.md, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditUserController.java, miso-web/src/main/webapp/WEB-INF/ad-security-config.xml, spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/DashboardHelperService.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/manager/MisoJdbcUserDetailsManager.java
Active directory does not return a password. Provide a fake password in this case
it is a requirement of the User service.
Created a separate Active directory configuration file that overrode one bean from the
general ldap configuration file.
=> GLT-479 Added configuration for Active Directory authentication

miso-web/src/main/webapp/WEB-INF/log4j.miso.properties
While date-based searching is nice, there's not automatic way to expire old
logs and log files can grow to an unbounded size. In particular, production
`ehcache.log` files can be large (over 1G) and tend to consume more prod disk
than they are worth. This will limit each log to 500GB and automaticall remove
old logs.
=> Switch to RollingFileAppender and reduce ehcache log level

miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/context/PrometheusInterceptor.java
The JavaScript in Grafana can't handle having {{class}} in the label name
=> Rename the class label to Java class

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractLibrary.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractPool.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractSample.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleAdditionalInfoImpl.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleTissueImpl.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/LimsUtils.java, core/src/test/java/uk/ac/bbsrc/tgac/miso/core/util/LimsUtilsTest.java
When Samples and Libraries are created through the Edit Sample/Edit Library page, empty fields were saved to the database as empty strings. This fix checks if the value being set is a blank string and if it is, the value is set to null.
=> GLT-1038 set null if attribute string is blank

miso-web/src/main/webapp/pages/bulkEditDilutions.jsp, miso-web/src/main/webapp/pages/bulkEditLibraries.jsp, miso-web/src/main/webapp/pages/bulkEditSamples.jsp, miso-web/src/main/webapp/pages/editSample.jsp
Right-click to paste does not work, so make it very obvious to users what they need to do to paste data.
=> GLT-1042 add ctrl-v message to HOT pages

miso-web/src/main/webapp/pages/editLibrary.jsp
The method is on the LibraryAdditionalInfo object, not on the Library object.
=> GLT-1060 correct handling of nonstandardalias on editLibrary JSP

miso-web/src/main/webapp/pages/editSequencerPartitionContainer.jsp
Too many `partition` -> `lane` conversions in places they shouldn't be (ie. the Java)
=> GLT-1090 remove accidental overgeneralization of language in Java

miso-web/src/main/webapp/scripts/sample_ajax.js
fixes bug where users could select more samples after selecting the sample class for child samples, but those additional selections wouldn't be carried over to the propagate page.
=> GLT-1078 check for selected samples right before changing page

sqlstore/src/main/resources/db/migration/V8001__box_position_unique.sql
This is to reduce the presentation of a race condition where concurrent
sample/library creation leads to duplicate boxPositionIds. This neither fixes
the underlying race condition in `nextval` nor ensures that there isn't a race
between a sample and a library.
=> Add uniqueness contraints to boxPositionId columns (GLT-1121)

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractPool.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLPoolDAOTest.java
(note: this work is based off GLT-1127, and will be rebased when #442 is merged)
=> GLT-1130 don't obliterate poolables when saving pool

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/naming/NameGenerator.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/naming/OicrSampleAliasGenerator.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/naming/SiblingNumberGenerator.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/context/MisoAppListener.java, miso-web/src/main/resources/external/miso.properties, miso-web/src/main/resources/internal/miso.properties, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/SampleDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDao.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLSampleDAOTest.java, sqlstore/src/test/resources/db-test-context.xml
also removes the option `miso.db.caching.mappers.enabled` which was never actually used for anything, and will not be useful with the switch-over to Hibernate
=> GLT-1085: fix siblingNumber generation

migration/src/main/java/uk/ac/bbsrc/tgac/miso/migration/destination/DefaultMigrationTarget.java
In migration, Library SecurityProfile is set using its parent Sample's Project, not the Sample itself.
=> Fixed NPE with Library SecurityProfiles

migration/src/main/java/uk/ac/bbsrc/tgac/miso/migration/destination/DefaultMigrationTarget.java
There is a bug where libraries which should have ghost aliquots are saving without the sample linked. This PR causes the save to fail as it should
=> GLT-1317: added check for parent sample when migrating library

miso-web/src/main/webapp/scripts/editProject_sample.js, spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/ProjectControllerHelperService.java
This was removed with the removal of plates.
Our lab use this, it isn't tied to any plate functionality.
Selecting this option in the radio adds a 96 well plate index (A1, B1, C1) to the generated sample delivery form, presumably for ease of use on the other end.
=> Re-add plate option for sample delivery form

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDao.java
This small change to using criteria speeds up bulk sample save from 25~30 secs per sample to <1 sec per sample.
It also removes some white space.
=> Speed up bulk add samples

miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
Turns out the project was lazy loaded and so getSamples() just returned an empty collection.
This change checks to see if there are more samples in the project and, if not, tries to eagerly load the project to get the full object graph.
No adjacent samples means no navigation arrows.
=> Fix Sample Navigation Arrows

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/MisoRequestManager.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/RequestManager.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/UserAuthMisoRequestManager.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/LibraryStore.java, miso-web/src/main/resources/external/miso.properties, spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/FlexReportingControllerHelperService.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLLibraryDAO.java
So creating the library report never seemed to end as it was trying to list every single library in the database.  We have ~26,000, so along with the mapping that was taking a while.
I changed it so it queries based on the created date of the library.  It always did this anyway but the logic was in the controller to sift though all 26K libraries, now it is in the DAO.
=> Fix library report

.gitignore, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractProject.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Project.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/ReferenceGenomeImpl.java, migration/src/main/java/uk/ac/bbsrc/tgac/miso/migration/destination/DefaultMigrationTarget.java, migration/src/main/java/uk/ac/bbsrc/tgac/miso/migration/destination/MisoServiceManager.java, migration/src/main/java/uk/ac/bbsrc/tgac/miso/migration/destination/ValueTypeLookup.java, migration/src/main/java/uk/ac/bbsrc/tgac/miso/migration/source/LoadGeneratorSource.java, migration/src/test/java/uk/ac/bbsrc/tgac/miso/migration/destination/ValueTypeLookupTestSuite.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/ReferenceGenomeService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultReferenceGenomeService.java, miso-service/src/test/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleServiceTestSuite.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditProjectController.java, miso-web/src/main/webapp/pages/editProject.jsp, spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/LimsBindingInitializer.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/ReferenceGenomeDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateReferenceGenomeDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLProjectDAO.java, sqlstore/src/main/resources/db/migration/V8000__ReferenceGenome.sql, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/AllTestsSuite.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLProjectDAOTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLReferenceGenomeDAOTest.java, sqlstore/src/test/resources/db-test-context.xml
Allowed ReferenceGenome to be retrieved by id.
Converted ReferenceGenome to charset utf8.
Project now refers to ReferenceGenome as an object and not an id.
Added project resolver to migration allowing a ReferenceGenome to be specified by name during migration.
Updated edit project UI to work with ReferenceGenome changes. Added a binding to convert by id.
=> GLT-1250 Migrate ReferenceGenome by name

integration-tools/pom.xml, pom.xml, runstats-client/pom.xml
This solves the problem we've been having for the past few months with the expired certificate.
@frankie13 should probably review this one.
=> Switch tgac repos from https to http to fix security issue

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractPool.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractProject.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractRun.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/ProjectOverview.java
I had thought that the cascade was required to manage the bridge table, but it is not. The cascade affects the referenced object(s) only. In this case, changes to the watched entity should never affect the watching User
=> fixup Watcher cascades

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractBox.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Box.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/BoxImpl.java, miso-web/src/main/webapp/WEB-INF/db-config.xml, spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/BoxControllerHelperService.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/CollectionLoggingInterceptor.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateBoxDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolDao.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLBoxDAOTest.java, sqlstore/src/test/resources/db/test_migration/V9000__miso_test_data.test.sql
The original interceptor design to log changes to pools and boxes created
multiple Hibernate sessions. This attaches the interceptor to the Hibernate
session factory.
=> Change interceptor design to avoid multiple Hibernate sesions

miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/AdminRestController.java
Add an URL to evict the contents of the Hibernate cache (since the existing cache eviction logic was removed when EHCache died).
=> Add cache eviction URL

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Status.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/StatusImpl.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/illumina/IlluminaStatus.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/solid/SolidStatus.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/MisoRequestManager.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/integration/strategy/interrogator/IlluminaSequencerInterrogationStrategy.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/integration/strategy/interrogator/LS454SequencerInterrogationStrategy.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/StatusStore.java, demo-notification-client/src/main/java/uk/ac/bbsrc/tgac/miso/notification/demo/service/mechanism/DemoIlluminaConsumerMechanism.java, notification-consumer-services/src/main/java/uk/ac/bbsrc/tgac/miso/notification/consumer/service/mechanism/IlluminaNotificationMessageConsumerMechanism.java, notification-consumer-services/src/main/java/uk/ac/bbsrc/tgac/miso/notification/consumer/service/mechanism/LS454NotificationMessageConsumerMechanism.java, notification-consumer-services/src/main/java/uk/ac/bbsrc/tgac/miso/notification/consumer/service/mechanism/PacBioNotificationMessageConsumerMechanism.java, notification-consumer-services/src/main/java/uk/ac/bbsrc/tgac/miso/notification/consumer/service/mechanism/SolidNotificationMessageConsumerMechanism.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateStatusDao.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLRunDAOTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLStatusDAOTest.java
The notification server and Status use the term runName to refer to the thing MISO calls Run.alias . This updates the getters and setters on Status to use the term run.alias to avoid confusion. (Note that the notification server still uses the term runName, because this is the term that the sequencers and possibly the SRA use.)
=> Change Status to use runAlias consistently

miso-web/src/main/webapp/scripts/sample_hot.js
So users can bulk update if receiving non-tissue, or if they need to bulk update scientific name for detailed samples.
=> always show date of receipt and sci. name for bulk create/update

miso-web/src/main/webapp/pages/adminsub.jsp
I commented out the link to the experiments page in the left hand navigation menu until we solve the back end issues surrounding the listAll methods.
=> Remove experiments link

sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateAlertDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateBoxDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateChangeLogDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateExperimentDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateIndexDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateKitDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryDilutionDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryQcDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePlatformDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolQcDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePrintServiceDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateProjectDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateReferenceGenomeDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRunDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRunQcDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleQcDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSecurityDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSecurityProfileDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSequencerPartitionContainerDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSequencerReferenceDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSequencerServiceRecordDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateStatusDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateStudyDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateTargetedSequencingDaoTest.java
In particular, I'm tired of `HiberateIndexDaoTest`.
=> Rename all DAO tests consistently

miso-web/src/main/webapp/scripts/library_hot.js
When called in the other order, some columns can be marked as invalid even
though they are valid.
=> Fix race condition causing validation problems

miso-web/src/main/webapp/pages/editSample.jsp
So users don't have to tab past non-required fields.
=> Group the fields for detailedSample alias together for easier entry

miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/LibraryDto.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/LibraryRestController.java, miso-web/src/main/webapp/scripts/library_hot.js
Add the ability to do certain QC procedures in bulk via the bulk library edit page. This is a temporary feature since it doesn't allow editing existing QCs in bulk nor setting dates or other particulars on QC. This is a stop gap measure to allow adding bulk QCs for OICR rollout until we can design something more comprehensive.
=> Add library QC types

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/RunImpl.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/StatusImpl.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/MisoRequestManager.java, notification-consumer-services/src/main/java/uk/ac/bbsrc/tgac/miso/notification/consumer/service/mechanism/IlluminaNotificationMessageConsumerMechanism.java, notification-consumer-services/src/main/java/uk/ac/bbsrc/tgac/miso/notification/consumer/service/mechanism/PacBioNotificationMessageConsumerMechanism.java
Notification server failed because hibernate does not know about the
RunImpl subclasses. Modified to use RunImpl rather than subclasses. Will switch
to subclasses when the Notification Server is revisited.
=> GLT-1611 Notification server uses RunImpl instead of subclasses

notification-server/src/main/java/uk/ac/bbsrc/tgac/miso/notification/service/PacBioTransformer.java
So what is happening is this:
The new PacBio Sequel machine folder structure is different to the current structure.  This transformer doesn't handle the new folder structure so tries to pull 'sequencerName' out of the wrong place, throws an exception causing the transform method to return early - undoing all it's work so far!
Catching and logging here enables to method to complete so at least recognised PacBio runs will be populated.
Next step is to parse the new directory structure...
=> PacBio Transformer dies on surprising JSON

core/src/main/java/com/eaglegenomics/simlims/core/Group.java, core/src/main/java/com/eaglegenomics/simlims/core/SecurityProfile.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractLibrary.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractProject.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractRun.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/PoolImpl.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/ProjectOverview.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SequencerPartitionContainerImpl.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/TargetedSequencing.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/UserImpl.java
Marked smaller collections as subselect so they will be completely
loaded on the first reference. Marked larger collections as batch so items
will be retrieved in chunks instead of one at a time.
=> GLT-1637 Modify how hibernate loads collections

miso-web/src/main/webapp/scripts/shared_hot.js
In cases where the cause of the failure is known, that info gets displayed instead of the generic "Something has gone terribly wrong" message.
=> Update error message with more info if save fails due to constraint violations

miso-web/src/main/webapp/pages/editSequencerPartitionContainer.jsp
I must have missed this while changing all instances of "Lane" to "Partition".
=> Restore double-click-to-scan-pool-barcode functionality

sqlstore/src/main/resources/db/migration/V0270__auto_main.sql, sqlstore/src/main/resources/db/migration/V5201__PacBio_library_options.sql
I accidentally mis-numbered a migration in the last release and it didn't get picked up by `compact-migrations`, so it got applied to the database independently. This PR moves the code from that migration into the V270 migration that resulted from compaction, because it has already been applied to the database.
The next OICR release should go smoothly, as I have already deleted the V5201 record from `schema_version` and updated the checksum for V0720:
```
mysql > DELETE FROM schema_version WHERE version = 5201;
mysql > UPDATE schema_version SET checksum = '-74045544' WHERE version = 0270;
```
=> fix migration numbering -- db changes required

miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/context/ApplicationContextProvider.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/component/CommonModelAttributeProvider.java, miso-web/src/main/resources/external/miso.properties, miso-web/src/main/resources/internal/miso.properties, miso-web/src/main/webapp/header.jsp
Bug URL was provided by ApplicationContextProvider, which still worked on my machine, but apparently stopped working on staging and prod.
Instance name was in the ROOT.xml instead of properties file.
Both are now set in miso.properties and injected via CommonModelAttributeProvider into models returned from all Controllers.
=> GLT-1803: fix properties used in header.jsp

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/PoolOrderCompletion.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SequencingParametersImpl.java, miso-web/src/main/webapp/scripts/list.js
GLT-1853 Avoid redrawing order table when dynamically adjusting the visibility
of the columns. This reduces the number REST calls made and improves the display
time of the table.
Made retrieval of OrderCompletion_Items EAGER. This reduces the total number of
SQL queries hibernate issues when displaying the order page.
=> GLT-1853 Avoid redrawing order table when adjusting visibility of columns

miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java
Before, they had to be of the sample sample class to show the correct library
designs, but this is now done on a per library basis, so this check is
unnecessary.
=> Remove restriction that all libraries be of the same sample class

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Sample.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SampleClass.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/LimsUtils.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/SampleClassService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleClassService.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/MenuController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleClassController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleController.java
This fixes a bug where tissue class was not inferred for tissue processing
samples created directly. It also shares that logic for all sample class
inference. Additionally, it limits the list of available option so that new
samples cannot be created from a class with no inference path to an identity.
JIRA: GLT-1922
=> Refactor and fix problems with inferring tissue for tissue processing

miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/DetailedSampleDto.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/LibraryDto.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/PoolDto.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleDto.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleStockDto.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/LibraryRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleController.java, miso-web/src/main/webapp/scripts/hot.js
This will cause the numbers to be saved with user-defined precision, instead of Handsontable-implemented precision.
=> Use strings in front end for double fields

miso-web/pom.xml, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/SampleBulkCreateIT.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/BulkSamplePage.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/element/HandsOnTable.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/element/HandsOnTableSaveResult.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/element/SampleHandsOnTable.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/util/MoreExpectedConditions.java, pom.xml
* Eliminated need for explicit waits
* added skipUTs parameter to skip unit tests but not integration tests
* Can use skipITs and skipUTs together: `mvn clean verify -DskipUTs=true -DskipITs=false`
* Defaults are unchanged: unit tests run, ITs don't
* `-DskipTests=true` will still skip all tests unless overridden by one of the other attributes
=> Bulk sample IT fixups

miso-web/pom.xml
Maven pre-integration-test phase still runs even when integration tests are skipped (because you know.. probably very useful). You can put plugin config into the integration-test-setup profile to prevent it from running when integration tests are skipped
Side note: the docker plugin is not working on my machine, but looks like I'm just missing some config
=> moved Docker/MySQL config into Maven integration-test-setup profile

migration/src/main/java/uk/ac/bbsrc/tgac/miso/migration/destination/DefaultMigrationTarget.java
This is just getting rid of the changelog entry created by DB trigger
=> fix migration of dilution changelog when library was already migrated

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractLibrary.java, miso-web/pom.xml, pom.xml
* some libraries were failing to update due to weird SQL generated by Hibernate for `FetchMode.SUBSELECT` when lazy-loading a library's indices. Was happening when setting nonStandardAlias on existing libraries with duplicate aliases
* Deploy to Tomcat was working before removing the FetchMode annotation and interestingly failed after removing it. Was due to dependency clash in miso-web. A different version of `bouncycastle.org:bcprov` was introduced by docker-maven-plugin, which doesn't seem to belong as a dependency anyway
=> removed unused plugin dependency, fix library update bug

migration/src/main/java/uk/ac/bbsrc/tgac/miso/migration/destination/DefaultMigrationTarget.java
Required for creating ghost aliquots in pinery-miso-migration when the stock comes from an already-migrated project
=> allow non-null SampleClass on entities representing pre-migrated samples

miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultRunService.java
If user has set status to Started/Running/Requested/Unknown, run scanner will now override that to update the status if it sees that the run has Completed/Failed.
=> GLT-2073 override user-set 'not done' if run is 'done'

miso-web/src/it/resources/db/migration/V9000__integration-test_data.test.sql
Current order of script work fine on develop branch, but causes issues when there exist site-specific DB migrations that introduce new value-type data
=> fixed order of deletes in integration test data

miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/PoolDto.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/AbstractListPage.java, miso-web/src/main/webapp/scripts/list_pool.js
From an internal request to replace previously removed functionality to calculate average insert size of pools selected on the List Pools page.
Users can select a number of pools and click "Avg. Insert Size", and an OK dialog is shown with the results of the calculation.
=> Add average insert size calculation button

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/LibraryDesignCode.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/LibraryDesignCodeDto.java, miso-web/src/main/webapp/scripts/hot.js, miso-web/src/main/webapp/scripts/hot_dilution.js, sqlstore/src/main/resources/db/migration/V8503__tarseq_required.sql
This patch doesn't actually make targeted sequencing required for any library design codes, as those are institute-specific. For testing on OICR, run this on your DB after the included migration:
```
UPDATE LibraryDesignCode SET targetedSequencingRequired = 1 WHERE code <> 'WG';
```
This will be added in a PR to `oicr` branch as well
=> GLT-2046: require targeted sequencing depending on library design code

miso-web/src/main/webapp/scripts/hot.js, miso-web/src/main/webapp/scripts/hot_dilution.js, miso-web/src/main/webapp/scripts/hot_library.js, miso-web/src/main/webapp/scripts/hot_sample.js, miso-web/src/main/webapp/scripts/lims.js
The JSON parser can't handle `undefined`, so this change adds a null if the Handsontable unpack field is undefined.
=> fix JSON parsing errors in Lib & LD Handsontables

runscanner/src/main/java/uk/ac/bbsrc/tgac/miso/runscanner/processors/DefaultPacBio.java
There is a second round of URL encoding which happens in Spring's `getStatus` method, so PacBio runs with spaces in the name were having their names URL-encoded twice, resulting in a URL that did not point to the correct run on the PB machine. This fix is for the inevitable future issue where someone decides that the run name really should have spaces in it.
=> Remove premature URL encoding

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/printing/Driver.java
This fixes a problem where the text would run into the barcode, preventing it
from scanning correctly.
=> Move barcode to the left for square labels

miso-web/src/main/webapp/pages/editProject.jsp, miso-web/src/main/webapp/pages/permissions.jsp, miso-web/src/main/webapp/scripts/lims.js
Only affects behaviour of Edit Project page and Create Project page.
Looks like this when fully collapsed:
=> GLT-1252 add collapse button to edit project page

sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_partitionqc.sql
When the Run_Partition_QC table is changed, compose some fields and store them in temporary user variables.  Store the changed records in both `SequencerPartitionContainerChangeLog` and `RunChangeLog`.
I auto-formatted the file for readability, apologies in advance.
=> GLT-2108: Add Lane QC changes to RunChangeLog

migration/src/main/java/uk/ac/bbsrc/tgac/miso/migration/destination/MisoServiceManager.java, migration/src/test/java/uk/ac/bbsrc/tgac/miso/migration/destination/ValueTypeLookupTest.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultInstrumentStatusService.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleClassDao.java
The following implementations were packaged with interfaces, so I moved them to their respective implementation packages:
DefaultInstrumentStatusService
HibernateSampleClassDao
=> Move miscellaneous implementations into interface packages

miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultPartitionQCService.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePartitionQcDao.java
Using `@Synchronize("SequencerPartitionContainer")` on PartitionQC doesn't work for some reason, so full flush is needed
=> GLT-2197: correct user in Partition QC changelogs

miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/BarcodableDto.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/BarcodableViewService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultBarcodableViewService.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/BarcodableSearchRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/util/form/PaneAjaxTag.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/util/form/PaneTag.java, miso-web/src/main/webapp/WEB-INF/miso-form.tld, miso-web/src/main/webapp/pages/mainMenu.jsp, miso-web/src/main/webapp/scripts/list_partition.js, miso-web/src/main/webapp/scripts/pane.js, miso-web/src/main/webapp/scripts/pane_barcode.js, miso-web/src/main/webapp/scripts/pane_instrument_status.js, miso-web/src/main/webapp/scripts/search.js, miso-web/src/main/webapp/scripts/tile.js, miso-web/src/main/webapp/styles/style-full.css, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/BarcodableViewDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateBarcodableViewDao.java
Create a search widget that takes a name, alias, or barcode.
Also remove Sample, Library, Pool, and Library Dilution widgets that are now obsolete.
`tile.js` has been separated into `pane.js` for Pane-related functions and `tile.js` for Tile-related functions.
All commits will be renamed and squashed before merging.
Screenshot: 
I picked a barcode that had more than 1 matching entry (edge case, but possible).
=> GLT-2183: Create search widget

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/spreadsheet/SampleSpreadSheets.java
If the object in the spreadsheet has it, use it rather than looking at its parents
JIRA: GC-1729
=> Don't climb hierarchy unnecessarily when making spreadsheets

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Sample.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/printing/Driver.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/BulkSamplePage.java
- Use `StandardCharsets` to avoid `getBytes` by string and its exceptions
- Change the sample concentration units to have a L for litres.
- Set the Zebra printer encoding to be UTF-8 using `^CI28`
=> Add concentration and volume to Zebra labels

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/printing/Driver.java
There are now two version of this label: one for small tubes and one for slides/tissue containers
=> Add a second THT-155-590 label

runscanner-illumina/main.cpp
The changes read to clusters, remove this previous ill-conceived cluster number
and adds a reads/cluster PF number.
=> Change reads/cluster terminology in Illumina summary

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/SampleStore.java, miso-service/src/test/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleServiceTest.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDao.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDaoTest.java
GC-1792
deduplicates identities found when the target external name has two comma-separated parts.
=> DetailedSample: fix external name lookup

miso-web/src/main/webapp/scripts/hot_qc.js
This brings the QC number handling in line with how we do other floats (see `makeColumnForFloat`). HoT has an inherent limitation where if the column is of type `numeric` then you have to specify the format of the number, which is rigidly applied, ie. if format is `0.00` then `1 -> 1.00` and `1.003 -> 1.00`. This solves it by having it be displayed as text (so however many decimal places are entered get preserved) but validated as a number.
=> GLT-2324 allow variable number of decimal places for QCs

miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkLibraryIT.java, miso-web/src/main/webapp/scripts/hot_library.js
#1409 (looks like I never merged this, oops)
Solves the problem where new users get annoyed because they can't create any libraries if they haven't added any sequencers. Also helpful for users who may be preparing libraries and sending them elsewhere for sequencing.
=> Allow library creation for all platforms

docs/_posts/2017-12-07-admin-guide.md, sqlstore/src/main/resources/db/migration/V8501__nonUniqueIndices.sql, sqlstore/src/main/resources/db/migration_beforeMigrate/05_add_index.sql
The existing unique constraint doesn't always make sense with unique dual indices. Removal is necessary to add the indices requested in GC-2001. The migration checks for existence of the unique key before deleting it because I intend to run the SQL in production before it's released, so it needs to be idempotent.
=> Allow non-unique indices within a family

pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllSamples.sql
This change should have been made either way, but I have no idea why it was causing the libraries to not show up in the flatfiles "all samples" endpoint.
=> GLT-2464: fixed missing Libraries in Pinery

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/printing/Driver.java
Fixes bug where printers would print HTML encoding literals instead of the micro character.
GLT-2463
=> Fix special characters for printers

miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/AbstractIT.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/WorksetPage.java
Seems to prevent the `StaleElementReferenceException` on `WorksetPageIT#testCreate`. I also only saw a single test (`ProjectPageIT#testConfirmTablesAllVisibleWithoutErrors`) time out in 5 test runs on Travis, but that could just be random, since these changes really shouldn't help with the timeouts.
=> Fix travis ITs

miso-web/src/main/webapp/scripts/run_graph.js
Add lineGraph_CustomX() which draws a line graph with a custom starting
point ("floor") on x axis.
Convert lineGraph() to calling lineGraph_CustomX() with '0' as floor.
Changes 'Lane' graph to drawing lineGraph_CustomX with floor of '1', as
per ticket.
New function allows changing floor of any other line graphs in the future.
=> [GLT-2414] Add line graph with custom x axis floor

runscanner/src/main/java/uk/ac/bbsrc/tgac/miso/runscanner/Scheduler.java
If scanning has not yet started, return an empty set when getting list
of Unreadable runs. This prevents a NullPointerException when accessing
the Unreadable page on the web interface before scanning has started.
=> Return empty set of Unreadables

miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-web/src/main/webapp/scripts/hot_library.js
GLT-2548
Fixes issue where when selecting indices for an index family with `uniqueDualIndex == true`, an index sequence would get pasted into Index 1 but the function that finds the corresponding index 1 and index 2 would error before validating the index 1 value and before finding the correct index 2.
=> Fix unique dual index paste

miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java, sqlstore/src/main/resources/db/migration/V8242__discards_non-null.sql
Discards is a required field when saving via the UI, but is not currently set when creating ghost slides. This PR sets discards to zero on ghost slides so that users don't encounter an error when they try to save the ghost slide via the UI.
=> fixup set required attr (discards) on ghost slides

miso-web/src/main/webapp/scripts/run_graph.js
Fixes bug where the "Lane" chart mislabelled the lanes (off-by-one, so lane 2 data was being displayed as lane 1) and didn't display data for lane 1.
GLT-2572
=> Fix Cluster PF chart x-axis

miso-web/.settings/org.eclipse.wst.jsdt.core.prefs, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java, miso-web/src/main/webapp/scripts/hot.js, miso-web/src/main/webapp/scripts/hot_sample.js
Intentionally left out of the default `miso.properties` and not documented because it is a strangely specific setting that nobody outside of OICR would ever care about
=> GLT-2562: add properties for default LCM Tube group ID/desc

miso-web/src/main/webapp/scripts/list_attachmentcategory.js
Service layer never had a check for admin, so this was probably just a copy/paste error on my part
=> GLT-2578: allow all users to create attachment categories

miso-web/src/main/webapp/pages/editBox.jsp
It's sized to match the height of an 8x12 box, so it looks nice beside that, and is of reasonable size next to other boxes. Did not make it dynamic, as it would be annoyingly small next to a box much shorter than 8 rows, and boxes don't get much larger.
=> limit height of bulk selection controls on box page

miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkLibraryIT.java
Selenium often misreads how many zeros are in the SPIKE_IN_DILUTION column and causes the test to fail, making it unreliable. This deletes the offending lines.
=> Fix failing IT

.travis.yml, sonar-project.properties
Note: Build will fail on PR because Sonar needs this to be merged in order to run on develop before it can run on PRs
=> update SonarCloud configuration

travis_jobs.sh
Since this worked before, I'm guessing Travis used to set `TRAVIS_PULL_REQUEST_SLUG` even for non-pull-request builds, but it doesn't any more
=> fix Sonar running on push builds

readme.md
Fix broken links in README so sonarcloud status badge displays properly
=> fix sonarcloud badge in readme

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractLibrary.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractSample.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/DetailedSampleImpl.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/LibraryDilution.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/PoolImpl.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/LimsUtils.java
Change LimsUtils.makeVolumeAndConcentrationLabel to accept VolumeUnit
and ConcentrationUnit types rather than String.
makeVolumeAndConcentrationLabel tests for null inside method, removing
need for testing getVolumeUnits() and getConcentrationUnits() for null
within the call to makeVolumeAndConcentrationLabel.
=> Handle null Volume and Concentration units

miso-web/src/main/resources/external/miso.properties, miso-web/src/main/resources/internal/miso.properties
Prevents errors from being thrown when the fake URL doesn't resolve. As per issue raised on Gitter.
=> Comment out runscanner URLs by default

miso-web/src/main/webapp/header.jsp
Note: link is currently broken because "V2" was removed from the title/filename. That change will be deployed at the same time as this
=> changed Help tab link to new User Manual

miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
to() was falling through to the default case and throwing NotImplementedException. This keeps it from doing that.
=> Accomodate Oxford Nanopore in Dtos.to()

.docker/tomcat/ROOT.xml, docs/_posts/2016-01-11-installation-guide.md, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/context/MisoAppListener.java
Anything you put in `/storage/files/freezermaps/` (depending on your `miso.properties` settings - this is the default location) will be statically served at `<host>/freezermaps/`. Note that similar to the `scripts` and `styles` directories, it will not be under `/miso`
=> GLT-2799: symlink /storage/files/freezermaps/ to be served statically

RELEASE_NOTES.md, miso-web/src/main/webapp/scripts/hot_library.js
Issue occurred when selecting a box position and index family when no library template was chosen
=> GLT-2836: fixed unresponsive bulk library table

.docker/demo.detailed.yml, docker-compose.plain.yml, docs/_posts/2019-05-01-compose-installation-guide.md
Alexis found during release today that the compose files still had `webapp` ports bound to 8080/8090, and when trying to look up the docs I discovered that they were wrong. So, fixed.
=> Fix ports and compose docs

build_docs.sh, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/util/form/TagUtils.java, miso-web/src/main/webapp/WEB-INF/header.jsp, miso-web/src/main/webapp/WEB-INF/miso-form.tld
For now, this is only going to build 0.2.x. Will make more sense after 1.0 when our regular releases are minor versions and it builds 1.1.x, 1.2.x, etc. where patch versions may contain docs updates to include in the same minor version.
I'll add this to the release procedure after it's merged. We'll have to change the GitHub settings to use `gh-pages` after the next release.
=> GLT-2829: added script for building versioned docs

readme.md
It complained at me that MISO_TAG wasn't set when I tried running it
=> Add 'Export' to Docker instructions

RELEASE_NOTES.md, miso-web/src/main/webapp/scripts/hot_library_receipt.js, miso-web/src/main/webapp/scripts/list_library.js
Putting periods in field names should cause Handsontable to create nested objects and fields. In rare (and as of yet unknown) circumstances, it fails to do this, and consistently does so on flat.sample.scientificName, creating a situation where on save there is an extra field flat["sample.scientificName"] which contains a string but flat.sample.scientificName is null. Detects when this happens and forces the value back to the correct place to enable saving. Does not fix the underlying issue. Can't seem to pinpoint it, this broken field seems to pop up at the call to pack.
Also corrects a typo in an unrelated function. Don't know if that's ever called.
=> [GLT-2916] Patch 'No Scientific Name' bug

miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultPoolService.java
When creating a new Pool, validation is called with a null
'beforeChange' pool. Prevent NPE in this case while preserving check for
conflicting indices
=> [GLT-2922] Check for null pool

RELEASE_NOTES.md, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/component/ExceptionHandlerAdvice.java
In the case of ValidationException being thrown when creating a new
page, the generic Server Error page appears without explaining the
error. Define new page that prints all the errors.
=> GLT-2969 Show message when Validation Error occurs

RELEASE_NOTES.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultPoolOrderService.java, miso-web/src/main/webapp/scripts/form_poolorder.js
* Check on adding Library Aliquots (& therefore, Pool Order creation) for duplicate & near duplicate indices, block action
* Check if pool is known to contain duplicate or near duplicate indices on linking to pool order, block action
=> GLT-2944 Inhibit duplicate-index actions on Pool Orders

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/PoolOrder.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/changelog/PoolOrderChangeLog.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultPoolOrderService.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditPoolOrderController.java, miso-web/src/main/webapp/WEB-INF/pages/editPoolOrder.jsp, sqlstore/src/main/resources/db/migration/V8000__pool_order_changelog.sql, sqlstore/src/main/resources/db/migration/V8001__pool_order_create_trigger.sql
Since Create/Link Sequencing Orders buttons appear to be broken, change logs can be added for them when they get fixed, probably by me (GLT-2983, GLT-2984)
=> GLT-2979 Pool Order changelogs

miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/component/ExceptionHandlerAdvice.java
`ValidationException` should only be thrown from the service layer during save/update/delete attempts, which should only happen through `RestController`s. Also, there was a bug in showing the error page for `ClientErrorException`s
=> front-end exception handling fixup

RELEASE_NOTES.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/LibraryAliquot.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryAliquotService.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/LibraryAliquotRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/LibraryRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleRestController.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryAliquotDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolDao.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryAliquotDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolDaoTest.java
Previous problem was caused by attempting to lazy load `LibraryAliquot.pools`. Switching to eager loading caused slowness. Fixed by removing the pools collection entirely and retrieving from the `PoolService` only when needed
=> GLT-3068: improved performance of library aliquot related things

RELEASE_NOTES.md, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/util/form/TagUtils.java, miso-web/src/main/webapp/WEB-INF/footer.jsp, miso-web/src/main/webapp/WEB-INF/header.jsp, miso-web/src/main/webapp/WEB-INF/miso-form.tld
I don't have an explanation as to why, but `<%=Version.VERSION%>` was sometimes returning the version from a previous build, whereas the one generated via a `TagUtils` method for the docs version was always correct, so I changed the other uses of version to go through `TagUtils` too :man_shrugging:
=> fixed version number shown in page footer

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/security/LDAPSecurityManager.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/security/util/LimsSecurityUtils.java
There appears to be no guarantee that the implementation of UserDetails we get will be an InetOrgPerson (external user seeing LdapUserDetailsImpl instead). The only methods we use outside of the interface are the Display Name and Email getters, so only use those if instanceof InetOrgPerson.
Still setting up LDAP Server locally to test against, but requesting thoughts on this approach to ensure there aren't obvious pitfalls
=> LDAP Compatibility Fix

miso-web/src/main/webapp/WEB-INF/standard-security-config.xml
`security="none"` means Spring Security doesn't intercept the patterns. Intercepting and permitting all means Spring Security will allow all users, but will also add the default security headers (or customized ones, though we're not customizing them in this case).
=> GLT-3221: add security headers to all requests

RELEASE_NOTES.md, miso-web/src/main/webapp/scripts/bulk_sample.js
Replaces previous PR. This just fixes the required field as other changes already merged into develop have fixed the default values
=> GLT-3270: fixed scientific name required

RELEASE_NOTES.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/LibraryAliquot.java, miso-web/src/main/webapp/styles/style-full.css
Also, _someone_ clearly used replace all in the css file 🤦‍♂️
=> GLT-3290: fixed library aliquot location showing barcode

RELEASE_NOTES.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleClassService.java
Eclipse likes turning my `.equals` into `.contentEquals`, `.stream` into `.parallelStream`, etc... Looks like it's related to a bug that goes back to 2016... 🎉 https://bugs.eclipse.org/bugs/show_bug.cgi?id=506804
=> GLT-3291: fixed creating stock sample classes

docs/admin/baremetal-installation-guide.md
* MariaDB 10.2.3 adds the JSON functions used in V0320
* The only issue I've found reported for V0611 is permission-related, and advising users to ignore and skip the migration could result in attachments being lost/orphaned (In #1669)
=> updated recommendations for migration error work-arounds

sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_array.sql, sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_arrayrun.sql, sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_box.sql, sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_container.sql, sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_containerqc.sql, sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_experiment.sql, sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_kit.sql, sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_libraryqc.sql, sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_pool.sql, sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_poolorder.sql, sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_poolqc.sql, sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_project.sql, sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_run.sql, sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_runpartition.sql, sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_sampleqc.sql, sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_storage.sql, sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_study.sql, sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_transfer.sql, sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_workset.sql, sqlstore/src/main/resources/db/migration_beforeMigrate/00_functions.sql
Applying these migrations and setting runpath or description on a run from a 255-char string to a different 255-char string still causes `Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'makeChangeMessage('description', OLD.description, NEW.description)' at row 1` or similar
=> Long changelog messages

RELEASE_NOTES.md, miso-web/src/main/webapp/scripts/list_qc.js
`precisionAfterDecimal < 0` means it's a boolean (pass/fail) QC. `results` (`data` in the render function) is a decimal string though, so it will be either "0" or "1"
=> GLT-3408: fixed failed QCs showing as checkmark

.travis.yml, travis_jobs.sh
* Sonar no longer supports Java 8, and it wasn't set up correctly anyway
* GSI Maven settings should not be required for MISO build
* I couldn't even find the Slack channel that notifications were supposed to be going to, but I don't think anyone wants this anyway
=> removed Sonar and unneccessary Travis config

RELEASE_NOTES.md, sqlstore/src/main/resources/db/migration/V8505__cascade_delete_changelogs.sql
What was happening:
* `DefaultPoolService#beforeDelete` deletes sequencing orders for the pool
* `PoolChange` trigger in MySQL adds a changelog to the Pool to record the order deletion
* `PoolImpl` changelog is annotated to cascade remove, so Hibernate deletes the changelogs it knows about. Unfortunately, it doesn't know about the one that was just generated by the trigger
* Hibernate tries to delete the pool and gets a foreign key violation error due to the new changelog
=> [GLT-3453] Fixed deletions prevented by changelog writing

changes/add_2532_illumina_experiment_types.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/IlluminaExperiment.java
This PR addresses #2532 adding 2 new IlluminaExperiment types for Application "FASTQ Only" for Assays "Nextera XT" and "TruSeq Nano DNA" for Illumina sample sheet CSV creation.
=> Add 2 new IlluminaExperiment types for Illumina sample sheet CSV creation

docs/admin/compose-installation-guide.md
Commit d0e89ca45e7b929508aac581105153dcaca936f0 changed the requirement to navigate to localhost/miso when launching MISO, and updated the README.
Updates the instructions in the documentation to match following github issue #2568.
=> Correct localhost/miso to localhost

RELEASE_NOTES.md, changes/fix_runscanner_kit_type.md, changes/fix_runscanner_updates.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/KitDescriptorService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultKitDescriptorService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultRunService.java, miso-service/src/test/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultRunServiceTest.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateKitDaoIT.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/KitStore.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateKitDao.java, sqlstore/src/main/resources/db/migration/V8501__mark_run_failed_dates.sql
Putting Run Scanner runs through the standard validation revealed a few minor data issues. All should be resolved automatically with this release. Notably:
* Runs that are marked failed, but have no completion date will have their completion date set to match the start date (via Flyway migration)
* There are some ONT kits that are duplicated to be used as both library and sequencing kits. In some cases, the library kits were wrongly assigned as sequencing kits. These will be corrected automatically the next time MISO receives the affected runs from Run Scanner
=> [GLT-3600] fix Run Scanner updating runs without changes

sqlstore/src/main/resources/db/migration/V0320__auto_main.sql, sqlstore/src/main/resources/db/migration/beforeValidate.sql
MariaDB doesn't have a JSON datatype, but `JSON_EXTRACT` works on strings in MySQL too, so the `CAST` is not necessary
=> [#2621] fix DB migration for MariaDB 10.2.41

changes/fix_slf4j_version.md, core/pom.xml, integration-tools/pom.xml, miso-service/pom.xml, miso-web/pom.xml, pinery-miso/pom.xml, pom.xml, sqlstore/pom.xml
`log4j-slf4j18-impl` uses a beta version of slf4j, so we'll stick with `log4j-slf4j-impl` for now instead
Requires a Pinery release and updating the Pinery version in `pinery-miso/pom.xml` before merging
=> [#2626] align log4j and slf4j versions

.docker/demo.detailed.yml, .docker/demo.plain.yml, changes/change_container_registry.md, changes/fix_nginx_restart.md, changes/note_container_registry.md, docs/admin/compose-installation-guide.md, docs/developers-manual.md
Notes:
* updated release procedure: https://wiki.oicr.on.ca/display/MISO/Release+Procedure
* build leads will need to update their GitHub token (or generate a new one) before they can push. I'll post more info on Slack
* removed the section from developer's manual as this is just a duplication of the release procedure
* included restart policy fix here since it's related
=> Updated to use GitHub container registry

changes/fix_dependencies.md, changes/note_pinery.md, changes/note_runscanner.md, pinery-miso/pom.xml, pom.xml
Jira ticket or GitHub issue: 
Requires Pinery release and updated Pinery version in this PR before merging
=> update to Jackson 2.13.2 via BOM, and Pinery's Spring version

changes/change_download_columns.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/spreadsheet/SampleSpreadSheets.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/context/WebConfig.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/BoxRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/ContainerRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/HotRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/LibraryAliquotRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/LibraryRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/PoolRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/RunRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleRestController.java, miso-web/src/main/webapp/scripts/lims.js
Includes fix for bug that was caused recent change to default ObjectMapper used in MessageConverter
* Changed `ObjectMapper` creation to use `Jackson2ObjectMapperBuilder` so it would include some default settings set by Spring
* Changed spreadsheet requests to set `Accept` header, which tells Spring which `MessageConverter` to use. I'm really not sure how it was choosing the correct one before, or how defining a `MessageConverter` for JSON affected that since the default converters are still there
* Added `produces` parameter to mapping annotation for downloads, which also determines the MessageConverter to use. Only this *or* the accept header (above) is needed, but setting both to be safe
* Not including a change file for the fix since the bug was not in a release
Jira ticket or GitHub …
=> [GLT-3675] sample download sheet updates

RELEASE_NOTES.md, compact-changelog.sh
The change-to-be-reverted did allow the `@` character to be processed correctly during the last set of changelogs -> release notes, but did not handle newlines properly
Jira ticket or GitHub issue: N/A
=> Revert changes to compact-changelog and fix the formatting errors it introduced to the release notes

changes/fix_print_receiptTime.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/transfer/Transfer.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/view/transfer/ListTransferView.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-web/src/main/webapp/scripts/list.js, miso-web/src/main/webapp/scripts/list_samples.js, miso-web/src/main/webapp/scripts/list_transfer.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3968
`TemporalType.DATE` gets populated as `java.sql.Date`, which is a subclass of `java.util.Date` that throws `UnsupportedOperationException` on `toInstant()`. We use `LocalDate` for date-only types elsewhere to avoid this and other problems, but in this case it should actually be a timestamp
=> [GLT-3968] fixed printing sample labels with received date

changes/fix_advancedSearch_dates.md, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/component/DateRangeParser.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3970
Besides the "day" range spanning a month, bugs would have been introduced when switching to `ZonedDateTime`, which uses 1-based month and date. Previous implementation used 0-based month and date.
=> [GLT-3970] fixed advanced search date pattern parsing

changes/add_between_runLibMetric.md, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/dashi/RunLibraryQcTableRequestMetricDto.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/dashi/RunLibraryQcTableRowMetricDto.java, miso-web/src/main/webapp/scripts/runLibraryMetrics_ajax.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4084
Using `minimum` and/or `maximum` fields as in other places would have been nicer than `threshold` and `threshold2`, but this way is backwards compatible. This doesn't require Dashi changes, and we don't need to do Dashi, Dimsum, and MISO releases all at the same time.
=> [GLT-4084] support range metrics on Run-Library metrics page

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/RunPartitionStore.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRunPartitionDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4190
Refactored to extend HibernateProviderDao/ProviderDao for now. RunPartition does not extend Identifiable and HibernateRunPartitionDao cannot be refactored to extend HibernateSaveDao.
=> [GLT-4190] Update HibernateRunPartitionDao to JPA Criteria

miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/view/MisoContextController.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4273
Did not include a change file as this is just a precaution and not going to actually fix any existing problems. Existing problems at OICR will be fixed by updating links from other systems so that this redirect is not used for POST requests. It's extremely unlikely that anyone else is using the run-library metrics page, and there shouldn't be any other POST requests coming from outside of MISO itself.
=> [GLT-4273] fixed POST requests to  redirecting to GET

miso-web/pom.xml, pom.xml
Jira ticket or GitHub issue: https://github.com/miso-lims/miso-lims/security/dependabot/12
I think j2html replaced jdom in MISO, but either way jdom doesn't seem to be used anymore
=> removed jdom dependency; updated j2html

changes/fix_savedQc_dsiplay.md, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateContainerQcDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryQcDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolQCDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateQcStore.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRequisitionQcDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleQcDao.java
Jira ticket or GitHub issue: https://github.com/miso-lims/miso-lims/issues/3019
All the QC DAOs were providing the entity ID instead of the QC ID. `HibernateQcStore#listByIdList` was supposed to be returning the QCs with the provided IDs, but instead was looking up the entities with the provided IDs and returning all of their QCs.
=> [#3019] fixed bulk QC pages showing wrong items after saving

changes/fix_pineryTimezone.md, pinery-miso/src/main/resources/pinery-miso-config.xml
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4371
=> [GLT-4357] make Pinery use DB server timezone

changes/fix_printByColumn.md, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/PrinterRestController.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4376
=> [GLT-4376] fixed sorting when printing barcodes by column

.docker/demo.detailed.yml, .docker/demo.plain.yml, docker-compose.detailed.yml, docker-compose.plain.yml, docs/admin/compose-installation-guide.md
This is to fix the error "field VolumeOptions must not be specified" when using recent versions of Docker Compose.
Jira ticket or GitHub issue:
=> Remove use of volume options for bind mounts

miso-web/pom.xml, pom.xml
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4645
Now, when you run `mvn clean verify -DskipSTs=false ...`, an `index.html` file will be created in `/miso-web/target/site/`. Opening this file in a browser will take you to a report which gives you information regarding the endpoint coverage.
=> [GLT-4645] added Spring Test controller endpoint coverage metrics

miso-web/src/spring-test/java/uk/ac/bbsrc/tgac/miso/webapp/springtest/PoolRestControllerST.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4655
My apologies, I changed the test data in a different controller test so Run with id 1 now uses instrument with id 1 instead of id 2. I didn't realize this before I merged the pool rest tests, so this is a fix for that.
=> [GLT-4655] pool rest test fix due to change in test data from a different test
