miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/AbstractListPage.java, miso-web/src/main/webapp/scripts/list_indices.js
=> Show position on List Indices table

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Library.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Sample.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/type/LibrarySelectionType.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/type/LibraryStrategyType.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/type/LibraryType.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/type/SubmissionActionType.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/EnaSubmissionPreparation.java, docs/_posts/2016-09-20-user-manual-v2.md, docs/user_manual/european_nucleotide_archive_support.md, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SubmissionRestController.java, miso-web/src/main/webapp/pages/adminsub.jsp
=> Add SRA user manual

pinery-miso/README.md, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllSamples.sql
I still can't deploy Pinery locally, so this is a best guess...
=> Export creation date and PDAC via Pinery

miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java, miso-web/src/main/webapp/scripts/hot_sample.js
GLT-2602
includes tests for Index Distance tool & Identity Search tool
=> Fix Identity Search tool (DetailedSample mode)

docs/user_manual/deletions.md
=> User manual: Deletions

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SequencingParameters.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditRunController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
=> Sort sequencing parameters

miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/MenuController.java
This only partially fixes the slowness issue, in that there may still be MISO slowness every 15 minutes when getting the new file.
=> Cache constants file for 15 minutes

pinery-miso/pom.xml, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllSampleProjects.sql
I know I've added a SNAPSHOT version. I'm not going to merge this until the next Pinery release and will change the version to 2.2.1
=> Add Pinery project active flag

pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllRuns.sql
GR-672
As this depends on a [Pinery PR](https://github.com/oicr-gsi/pinery/pull/83), I will not merge this until a new version of Pinery is released and I've updated the Pinery version in the POM.
=> Export sequencingParams via Pinery

miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/BoxRestController.java, miso-web/src/main/webapp/scripts/box_ajax.js, miso-web/src/main/webapp/scripts/box_visualization.js
=> Clear contents of box only when doing bulk update by scanner

RELEASE_NOTES.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultRunService.java
=> Fix error with saving runs from runscanner

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/InstrumentDataManglingPolicy.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/InstrumentModel.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/SampleSheet.java, docs/user_manual/type_data.md, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllRunSamples.sql, sqlstore/src/main/resources/db/migration/V8888__add_mangling_policy.sql
=> Handle instruments which mangle the i5 index

miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultRunService.java
=> Fix create run error

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/DateType.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/PaginationFilter.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/PaginationFilterSink.java, miso-web/src/main/webapp/scripts/list.js, miso-web/src/main/webapp/scripts/list_library.js, miso-web/src/main/webapp/scripts/list_samples.js, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePaginatedDataSource.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDao.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDaoTest.java
=> Search by distribution (Samples & Libraries) and group ID (DetailedSample only)

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/ConcentrationUnit.java
=> Add picomolar concentration unit

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/naming/AbstractNamingScheme.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/naming/DelegatingNamingScheme.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/naming/NamingScheme.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/naming/generation/OicrLibraryAliasGenerator.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/naming/validation/AllowAnythingValidator.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/naming/validation/DefaultLibraryAliasValidator.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/naming/validation/DefaultNameValidator.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/naming/validation/DefaultSampleAliasValidator.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/naming/validation/NameValidator.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/naming/validation/OicrLibraryAliasValidator.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/naming/validation/OicrProjectShortNameValidator.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/naming/validation/OicrSampleAliasValidator.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/naming/validation/RegexValidator.java, core/src/test/java/uk/ac/bbsrc/tgac/miso/core/service/naming/generation/OicrLibraryAliasGeneratorTest.java, core/src/test/java/uk/ac/bbsrc/tgac/miso/core/service/naming/generation/OicrSampleAliasGeneratorTest.java, core/src/test/java/uk/ac/bbsrc/tgac/miso/core/service/naming/validation/OicrLibraryAliasValidatorTest.java, core/src/test/java/uk/ac/bbsrc/tgac/miso/core/service/naming/validation/OicrSampleAliasValidatorTest.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultBoxService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultPoolService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultProjectService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultRunService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultStudyService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/ValidationUtils.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ProjectPageIT.java, sqlstore/src/main/resources/db/migration/V8080__shortname.sql
=> Lengthen project short names

sqlstore/src/main/resources/db/migration_afterMigrate/05_delete_run.sql
=> Update deleteRun procedure

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Printer.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/DetailedSampleImpl.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/printing/BradyLabelGenerator.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/printing/Driver.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/printing/LabelCanvas.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/printing/Layout.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/printing/ZebraLabelGenerator.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/PrinterDto.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/PrinterLayoutDto.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/AbstractListPage.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/MenuController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/PrinterRestController.java, miso-web/src/main/webapp/scripts/list_printer.js, sqlstore/src/main/resources/db/migration/V8811__printer_layout.sql, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePrintServiceDaoTest.java, sqlstore/src/test/resources/db/test_migration/test_data.sql
=> Refactor printer labels

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/TargetedSequencing.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/kit/KitDescriptor.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/KitStore.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/TargetedSequencingStore.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/TargetedSequencingDto.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/KitService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/TargetedSequencingService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultKitService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultTargetedSequencingService.java, miso-service/src/test/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryDilutionServiceTest.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditKitDescriptorController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/ListKitDescriptorsController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/KitDescriptorRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/TargetedSequencingRestController.java, miso-web/src/main/webapp/pages/editKitDescriptor.jsp, miso-web/src/main/webapp/scripts/list_kits.js, miso-web/src/main/webapp/scripts/list_poolelement.js, miso-web/src/main/webapp/scripts/list_targetedSequencing.js, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateKitDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateTargetedSequencingDao.java, sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_kit.sql
=> Allow lab to link kits to targeted sequencing

pinery-miso/pom.xml, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllRunPositions.sql
Will not merge until Pinery is changed to a release version
=> GP-1840: include lane QC data in Pinery

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractLibrary.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractSample.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/ValidationUtils.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/PoolPageIT.java, miso-web/src/main/webapp/header.jsp, miso-web/src/main/webapp/pages/editLibrary.jsp, miso-web/src/main/webapp/pages/editSample.jsp, miso-web/src/main/webapp/scripts/boxable_ajax.js, miso-web/src/main/webapp/scripts/library_ajax.js, miso-web/src/main/webapp/scripts/sample_ajax.js
=> Fix bug in distributing from edit Sample/Lib page

RELEASE_NOTES.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/printing/LabelCanvas.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/printing/Layout.java
=> Fix up multiline label layout

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/StorageLocation.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/StorageLocationDto.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/StorageLocationService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultStorageLocationService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/ValidationUtils.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditFreezerController.java, miso-web/src/main/webapp/pages/editFreezer.jsp, miso-web/src/main/webapp/scripts/freezer_ajax.js, pom.xml, sqlstore/src/main/resources/db/migration/V8229__add_probeId_to_freezer.sql, sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_storage.sql
Also adds Probe IDs to freezers
=> Search for freezers by storage location barcode

.dockerignore, Dockerfile
Fixes the issue where MySQL would not start up properly on some systems.
=> Fix Docker image

docs/user_manual/type_data.md
=> User manual: link kits & targeted sequencing

miso-web/src/main/webapp/scripts/list_instrument.js
=> Fix "Add Sequencer" creating malformed DTO

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/printing/Layout.java
=> Adjust JTT7 label layouts

miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryService.java
=> Check targeted sequencing when changing library code

miso-web/src/main/webapp/scripts/warning.js, miso-web/src/main/webapp/scripts/warning_dilution.js, miso-web/src/main/webapp/scripts/warning_experiment.js, miso-web/src/main/webapp/scripts/warning_library.js, miso-web/src/main/webapp/scripts/warning_partition.js, miso-web/src/main/webapp/scripts/warning_pool.js, miso-web/src/main/webapp/scripts/warning_sample.js, miso-web/src/main/webapp/styles/style-full.css
Slightly off-blue to not clash entirely with purplish row backgrounds
=> GC-6624: Change PRIORITY message to blue

miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/BarcodableSearchRestController.java
=> Fix error when search by barcode returns container model

miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/RunPageIT.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/RunPage.java
getPoolWarningsFromTiles() returns the warning inside the span tag. Go
through List<String> to test each individual String for substring
containing the warning for which we're looking.
=> Fix testPoolTileWarnings()

miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/PrinterRestController.java
=> Sort items for printing by alias

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/printing/LabelCanvas.java
=> Fix error in multiline printer layout

miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/PrinterRestController.java, miso-web/src/main/webapp/scripts/box_ajax.js, miso-web/src/main/webapp/scripts/lims.js, miso-web/src/main/webapp/scripts/list_box.js
=> Allow printing labels by position in a box

sqlstore/src/main/resources/db/migration/V8501__fix_promethion_pos.sql
* corrects names of positions that are active at OICR
* adds positions that are not functional at OICR
* deletes positions that were incorrectly named according to both sources
Will run on stage after approved and prod after release
=> fixed naming of PromethION positions

miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultRunService.java
=> Process Oxford Nanopore data from run scanner

Dockerfile, docker-compose.yml
by reordering commands and caching .m2 repositories. Remove dependency on flyway for webapp
=> Speed up docker builds 

miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultPoolOrderService.java
=> Allow any internal user to delete a pool order

miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSequencerPartitionContainerController.java, miso-web/src/main/webapp/WEB-INF/pages/handledError.jsp
=> Fix header and footer paths on error page

miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SpreadsheetRequest.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/ContainerRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/LibraryDilutionRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/LibraryRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/PoolRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/PrinterRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/util/MisoWebUtils.java, miso-web/src/main/webapp/WEB-INF/header.jsp, miso-web/src/main/webapp/WEB-INF/pages/handsontables.jsp, miso-web/src/main/webapp/scripts/hot.js, miso-web/src/main/webapp/scripts/lims.js
This includes spreadsheet downloads and printing
JIRA: GC-6778
=> Avoid sending lists of IDs by query parameters

miso-web/src/main/webapp/scripts/box_ajax.js, miso-web/src/main/webapp/scripts/lims.js
Printer success message no longer guarantees printing success.
=> GLT-2838 update barcode printing message

docs/_posts/2016-01-11-installation-guide.md
=> Fix broken link in installation guide

RELEASE_NOTES.md, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/BulkDilutionPage.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/BulkPoolCustomPage.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/BulkPoolPage.java, miso-web/src/main/webapp/scripts/hot_dilution.js, miso-web/src/main/webapp/scripts/hot_library.js, miso-web/src/main/webapp/scripts/hot_library_receipt.js, miso-web/src/main/webapp/scripts/list_dilution.js, miso-web/src/main/webapp/scripts/list_poolelement.js
Hotfixed `header_script.js` on OICR stage and production already
=> GLT-2863: fixed bulk dilution page links

RELEASE_NOTES.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SampleType.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/SampleStore.java, docs/user_manual/type_data.md, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleTypeDto.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/DeleterService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/SampleService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/SampleTypeService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleTypeService.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/AbstractTypeDataController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/MenuController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/SampleTypeController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/RestUtils.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleTypeRestController.java, miso-web/src/main/webapp/WEB-INF/pages/adminsub.jsp, miso-web/src/main/webapp/scripts/hot_sampletype.js, miso-web/src/main/webapp/scripts/list.js, miso-web/src/main/webapp/scripts/list_sampletype.js, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/SampleTypeDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleTypeDao.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDaoTest.java, sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleTypeDaoTest.java, sqlstore/src/test/resources/db/test_migration/test_data.sql
Note: added `AbstractTypeDataController` as a more easily customizeable alternative to `AbstractInstituteDefaultsController`
=> GLT-2813: added interface for modifying sample types

miso-web/src/main/webapp/scripts/form_servicerecord.js
=> Fix service record detail validator

RELEASE_NOTES.md, miso-web/src/main/webapp/scripts/hot_dilution.js, miso-web/src/main/webapp/scripts/hot_library.js, miso-web/src/main/webapp/scripts/hot_pool.js, miso-web/src/main/webapp/scripts/hot_sample.js
=> Fix Parents and Children buttons

miso-web/src/main/webapp/scripts/list_run.js
=> Fix manually creating a sequencer run

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/naming/generation/OicrSampleAliasGenerator.java, core/src/test/java/uk/ac/bbsrc/tgac/miso/core/service/naming/generation/OicrSampleAliasGeneratorTest.java
=> Fix aliquot-aliquot alias generation

miso-web/src/main/webapp/scripts/list_poolelement.js
=> Sort dilutions by ID on pools page

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/SampleSheet.java
=> Add more columns to Cell Ranger sample sheet output

RELEASE_NOTES.md, pinery-miso/pom.xml, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllRunPositions.sql, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllRuns.sql
Rebased and combined 3 separate PRs that should be merged after the Pinery release and before the next MISO release. These have all already been reviewed separately:
* https://github.com/miso-lims/miso-lims/pull/1830
* https://github.com/miso-lims/miso-lims/pull/1986
* https://github.com/miso-lims/miso-lims/pull/1990
Pinery version in pinery-miso/pom.xml needs updated to release version before merging
=> Pinery updates

miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
=> Fix Edit Library group ID bug (detailed sample)

RELEASE_NOTES.md, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/AbstractListPage.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/ListTabbedPage.java, miso-web/src/main/webapp/scripts/list_storage_location.js, miso-web/src/main/webapp/scripts/urls.js
=> Fix list freezers

miso-web/src/main/webapp/scripts/identitySearch_ajax.js
=> Better message when no samples found in identity search (detailed sample)

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/spreadsheet/LibraryAliquotSpreadSheets.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/spreadsheet/LibrarySpreadSheets.java
This was reported by Kayla, but she hasn't filed a ticket yet. I'll add it once she does.
=> Ensure spreadsheets list indices in order

RELEASE_NOTES.md, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryAliquotController.java
GLT-2935
Library Aliquots in detailed sample mode now get properly serialized.
=> Fix 'Pool custom' error

RELEASE_NOTES.md, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BoxPageIT.java, sqlstore/src/main/resources/db/migration_afterMigrate/05_view_box.sql
=> Show library aliquot alias in box contents table

RELEASE_NOTES.md, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/IndexDistanceToolController.java, miso-web/src/main/webapp/WEB-INF/pages/indexDistanceTool.jsp, miso-web/src/main/webapp/scripts/indexDistance_ajax.js
=> Fix reset distance button

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/IndexChecker.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/LibraryAliquotDto.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/PoolOrderDto.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/PoolOrderPageIT.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/PoolOrderPage.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditPoolOrderController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/PoolOrderRestController.java, miso-web/src/main/webapp/WEB-INF/pages/editPoolOrder.jsp, miso-web/src/main/webapp/scripts/list_libraryaliquot.js, miso-web/src/main/webapp/scripts/list_orderaliquot.js, miso-web/src/main/webapp/scripts/list_poolorder.js, miso-web/src/main/webapp/scripts/poolorder_ajax.js, miso-web/src/main/webapp/scripts/warning_orderaliquot.js, miso-web/src/main/webapp/scripts/warning_poolorder.js
=> Display index checking on pool orders

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/spreadsheet/LibraryAliquotSpreadSheets.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/spreadsheet/LibrarySpreadSheets.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/PoolRestController.java, miso-web/src/main/webapp/scripts/hot.js, miso-web/src/main/webapp/scripts/hot_pool.js
This is only some of what was requested in the ticket, but the lab requested these features in the meeting today.
=> Glt 2902 have index in sheet

RELEASE_NOTES.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/PaginationFilter.java
List all unmatched names, rather than throwing exception on the first
one found.
=> GLT-2972 Show all unmatched names in bulk search

miso-web/src/main/webapp/scripts/jquery/datatables/css/jquery.dataTables.css
=> Allow toolbar buttons to wrap when full

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Index.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/IndexChecker.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/IndexDto.java, sqlstore/src/main/resources/db/migration/V8888__real_10X_sequences.sql
=> Check duplicate indices for fake (10X) families

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/SampleSheet.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/MenuController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/PoolRestController.java, miso-web/src/main/webapp/scripts/hot_pool.js
=> Allow creating sample sheets for pools

miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditPoolController.java
Behaviour was always good, but warning would display even when strict index checking was off. Don't show the pool merge warning if strict index checking is off
=> Fix warning display when strictIndexChecking is off

miso-web/src/main/webapp/scripts/hot_pool.js, miso-web/src/main/webapp/scripts/lims.js
=> Make widget to order pools for sample sheet creation

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/SampleSheet.java
=> Expand 10X barcodes as appropriate

RELEASE_NOTES.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultDetailedQcStatusService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLabService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultQcTypeService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultReferenceGenomeService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleClassService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleGroupService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSamplePurposeService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleValidRelationshipService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSubprojectService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultTissueMaterialService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultTissueOriginService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultTissueTypeService.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/MenuController.java
Doing this asynchronously means there is no authentication context, so I've had to remove some authentication checks.
=> Make saving institute defaults asynchronously regenerate constants.js

RELEASE_NOTES.md, miso-web/src/main/webapp/scripts/form_library.js
=> Fix Edit Library page with no indices

miso-web/src/main/webapp/scripts/list.js
=> Allow selecting all things from all pages in a table

RELEASE_NOTES.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/IlluminaExperiment.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/SampleSheet.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/MenuController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/PoolRestController.java, miso-web/src/main/webapp/scripts/hot_pool.js
=> Generate sample sheets like the Illumina Experiment Manager does

RELEASE_NOTES.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SequencingParameters.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/IlluminaExperiment.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/SampleSheet.java, miso-web/src/it/resources/db/migration/integration_test_data.sql, miso-web/src/it/resources/db/migration/plainSample_integration_test_data.sql, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/service/RunScannerClient.java, pinery-miso/src/it/resources/db/migration/pinery-miso_plain_test_data.sql, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllOrderSamples.sql, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllRuns.sql, pom.xml, sqlstore/src/main/resources/db/migration/V8888__sequencing_parameters_paired.sql, sqlstore/src/main/resources/db/migration_beforeMigrate/05_add_seqparam.sql, sqlstore/src/test/resources/db/test_migration/test_data.sql
=> Allow specifying two different read lengths in Illumina runs

miso-web/src/main/webapp/scripts/form.js
=> Correct generate ID of match form fields

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/IlluminaExperiment.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/PoolRestController.java, miso-web/src/main/webapp/scripts/hot_pool.js
=> Allow setting custom primer wells in sample sheet

RELEASE_NOTES.md, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/service/integration/jira/JiraIssueManager.java
=> Fix JIRA assignee null pointer

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/IlluminaExperiment.java
I don't understand why this is a thing, but it's what the lab has found out.
JIRA: GLT-2902
=> Set chemistry in sample sheet based on read count

RELEASE_NOTES.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SampleAliquotSingleCell.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SampleClass.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SampleLCMTube.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SampleSingleCell.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SampleSlide.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SampleStockSingleCell.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleClassImpl.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/LimsUtils.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/DetailedSampleDto.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleAliquotSingleCellDto.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleClassDto.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleDto.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleLCMTubeDto.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleSingleCellDto.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleSlideDto.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleStockSingleCellDto.java, miso-web/src/it/resources/db/migration/integration_test_data.sql, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java, miso-web/src/main/webapp/scripts/form_sample.js, miso-web/src/main/webapp/scripts/hot_sample.js, pinery-miso/src/it/resources/db/migration/pinery-miso_detailed_test_data.sql, sqlstore/src/main/resources/db/migration/V8000__sample_class_alias.sql
=> Move special information out of sample class alias

RELEASE_NOTES.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/IlluminaExperiment.java
=> Change order thigns are present in generated samples sheet

.docker/detailed_sample_config/V0793__detailed_sample_data.sql, RELEASE_NOTES.md, docs/_posts/2019-05-01-compose-installation-guide.md
This affected a few MISO versions. I think we missed it in the release procedure because we weren't pruning the DB volume, and so only new migrations were being tested. I'll update the release procedure to fix that as well
=> #2078: fixed detailed sample Docker demo migration

RELEASE_NOTES.md
Updated the release notes on GitHub to match already
=> #2079: noted confirm password bug and fix in release notes

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/naming/generation/OicrSampleAliasGenerator.java
=> Use tissue piece type in tissue piece alias

RELEASE_NOTES.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/LibraryTemplate.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/BoxUtils.java, docs/_posts/2018-09-20-user-manual-table-of-contents.md, docs/user_manual/libraries.md, integration-tools/src/test/java/uk/ac/bbsrc/tgac/miso/integration/test/BoxScanTests.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/LibraryTemplateDto.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryTemplateService.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryTemplateController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/LibraryTemplateRestController.java, miso-web/src/main/webapp/WEB-INF/pages/editLibraryTemplate.jsp, miso-web/src/main/webapp/WEB-INF/pages/editProject.jsp, miso-web/src/main/webapp/scripts/form.js, miso-web/src/main/webapp/scripts/form_librarytemplate.js, miso-web/src/main/webapp/scripts/hot_library.js, miso-web/src/main/webapp/scripts/hot_library_template.js, miso-web/src/main/webapp/scripts/hot_library_template_index.js, miso-web/src/main/webapp/scripts/librarytemplate_ajax.js, miso-web/src/main/webapp/scripts/lims.js, miso-web/src/main/webapp/scripts/list_library_template.js, miso-web/src/main/webapp/scripts/list_library_template_index.js, miso-web/src/main/webapp/scripts/list_project.js, miso-web/src/main/webapp/scripts/urls.js, sqlstore/src/main/resources/db/migration/V8510__libraryTemplate_volumeUnits.sql
Open to opinions on whether the bulk edit page, and the bulk add/remove project actions should be removed
=> GLT-2959: improved interface for editing library templates

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/spreadsheet/SampleSpreadSheets.java
=> Add BioBank Transfer List

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/spreadsheet/SampleSpreadSheets.java
=> Add Barcode field to Transfer List

RELEASE_NOTES.md, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllSamples.sql
=> Export RIN & DV200 via Pinery

RELEASE_NOTES.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultRunService.java, sqlstore/src/main/resources/db/migration/V8267__unique_run_alias.sql
=> Enforce unique run aliases

RELEASE_NOTES.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Run.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/KitDescriptorService.java, docs/user_manual/type_data.md, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/run/RunDto.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultKitDescriptorService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultRunService.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/service/RunScannerClient.java, miso-web/src/main/webapp/scripts/form_run.js, pinery-miso/pom.xml, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllRuns.sql, pom.xml, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/KitStore.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateKitDao.java, sqlstore/src/main/resources/db/migration/V8527__sequencing_kit.sql
Run Scanner and Pinery dependencies need updated to the next release of each before merging
=> Pinery Sequencing Kits and Container Models

RELEASE_NOTES.md, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllSamples.sql
=> Export intialVolume in Pinery samples

RELEASE_NOTES.md, integration-tools/src/main/java/uk/ac/bbsrc/tgac/miso/integration/visionmate/VisionMateScanner.java, integration-tools/src/test/java/uk/ac/bbsrc/tgac/miso/integration/test/visionmate/VisionMateScanTests.java, integration-tools/src/test/java/uk/ac/bbsrc/tgac/miso/integration/test/visionmate/VisionMateScannerTests.java, pom.xml, sqlstore/src/main/resources/db/migration/V8510__transfers.sql
Requires release of VisionMate Client including https://github.com/miso-lims/visionmate-client/pull/6
=> GLT-3087: change VisionMate scanner to use 'Other' manufacturer

RELEASE_NOTES.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/LibraryAliquot.java
=> Fix library aliquot printer text

RELEASE_NOTES.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/LibraryAliquot.java
=> Don't show library name on library aliquot labels

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/spreadsheet/SampleSpreadSheets.java
=> Add Initial Extraction Yields List

RELEASE_NOTES.md, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-web/src/main/webapp/scripts/hot_sample.js
Hotfixed stage and prod with the JS fix already
=> fixed receipt validation

RELEASE_NOTES.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/DetailedLibraryAliquot.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/DetailedLibraryImpl.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/DetailedSampleImpl.java
=> Add null check for group description

RELEASE_NOTES.md, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/DetailedSampleDto.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkSampleEditIT.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/BulkLibraryPage.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/BulkSamplePage.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java, miso-web/src/main/webapp/scripts/hot_boxable.js, miso-web/src/main/webapp/scripts/hot_library.js, miso-web/src/main/webapp/scripts/hot_sample.js
Also moved subproject column beside project because... it wasn't already there? :man_shrugging:
=> Box Position Sorting

pinery-miso/pom.xml, pinery-miso/src/main/resources/context-example.xml, pinery-miso/src/main/resources/pinery-miso-config.xml, pinery-miso/src/main/resources/pinery-miso.properties
Requires Pinery release containing https://github.com/oicr-gsi/pinery/pull/122
=> GLT-3131: updates for Pinery caching

RELEASE_NOTES.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultProjectService.java, sqlstore/src/main/resources/db/migration/V8280__unique_shortname.sql
=> Project shortname must be unique (or empty)

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/SampleNumberPerProjectService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultProjectService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleNumberPerProjectService.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/SampleNumberPerProjectDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleNumberPerProjectDao.java
Since there's already a release note about fixing errors when deleting things, I'm not adding another for this one.
=> Fix bug deleting projects

RELEASE_NOTES.md, miso-web/src/main/webapp/scripts/hot_library_template_index.js
=> Add 'Sort By Rows/Columns' buttons for library template indices

RELEASE_NOTES.md, pinery-miso/pom.xml, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllSampleProjects.sql
Requires updated Pinery version after Pinery release
=> GLT-3210: expose naming scheme selection on Pinery projects

RELEASE_NOTES.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractSample.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Sample.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SequencingControlType.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/kit/KitDescriptor.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/SequencingControlTypeService.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleDto.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SequencingControlTypeDto.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSequencingControlTypeService.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/ConstantsController.java, miso-web/src/main/webapp/scripts/form.js, miso-web/src/main/webapp/scripts/form_sample.js, pinery-miso/pom.xml, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllSamples.sql, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/SequencingControlTypeDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSequencingControlTypeDao.java, sqlstore/src/main/resources/db/migration/V8525__sequencing_controls.sql, sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_sample.sql
=> GLT-3222: allow marking samples as sequencing controls

RELEASE_NOTES.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/view/PoolableElementView.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/LibraryAliquotDto.java, miso-web/src/main/webapp/scripts/warning_poolelement.js, sqlstore/src/main/resources/db/migration_afterMigrate/05_view_pool.sql
=> GLT-3227: indicate sequencing controls on Edit Pool page

miso-web/src/main/webapp/scripts/bulk.js
There are display issues where the comment box sometimes popped up out of view, so just marking the cells invalid (red) instead
=> improve backend validation display in bulk tables

miso-web/pom.xml, sqlstore/pom.xml
Finally got tired of editing the pom every time I need to run integration tests on my laptop
=> fix running integration tests on Mac

Dockerfile, RELEASE_NOTES.md
Not sure why Tomcat is fine with the mysql driver in the webapp in other installations, but not in Docker
=> fixed Docker webapp build

miso-web/src/main/webapp/scripts/list_library.js
Has caused confusion for two people trying to get started with MISO now
=> added error message when library receipt isn't possible

RELEASE_NOTES.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/PaginationFilter.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/PaginationFilterSink.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/LibraryAliquotRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/LibraryRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleRestController.java, miso-web/src/main/webapp/WEB-INF/pages/editWorkset.jsp, miso-web/src/main/webapp/scripts/list_library.js, miso-web/src/main/webapp/scripts/list_libraryaliquot.js, miso-web/src/main/webapp/scripts/list_samples.js, miso-web/src/main/webapp/scripts/urls.js, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryAliquotDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePaginatedDataSource.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolableElementViewDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDao.java
Getting 'Library Aliquot cannot be filtered by workset.' on Workset 138 despite all the code being the same, don't understand it
=> [GLT-3286] workset search

RELEASE_NOTES.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleTissueProcessingImpl.java, sqlstore/src/main/resources/db/migration/V1060__auto_main.sql, sqlstore/src/main/resources/db/migration/beforeValidate.sql
After this is merged, I'll also release patches for
* v1.9.x (latest official release)
* 1.10.x (current release candidate)
=> [#2325] fixed errors with non-subcategorized tissue processing classes

miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/AbstractPage.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/PoolPage.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/util/TestUtils.java, miso-web/src/it/resources/tomcat-config/miso.it.properties, miso-web/src/it/resources/tomcat-plain-config/miso.it.plain.properties, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/ConstantsController.java
It seems a lot of the flaky tests are due to pages not loading correctly (expected elements not found). Hopefully this will help to narrow down the cause.
=> check for errors on every integration test page load

miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/SamplePage.java, miso-web/src/main/webapp/scripts/form_sample.js
Field no longer exists as received date is now covered by transfers
=> removed old received date field from Edit Sample page

RELEASE_NOTES.md, miso-web/src/main/webapp/scripts/list_qc.js
Setting window location issues GET which isn't compatible
=> [GLT-3319] Fix Add QCs Button

RELEASE_NOTES.md, miso-web/src/main/webapp/scripts/list_targetedSequencing.js
=> Change labels so Add doesn't appear twice

RELEASE_NOTES.md, pinery-miso/pom.xml, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllSamples.sql
Needs Pinery release and updated Pinery version before merging
=> GLT-3349: export index family name via Pinery

RELEASE_NOTES.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/InstrumentModel.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Run.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/run/RunDto.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultRunService.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/RunRestController.java, miso-web/src/main/webapp/scripts/form_run.js, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllRunSamples.sql, sqlstore/src/main/resources/db/migration/V8505__run_index_strategy.sql, sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_run.sql
Added as enum instead of boolean to be consistent with how it is on instrument model
=> GLT-3358: added dataManglingPolicy to runs

RELEASE_NOTES.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Printer.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/PrinterService.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/printing/PrintableField.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/printing/PrintableText.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/printing/PrintableTextDeserializer.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/printing/PrintableTextSerializer.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/printing/TypeAlternate.java, docs/user_manual/barcode_label_printers.md, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/ConstantsController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/PrinterRestController.java, miso-web/src/main/webapp/scripts/labeldesign.js, miso-web/src/main/webapp/scripts/list_printer.js, miso-web/src/main/webapp/scripts/urls.js
=> Allow editing label layouts for printers

RELEASE_NOTES.md, pinery-miso/pom.xml, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllRunPositions.sql, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllRunSamples.sql
Requires Pinery release and version update in `pinery-miso/pom.xml` before merging
=> GLT-3363: updated QC statuses in Pinery-MISO

pinery-miso/src/it/resources/db/migration/pinery-miso_base_test_data.sql, pinery-miso/src/it/resources/db/migration/pinery-miso_detailed_test_data.sql, pinery-miso/src/it/resources/db/migration/pinery-miso_plain_test_data.sql
Not sure how I missed this with the project clinical/pipeline field change
=> fix Pinery-MISO integration test data

RELEASE_NOTES.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Project.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/ProjectImpl.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/exception/ValidationError.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/ProjectDto.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultProjectService.java, miso-web/src/main/webapp/scripts/contact_ajax.js, miso-web/src/main/webapp/scripts/form_project.js, miso-web/src/main/webapp/scripts/list_transfernotification.js, miso-web/src/main/webapp/scripts/parsley_form_validations.js, pinery-miso/pom.xml, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/converters/QcConverter.java, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllRuns.sql, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllSampleProjects.sql, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllSampleQcs.sql, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllSamples.sql, sqlstore/src/main/resources/db/migration/V8501__new_project_fields.sql
~~Requires Pinery release - version 2.16.0 assumed and set here~~
=> GLT-3401 Sampuru Requirements

RELEASE_NOTES.md, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultRunService.java, pom.xml
~~Requires Run Scanner release (assumed v1.13.0)~~
=> GLT-3360: set NovaSeq index sequencing method from Run Scanner

RELEASE_NOTES.md, docs/user_manual/worksets.md, miso-web/src/main/webapp/scripts/hot.js, miso-web/src/main/webapp/scripts/lims.js
This PR is only for the GLT-3437 commit. The other commit is also in #2463, which will be merged first.
=> [GLT-3437] added navigation options after add to workset

RELEASE_NOTES.md, miso-web/src/main/webapp/scripts/form_indexfamily.js, miso-web/src/main/webapp/scripts/form_library.js
The bulk page already works this way
=> [GLT-3492] fix UDI index error when missing matched index

docs/admin/baremetal-installation-guide.md
JDK 11-15 are fine, but I'm just specifying 11 since it's LTS.
=> [#2499] updated JDK and Tomcat requirements in install guide

miso-web/pom.xml, pinery-miso/pom.xml, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java, pom.xml
Instead of dependabot PR that updates the library
=> removed commons IO dependency

.travis.yml, travis_jobs.sh
Apparently the travis CLI does not like white space. 🤷‍♂️ 
I just created an access token for my own Docker account and used that (encrypted via travis CLI)
=> log into Docker to increase pull rate limits

changes/change_menus.md, docs/admin/site-configuration.md, docs/user_manual/freezers_and_rooms.md, docs/user_manual/projects.md, docs/user_manual/type_data.md, docs/user_manual/workstations.md, miso-web/src/main/webapp/WEB-INF/pages/adminsub.jsp, miso-web/src/main/webapp/scripts/lims.js, miso-web/src/main/webapp/styles/style-full.css
I just could not add yet another link to these menus before doing this... 🙈
=> reorganized Misc and Institute Defaults menus

promote_release.sh
:droplet: merge false spring... :snowflake:
=> Change script to work on Ubuntu

changes/add_pinery_requisitions.md, changes/note_pinery_bump.md, pinery-miso/pom.xml, pinery-miso/src/it/java/ca/on/oicr/pinery/lims/miso/AbstractMisoClientIT.java, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/converters/QcConverter.java, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllAssayMetrics.sql, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllAssays.sql, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllRequisitionQcs.sql, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllRequisitionSampleIds.sql, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllRequisitions.sql, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllRunSamples.sql, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllRuns.sql, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllSamples.sql, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryRunIdsBySampleIds.sql
Before merging
* Release Pinery
* Update pinery version in `pinery-miso/pom.xml`
* Add release note
=> [GLT-3583] updated to support latest Pinery additions

RELEASE_NOTES.md, change_label_editor.md, change_samples_list.md, changes/fix_identity_search.md, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDao.java
Problem was setting the same alias twice on the criteria - the same was added to standard aliases.
Also fixed changelog. Change files were in wrong directory
=> [GLT-3598] fixed filter by identity query

changes/change_datareview_columns.md, changes/change_runlibs_heading.md, changes/fix_req_missing_runlibs.md, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/run/RunDto.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/view/RequisitionController.java, miso-web/src/main/webapp/WEB-INF/pages/editRun.jsp, miso-web/src/main/webapp/scripts/form_run.js, miso-web/src/main/webapp/scripts/list.js, miso-web/src/main/webapp/scripts/list_run.js, miso-web/src/main/webapp/scripts/list_runaliquot.js
(sneaked in a couple other related minor improvements too)
=> [GLT-5606] fixed missing run-libraries on the Edit Requisition page

changes/change_pinery_assayTests.md, pinery-miso/pom.xml, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/converters/SampleTypeConverter.java, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllAssayTests.sql
Requires Pinery release and updating `pinery.version` in `pinery-miso/pom.xml` before merging
=> [GLT-3642] added assay tests to Pinery

changes/fix_metric_controls.md, miso-web/src/main/webapp/scripts/assay_ajax.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3645
=> [GLT-3645] fixed missing controls in assay metric list

changes/fix_requisition_propagation.md, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/DetailedSampleDto.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-web/src/main/webapp/scripts/form_sample.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3647
=> [GLT-3647] fixed unintended propagation of requisitionId field

promote_release.sh
Fixes issue where script errored on Ubuntu for no obvious reason.
(no ticket or changefile because it's so minor)
=> Fix promote release script

changes/fix_secure_cookie.md, changes/note_secure_cookie.md, docs/admin/baremetal-installation-guide.md, miso-web/src/main/webapp/WEB-INF/web.xml
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3656
=> [GLT-3656] secured session cookie

changes/fix_noreferrer.md, miso-web/src/main/webapp/WEB-INF/header.jsp, miso-web/src/main/webapp/WEB-INF/pages/editFreezer.jsp, miso-web/src/main/webapp/scripts/form.js, miso-web/src/main/webapp/scripts/list.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3657
=> [GLT-3657] prevent phishing by navigating browser tabs

changes/fix_qctype_correspondingField.md, miso-web/src/main/webapp/scripts/form_qctype.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3655
=> [GLT-3655] fixed QC Type corresponding field display bug

changes/fix_generated_pool_barcodes.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultPoolService.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3654
=> [GLT-3654] fixed auto pool barcodes containing temporary name

changes/fix_empty_requisition.md, miso-web/src/main/webapp/WEB-INF/pages/editRequisition.jsp, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3663
=> [GLT-3663] fixed errors handling empty requisitions

changes/fix_transferitem_changebox.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultTransferService.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3676
=> [GLT-3676] fixed error moving transferitem to different box

changes/change_pineryReqStop.md, changes/note_pineryVersion.md, pinery-miso/pom.xml, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllRequisitions.sql
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3680
Requires Pinery release and updating `pinery.version` in `pinery-miso/pom.xml` before merging
=> [GLT-3686] added 'stopped' field to Pinery requisitions

RELEASE_NOTES.md, changes/fix_parentChildActions.md, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/LibraryAliquotRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/LibraryRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/PoolRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/RelationFinder.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/RestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/RunRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleRestController.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3696
Tested all other controller methods that return HttpEntity and all are working fine
=> [GLT-3696] fixed parent/child bulk actions

changes/fix_jiraLabelSpaces.md, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/service/integration/jira/JiraIssueManager.java
Jira ticket or GitHub issue: https://github.com/miso-lims/miso-lims/issues/2667
=> [#2667] JIRA issue lookup for projects with spaces in shortname

changes/fix_selfUrl.md, miso-web/src/main/webapp/scripts/form_user.js, miso-web/src/main/webapp/scripts/urls.js
Jira ticket or GitHub issue: https://github.com/miso-lims/miso-lims/issues/2666
=> [#2666] Fixed 404 error after changing user password

changes/add_runningSheet.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/spreadsheet/SampleSpreadSheets.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3701
=> [GLT-3701] Added Running Sheet sample download format

changes/change_passwordRequirements.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultUserService.java, miso-service/src/test/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultUserServiceTest.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/UserRestController.java, miso-web/src/main/webapp/scripts/form_user.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3705
=> [GLT-3705] added password length and complexity requirements

changes/fix_arrayRun_samples.md, changes/fix_saveArrayModel.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/ArrayModel.java, miso-web/src/it/resources/db/migration/integration_test_data.sql, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/view/EditArrayRunController.java, miso-web/src/main/webapp/WEB-INF/pages/editArrayRun.jsp, miso-web/src/main/webapp/scripts/array_ajax.js, miso-web/src/main/webapp/scripts/form_arrayrun.js, sqlstore/src/it/resources/db/migration/V9010__test_data.sql, sqlstore/src/main/resources/db/migration/V8501__fix_arraymodel.sql
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3727
=> [GLT-3727] Fixed Array Model/Run Bugs

miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/BoxRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/RestException.java, miso-web/src/main/webapp/WEB-INF/log4j2.miso.properties
=> log full exception chain when box scanning fails

changes/change_xferNotification.md, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/context/NotificationManager.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3746
=> [GLT-3746] added tissue attributes to transfer notifications

changes/fix_aliquotSearch.md, sqlstore/src/main/resources/db/migration_afterMigrate/05_view_barcodable.sql
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3748
=> [GLT-3748] fixed searching by aliquot alias in Search widget

changes/fix_xferEmail_tissueAttrs.md, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/context/NotificationManager.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3756
=> [GLT-3756] fixed tissue attribute display in transfer notifications

RELEASE_NOTES.md, changes/fix_newLdapUser.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultUserService.java, miso-service/src/test/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultUserServiceTest.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3759
=> [GLT-3759] fixed NPE when creating new LDAP user

RELEASE_NOTES.md, changes/fix_exception_when_shortname_is_null.md, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/service/integration/jira/JiraIssueManager.java
Jira ticket or GitHub issue: #2700
=> Fix error loading project page in plain sample mode

changes/change_ad_username.md, changes/note_change_ad_username.md, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/context/MisoLoginFilter.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3774
=> [GLT-3774] remove AD email domain from login name

changes/fix_null_metrics.md, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/dashi/RunLibraryQcTableRequestMetricDto.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/dashi/RunLibraryQcTableRowMetricDto.java, miso-web/src/main/webapp/scripts/runLibraryMetrics_ajax.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3784
=> [GLT-3784] fix display of missing values on Run-Library Metrics page

changes/fix_boxExport.md, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/BoxRestController.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3785
=> [GLT-3785] fixed exporting box spreadsheet

changes/fix_subproject_validation.md, miso-web/src/main/webapp/scripts/bulk_subproject.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3794
=> [GLT-3794] fixed subproject editing/validation bugs

changes/add_projectColumn.md, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/LibraryAliquotDto.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/LibraryDto.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkLibraryAliquotIT.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkLibraryIT.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/PlainSampleITs.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/view/EditLibraryAliquotController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/view/EditLibraryController.java, miso-web/src/main/webapp/scripts/bulk_library.js, miso-web/src/main/webapp/scripts/bulk_libraryaliquot.js, miso-web/src/main/webapp/scripts/list_library.js, miso-web/src/main/webapp/scripts/list_libraryaliquot.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3792
=> [GLT-3792] project columns

changes/change_seqparam_validation.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSequencingParametersService.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3653
=> [GLT-3653] allow saving Illumina seq params with unknown parameters

changes/fix_deleteAliquot_message.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryAliquotService.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/LibraryAliquotStore.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryAliquotDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3781
=> [GLT-3781] check for children when deleting library aliquots

changes/fix_qcAutoUpdate.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultQcTypeService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultQualityControlService.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3782
=> [GLT-3782] fixed QC type auto-update validation

changes/fix_bulk_multiSequenceIndices.md, miso-web/src/main/webapp/scripts/bulk_index.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3755
=> [GLT-3755] fixed multi-sequence indices on bulk edit page

changes/fix_saveTransferStocks.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java
Was throwing `ClassCastException` at these two lines because the sample was a Hibernate proxy object
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3798
=> [GLT-3798] fixed ClassCastExceptions when saving transfer items

changes/add_singleSample_viewMetrics.md, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/DetailedSampleDto.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-web/src/main/webapp/scripts/assay_ajax.js, miso-web/src/main/webapp/scripts/form_sample.js, miso-web/src/main/webapp/scripts/list_assaymetric.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3799
=> [GLT-3799] show assay and metrics on Edit Sample page

changes/add_singleSample_viewMetrics.md, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/LibraryAliquotDto.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/LibraryDto.java, miso-web/src/main/webapp/scripts/form.js, miso-web/src/main/webapp/scripts/form_library.js, miso-web/src/main/webapp/scripts/form_libraryaliquot.js, miso-web/src/main/webapp/scripts/form_sample.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3801
=> [GLT-3801] show assay and metrics on Edit Library and Aliquot pages

changes/add_bulk_assay.md, changes/add_bulk_viewMetrics.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/LimsUtils.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkSampleEditIT.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/PlainSampleITs.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/view/EditSampleController.java, miso-web/src/main/webapp/scripts/bulk_sample.js, miso-web/src/main/webapp/styles/style-full.css
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3800
=> [GLT-3800] show assay and metrics on bulk sample pages

changes/add_bulk_assay.md, changes/add_bulk_viewMetrics.md, changes/add_singleSample_viewMetrics.md, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkLibraryAliquotIT.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkLibraryIT.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/PlainSampleITs.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/view/EditLibraryAliquotController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/view/EditLibraryController.java, miso-web/src/main/webapp/scripts/assay_ajax.js, miso-web/src/main/webapp/scripts/bulk.js, miso-web/src/main/webapp/scripts/bulk_library.js, miso-web/src/main/webapp/scripts/bulk_libraryaliquot.js, miso-web/src/main/webapp/scripts/bulk_sample.js, miso-web/src/main/webapp/scripts/form_libraryaliquot.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3802
=> [GLT-3802] show assay and metrics on bulk library and aliquot pages

changes/fix_symbols.md, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/context/WebConfig.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3813
=> [GLT-3813] fix displaying symbol characters

pom.xml
=> updated to VisionMate Client v1.0.3

changes/fix_bulkTables.md, changes/fix_bulk_containerModels.md, changes/fix_bulk_librarySelection.md, changes/fix_bulk_librarySpikeIns.md, changes/fix_bulk_libraryStrategy.md, changes/fix_bulk_libraryTypes.md, changes/fix_bulk_librarydesign.md, changes/fix_bulk_librarydesigncode.md, changes/fix_bulk_partitionQcTypes.md, changes/fix_bulk_runPurposes.md, changes/fix_bulk_seqParams.md
=> condensed bulk table changes into one entry

changes/add_trackingSheet_conc.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/spreadsheet/SampleSpreadSheets.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3829
=> [GLT-3829] added concentration to sample tracking sheets

.github/workflows/miso_web_bulk_it.yml, .github/workflows/miso_web_other_it.yml, .github/workflows/miso_web_plain_it.yml, .github/workflows/pinery_miso_it.yml, .github/workflows/sqlstore_it.yml, .github/workflows/unit_tests.yml, Dockerfile, changes/change_java17.md, changes/note_java17.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/spreadsheet/SampleSpreadSheets.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/type/LibrarySelectionType.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/type/LibraryStrategyType.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/type/LibraryType.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/AlphanumericComparator.java, docs/admin/baremetal-installation-guide.md, miso-service/src/test/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultExperimentServiceTest.java, miso-service/src/test/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleServiceTest.java, miso-web/pom.xml, miso-web/src/it/resources/tomcat-config/ROOT.xml, miso-web/src/it/resources/tomcat-plain-config/ROOT.xml, miso-web/src/main/webapp/WEB-INF/jdbc-security-config.xml, pom.xml, sqlstore/pom.xml, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateChangeLogDaoIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRunDaoIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRunPartitionAliquotDaoIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSequencerPartitionContainerDaoIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateServiceRecordDaoIT.java
This updates to Java 17 and the latest versions of Spring 5. Will update to Spring 6 in a separate PR
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3825
=> [GLT-3825] updated to Java 17

.mkdocs.yml, docs/user_manual/qc_integration.md
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3809
=> [GLT-3809] updated Run-Library Metrics page documentation

changes/add_freezer_probeID_col.md, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/AbstractListPage.java, miso-web/src/main/webapp/scripts/list_storage_location.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3833
- [add_freezer_probeID_col.md] Includes a change file
=> added probe ID column on Freezer page

changes/fix_orphaned_runlib.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/RunPartitionAliquotService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultContainerService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultRunPartitionAliquotService.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRunPartitionAliquotDaoIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSiblingNumberGeneratorIT.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/RunPartitionAliquotDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRunPartitionAliquotDao.java, sqlstore/src/main/resources/db/migration/V8501__delete_orphaned_runlibs.sql
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3848
=> [GLT-3848] fix deleting run-library link when removing pool

changes/fix_qc_sort.md, miso-web/src/main/webapp/scripts/bulk_qc.js
Jira ticket or GitHub issue: https://github.com/miso-lims/miso-lims/issues/2753
=> [#2753] fixed sorting bulk QC table

changes/note_pinery.md, pinery-miso/pom.xml
Jira ticket or GitHub issue: N/A
=> Update to Pinery 2.25.0

changes/change_assayTest_tissueTypeOptional.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultAssayTestService.java, miso-web/src/main/webapp/scripts/bulk_assaytest.js, miso-web/src/main/webapp/scripts/list_assaytest.js, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3866
=> [GLT-3866] made assay test tissue type optional

changes/change_assayMetric_showUnits.md, changes/fix_createAssay_addTest.md, miso-web/src/main/webapp/scripts/list_assaymetric.js, miso-web/src/main/webapp/scripts/list_assaytest.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3868
=> Glt 3868 assay improvements

changes/add_assayCopy.md, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/view/AssayController.java, miso-web/src/main/webapp/scripts/list_assay.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3869
=> [GLT-3869] allow copying assays

changes/add_requisition_stopReason.md, changes/note_pinery.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/Requisition.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/RequisitionDto.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultRequisitionService.java, miso-web/src/main/webapp/scripts/form_requisition.js, pinery-miso/pom.xml, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllRequisitions.sql, sqlstore/src/main/resources/db/migration/V8501__requisition_stop_reason.sql, sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_requisition.sql
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3863
PR is ready for review. Marked as draft because a Pinery release and version bump is required before merging
=> [GLT-3863] added requisition stop reason field

.vscode/launch.json, changes/fix_project_users.md, sqlstore/src/main/resources/db/migration/V8501__project_fk_constraints.sql
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3886
Also added debug config. VSCode generated the comments in the JSON and is fine with them
=> [GLT-3886] added missing Project foreign key constraints

changes/fix_ldi_alias.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryAliquotService.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/view/EditLibraryAliquotController.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3890
=> [GLT-3890] fixed library aliquot alias generation and validation

changes/fix_moveToWorkset.md, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/WorksetRestController.java, miso-web/src/main/webapp/scripts/bulk.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3892
=> [GLT-3892] fixed errors moving samples between worksets

docs/user_manual/requisitions.md
=> correction to requisition docs

changes/fix_probeId_validation.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultStorageLocationService.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateStorageLocationDaoIT.java, sqlstore/src/it/resources/db/migration/V9010__test_data.sql, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/StorageLocationStore.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateStorageLocationDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3895
=> [GLT-3895] improved freezer probe ID validation

changes/Change_qc_in_MISO.md, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/view/RunLibraryController.java, miso-web/src/main/webapp/scripts/runLibraryMetrics_ajax.js, miso-web/src/main/webapp/styles/style.css
Jira ticket or GitHub issue: GLT-3841
=> [GLT-3841] QC in MISO with different assays/designs together

changes/fix_groupDeletion_validate.md, changes/fix_userPage_deleteGroup.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultGroupService.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/view/EditSampleController.java, miso-web/src/main/webapp/scripts/list_group.js, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/SecurityStore.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSecurityDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3901
=> [GLT-3901] Fixes for deleting groups

changes/fix_GLT-3920.md, miso-web/src/main/webapp/scripts/list_assaytest.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3920
✅ Includes a change file
=> #GLT-3920: bug where add button showed on view-only mode.

changes/change_hasUmis_default.md, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/LibraryDto.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkLibraryIT.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/PlainSampleITs.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/view/EditLibraryController.java, miso-web/src/main/webapp/scripts/bulk_library.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3906
=> [GLT-3906] removed library hasUmis default value

docs/admin/baremetal-installation-guide.md, docs/admin/mysql-8-upgrade.md
=> install guide fixups

changes/fix_duplicateUser_message.md, changes/fix_newUser_autocomplete.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultUserService.java, miso-web/src/main/webapp/scripts/form.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3925
=> [GLT-3925] Create User page improvements

docs/admin/baremetal-installation-guide.md, docs/admin/mysql-8-upgrade.md
=> document using non-root user for database admin

.docker/run-flyway, .docker/tomcat/ROOT.xml, RELEASE_NOTES.md, changes/fix_timezone_caching.md, docs/admin/baremetal-installation-guide.md, docs/admin/mysql-8-upgrade.md, pinery-miso/pom.xml, sqlstore/pom.xml
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3929
=> update docs, tests, and Docker images to disable timezone caching

changes/fix_boxFreezer_log.md, sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_box.sql, sqlstore/src/main/resources/db/migration_beforeMigrate/05_functions.sql
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3930
=> [GLT-3930] log box freezer changes

changes/add_transfer_subprojectSearch.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/view/transfer/ListTransferViewSampleParent.java, miso-web/src/main/webapp/scripts/list.js, miso-web/src/main/webapp/scripts/list_transfer.js, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateListTransferViewDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3924
=> [GLT-3924] allow searching transfers by subproject

changes/fix_bulkSort.md, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkLibraryIT.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkSamplePropagateIT.java, miso-web/src/main/webapp/scripts/bulk.js, miso-web/src/main/webapp/scripts/bulk_library.js, miso-web/src/main/webapp/scripts/bulk_libraryaliquot.js, miso-web/src/main/webapp/scripts/bulk_sample.js
Jira ticket or GitHub issue: https://github.com/miso-lims/miso-lims/issues/2792
=> [#2792] fixed default sorting on bulk pages

changes/fix_assay_duplicate_items.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultAssayService.java, miso-web/src/main/webapp/scripts/assay_ajax.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3931
=> [GLT-3931] validate against duplicate tests and metrics in assay

changes/change_aliquotTrackingSheet.md, changes/fix_detailedSampleFields.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/spreadsheet/LibraryAliquotSpreadSheets.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/spreadsheet/LibrarySpreadSheets.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/spreadsheet/SampleSpreadSheets.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3942
=> Glt 3942 tracking list group

changes/fix_closeDialog.md, miso-web/src/main/webapp/scripts/lims.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3838
=> [GLT-3838] fixed dialogs missing close button

changes/fix_pinery_qcattributes.md, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/converters/QcConverter.java, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllSampleQcs.sql
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3955
=> [GLT-3955] fixed Pinery including multiple values for one QC attribute

changes/add_assaytest_permittedSamples.md, changes/fix_assaytest_buttons.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/AssayTest.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/AssayTestDto.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultAssayTestService.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/AbstractListPage.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/ConstantsController.java, miso-web/src/main/webapp/scripts/bulk_assaytest.js, miso-web/src/main/webapp/scripts/list_assaytest.js, pinery-miso/pom.xml, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllAssayTests.sql, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateAssayTestDaoIT.java, sqlstore/src/main/resources/db/migration/V8501__test_prohibit_supplemental.sql
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3958
Ready for review, but requires a Pinery release and updated version in pinery-miso/pom.xml before merging
=> [GLT-3958] added assay test permitted samples field

changes/fix_sampleClass_stackOverflow.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleClassService.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3977
=> [GLT-3977] fixed possible infinite loop in sample class validation

core/pom.xml, docs/developers-manual.md, pom.xml, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateDetailedQcStatusDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLabDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryTemplateDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateMetricDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePipelineDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateProjectDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateProviderDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateReferenceGenomeDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRunPurposeDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleClassDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSamplePurposeDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSaveDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSequencingOrderDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSubprojectDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateTissueMaterialDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateTissueOriginDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateTissueTypeDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3981
=> [GLT-3981] updated abstract Hibernate DAO classes to JPA Criteria API

changes/add_pinery_qcNotes.md, pinery-miso/pom.xml, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllRunSamples.sql, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllSamples.sql
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3977
Requires Pinery release and version bump before merging
=> [GLT-3975] export QC notes via Pinery

changes/add_GLT-3529.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/PaginationFilter.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/PaginationFilterSink.java, docs/user_manual/workstations.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultWorkstationService.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/InstrumentRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/LibraryRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/WorkstationRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/view/EditInstrumentController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/view/WorkstationController.java, miso-web/src/main/webapp/WEB-INF/footer.jsp, miso-web/src/main/webapp/WEB-INF/pages/editInstrument.jsp, miso-web/src/main/webapp/WEB-INF/pages/editWorkset.jsp, miso-web/src/main/webapp/WEB-INF/pages/editWorkstation.jsp, miso-web/src/main/webapp/scripts/form_workstation.js, miso-web/src/main/webapp/scripts/list_instrument.js, miso-web/src/main/webapp/scripts/list_library.js, miso-web/src/main/webapp/scripts/list_workstation.js, miso-web/src/main/webapp/scripts/urls.js, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/WorkstationDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateInstrumentDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePaginatedDataSource.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateWorkstationDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3529
- ☑️ Includes a change file
=> [GLT-3529] Added individual workstation pages

changes/add_GLT-3650.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/workset/Workset.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/WorksetService.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/WorksetDto.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultWorksetService.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/NoteRestController.java, miso-web/src/main/webapp/WEB-INF/pages/editRun.jsp, miso-web/src/main/webapp/WEB-INF/pages/editWorkset.jsp, sqlstore/src/main/resources/db/migration/V8229__add_Workset_Notes.sql
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3650
- ✅ Includes a change file
=> [GLT-3650] added notes field to Worksets

changes/fix_GLT-3989.md, pom.xml
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3989
=> [GLT-3989] webdrivermanager version change

miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/component/AdvancedSearchParser.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/HibernatePaginatedDataSourceIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/PaginationFilterSinkIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateInstrumentDaoSearchIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateInstrumentModelDaoSearchIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateKitDaoSearchIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryAliquotDaoSearchIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryDaoSearchIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryTemplateDaoSearchIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateListLibraryAliquotViewDaoSearchIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateListPoolViewDaoSearchIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateListWorksetViewDaoSearchIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolDaoSearchIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolOrderDaoSearchIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRequisitionDaoSearchIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRunDaoSearchIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDaoSearchIT.java, sqlstore/src/it/resources/db/migration/V9010__test_data.sql, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateKitDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/JpaCriteriaPaginatedDataSource.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/LongQueryBuilder.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/QueryBuilder.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/util/DbUtils.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3984
=> [GLT-3984] updated HibernateKitDao to use JPA Criteria API

changes/change_analysis_review.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/type/MetricCategory.java, docs/user_manual/type_data.md, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateMetricDaoIT.java, sqlstore/src/main/resources/db/migration/V8501__analysis_review_rename.sql
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3995
=> [GLT-3995] renamed Analysis Review metric category

changes/fix_transferSearch.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/view/transfer/ListTransferView.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateListTransferViewDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3997
=> [GLT-3997] fixed transfer advanced search terms

changes/fix_deleteRun.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultRunService.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3998
=> [GLT-3998] fixed error deleting runs

changes/change_pineryBatchIds.md, pinery-miso/pom.xml
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3974
=> [GLT-3974] updated Pinery to add batch IDs to sample provenance

changes/fix_jiraError.md, miso-web/src/main/webapp/WEB-INF/pages/editRun.jsp
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4007
Already working correctly on the Edit Project page
=> [GLT-4007] fixed displaying JIRA error message

docs/user_manual/requisitions.md, docs/user_manual/type_data.md, miso-web/src/main/webapp/scripts/bulk_assaytest.js, miso-web/src/main/webapp/scripts/list_assaytest.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3996
=> [GLT-3996] added documentation for assay tests

changes/add_tatTargets.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/Assay.java, docs/user_manual/requisitions.md, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/AssayDto.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultAssayService.java, miso-web/src/main/webapp/scripts/form_assay.js, sqlstore/src/main/resources/db/migration/V8501__tat_targets.sql
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4010
=> [GLT-4010] added assay turn-around time target fields

miso-web/src/main/webapp/scripts/form_assay.js
=> specify units for assay turn-around time targets

changes/add_pineryTatTargets.md, pinery-miso/pom.xml, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllAssays.sql
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4011
Requires Pinery release and version bump before merging
=> [GLT-4011] added turn-around time targets to Pinery

changes/add_rebSearch.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/DateType.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/PaginationFilter.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/PaginationFilterSink.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/component/AdvancedSearchParser.java, miso-web/src/main/webapp/scripts/list.js, miso-web/src/main/webapp/scripts/list_project.js, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/PaginationFilterSinkIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateProjectDaoSearchIT.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePaginatedDataSource.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateProjectDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/JpaCriteriaPaginatedDataSource.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4020
=> [GLT-4020] added project search by REB number and expiry

changes/fix_sortRequisitionsByEntered.md, miso-web/src/main/webapp/scripts/list_requisition.js, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRequisitionDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4026
=> [GLT-4026] fixed sorting requisitions by entered date

changes/fix_attachReload.md, miso-web/src/main/webapp/scripts/bulk.js, miso-web/src/main/webapp/scripts/list_attachment.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4030
=> [GLT-4030] fixed bulk pages reloading after attaching files

changes/add_pinery_requisitionPauses.md, pinery-miso/pom.xml, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllRequisitionPauses.sql
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4014
Requires Pinery release before merging
=> [GLT-4014] added requisition pauses to Pinery

changes/change_totalTatTarget.md, changes/fix_tatTarget_validation.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultAssayService.java, miso-web/src/main/webapp/scripts/form_assay.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4039
=> [GLT-4039] adjusted turn-around time target validation

RELEASE_NOTES.md, changes/fix_attachFiles.md, miso-web/src/main/webapp/scripts/bulk.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4043
=> [GLT-4043] fixed error attaching to items in multiple projects

changes/change_deliverables_multi.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Project.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/Assay.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/Deliverable.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/ProjectImpl.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/LimsUtils.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/ProjectDto.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultProjectService.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/view/EditProjectController.java, miso-web/src/main/webapp/WEB-INF/pages/editProject.jsp, miso-web/src/main/webapp/scripts/bulk_deliverable.js, miso-web/src/main/webapp/scripts/form_project.js, miso-web/src/main/webapp/scripts/list_deliverable.js, miso-web/src/main/webapp/scripts/project_ajax.js, sqlstore/src/it/resources/db/migration/V9010__test_data.sql, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateDeliverableDao.java, sqlstore/src/main/resources/db/migration/V8501__multiple_deliverables.sql
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3999
=> [GLT-3999] allow adding multiple deliverables to a project

changes/add_pinery_deliverables.md, pinery-miso/pom.xml, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllProjectDeliverables.sql
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4048
Pinery release required - `pinery.version` in `pinery-miso/pom.xml` will be updated before merging
=> [GLT-4048] added Pinery sample project deliverables

changes/fix_requisition_add_error.md, miso-web/src/main/webapp/scripts/lims.js, miso-web/src/main/webapp/scripts/list_samples.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4058
=> [GLT-4058] display clear error when failing to add samples to a req

changes/change_assayTest_noLibQual.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/AssayTest.java, miso-web/src/main/webapp/scripts/bulk_assaytest.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4064
=> [GLT-4064] added None option for assay test library qualification

changes/add_designSearch.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/PaginationFilter.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/PaginationFilterSink.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/component/AdvancedSearchParser.java, miso-web/src/main/webapp/scripts/list.js, miso-web/src/main/webapp/scripts/list_library.js, miso-web/src/main/webapp/scripts/list_libraryaliquot.js, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/PaginationFilterSinkIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryAliquotDaoSearchIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryDaoSearchIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateListLibraryAliquotViewDaoSearchIT.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryAliquotDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateListLibraryAliquotViewDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePaginatedDataSource.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/JpaCriteriaPaginatedDataSource.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4076
=> [GLT-4076] search libraries and aliquots by design code

changes/fix_createTransfer.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4080
=> [GLT-4080] fixed ClassCastException adding samples to transfers

changes/fix_externalName_apostrophe.md, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/DetailedLibraryDto.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/view/EditLibraryController.java, miso-web/src/main/webapp/WEB-INF/pages/editLibrary.jsp
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4079
=> [GLT-4079] fixed Library page error with certain characters in external name

pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllSamples.sql
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4063
=> added missing requisition ID attribute to libraries in Pinery

changes/add_sampleProject.md, changes/remove_projectItem_project.md, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java, miso-web/src/main/webapp/scripts/list.js, miso-web/src/main/webapp/scripts/list_library.js, miso-web/src/main/webapp/scripts/list_libraryaliquot.js, miso-web/src/main/webapp/scripts/list_samples.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4086
=> [GLT-4086] added project column to sample lists

changes/change_projectDeliverables_log.md, sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_project.sql
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4090
=> [GLT-4090]: changelog project deliverables

changes/fix_attachRefresh.md, miso-web/src/main/webapp/scripts/list_attachment.js
Jira ticket or GitHub issue: https://github.com/miso-lims/miso-lims/issues/2854
=> [#2854] fix refresh after attaching files

changes/fix_advancedSearch_colon.md, changes/fix_searchWidgets_specialChars.md, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/component/AdvancedSearchParser.java, miso-web/src/main/webapp/scripts/pane.js, miso-web/src/test/java/uk/ac/bbsrc/tgac/miso/webapp/controller/component/AdvancedSearchParserTest.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4091
=> Fixed search issues involving special characters

changes/fix_moveToReq.md, miso-web/src/main/webapp/scripts/list.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4092
=> [GLT-4092] fixed 'Move to Req.' action errors

.vscode/settings.json, changes/add_supplementalWizard.md, changes/fix_requisitionExclusions.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/LibraryService.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/SampleService.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/LimsUtils.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/LibraryRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/view/EditLibraryAliquotController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/view/EditLibraryController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/view/EditSampleController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/view/RequisitionController.java, miso-web/src/main/webapp/WEB-INF/pages/editRequisition.jsp, miso-web/src/main/webapp/scripts/list_library.js, miso-web/src/main/webapp/scripts/list_samples.js, miso-web/src/main/webapp/scripts/urls.js, pom.xml, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryDaoIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDaoIT.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/LibraryStore.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/SampleStore.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4102
=> [GLT-4102] added supplemental sample and library wizards

changes/change_requisitionCollapse.md, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/util/form/AttachmentsTag.java, miso-web/src/main/webapp/WEB-INF/miso-form.tld, miso-web/src/main/webapp/WEB-INF/pages/editRequisition.jsp, miso-web/src/main/webapp/scripts/lims.js, miso-web/src/main/webapp/scripts/list.js, miso-web/src/main/webapp/scripts/list_attachment.js, miso-web/src/main/webapp/scripts/list_library.js, miso-web/src/main/webapp/scripts/list_samples.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4107
=> [GLT-4107] collapse tables on Edit Requisition page

changes/change_libQualDesign.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultAssayTestService.java, miso-web/src/main/webapp/scripts/bulk_assaytest.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4113
=> [GLT-4113] allow library qualification design for low-depth sequencing

changes/change_pineryversion.md, pinery-miso/pom.xml
Jira ticket or GitHub issue:
- [ x] Includes a change file
=> Update pinery version to 2.33.0

changes/add_analysisReviewRequired.md, changes/add_analysisReviewRequired_pinery.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/Deliverable.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/DeliverableDto.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultDeliverableService.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/AbstractListPage.java, miso-web/src/main/webapp/scripts/bulk_deliverable.js, miso-web/src/main/webapp/scripts/list_deliverable.js, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllProjectDeliverables.sql, sqlstore/src/main/resources/db/migration/V8501__skip_analysis_review.sql
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4120
Ready for review, but requires Pinery release and dependency update before merging
=> [GLT-4120] add deliverable analysisReviewRequired field

changes/fix_containerModel_validation.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSequencingContainerModelService.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4122
=> [GLT-4122] fixed usage check in container model validation

changes/fix_supplementalLibWizard.md, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/LibraryRestController.java, miso-web/src/main/webapp/scripts/list_library.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4127
=> [GLT-4127] fixed supplemental library wizard filtering

changes/add_bulkAttachPool.md, miso-web/src/main/webapp/scripts/bulk_pool.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3679
=> [GLT-3679] bulk attach files to pools

RELEASE_NOTES.md, changes/fix_db_recursion.sql, sqlstore/src/main/resources/db/migration_beforeMigrate/00_config.sql
=> fixed setting MySQL variable at global AND session level

miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultArrayService.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateArrayDaoIT.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/ArrayStore.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateArrayDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/QueryBuilder.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4138
=> [GLT-4138] update HibernateArrayDao to JPA Criteria

changes/fix_moveToReq_changelog.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java, sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_library.sql, sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_sample.sql
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4147
=> [GLT-4147] fixed Move to Requisition changelogging

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateArrayModelDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4139
=> [GLT-4239] Update HibernateArrayModelDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateAssayDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4141
=> [GLT-4141] Update HibernateAssayDao to JPA Criteria

changes/fix_sortByProject.md, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryDaoSearchIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateListLibraryAliquotViewDaoSearchIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDaoSearchIT.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateListLibraryAliquotViewDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4149
=> [GLT-4149] Sorting Workset Items by Project Fails

miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultArrayRunService.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateArrayRunDaoIT.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/ArrayRunStore.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateArrayRunDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4140
=> [GLT-4140] Update HibernateArrayRunDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateAssayTestDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4142
=> [GLT-4142] Update HibernateAssayTestDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateAttachmentCategoryDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4151
=> [GLT-4151] Update HibernateAttachmentCategoryDao to JPA Criteria

changes/fix_moveToStoppedReq.md, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/RequisitionRestController.java, miso-web/src/main/webapp/scripts/list.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4155
=> [GLT-4155] added stop reason to Move to Req. dialog

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateContactDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4153
=> [GLT-4153] Update HibernateContactDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateDetailedQcStatusDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4154
=> [GLT-4154] Update HibernateDetailedQcStatusDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateIndexFamilyDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4158
=> [GLT-4158] Update HibernateIndexFamilyDao to JPA Criteria

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/ExperimentService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultExperimentService.java, miso-service/src/test/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultExperimentServiceTest.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateExperimentDaoIT.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/ExperimentStore.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateExperimentDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4156
=> [GLT-4156] Update HibernateExperimentDao to JPA Criteria

sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateIndexDaoIT.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateIndexDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4157
=> [GLT-4157] Update HibernateIndexDao to JPA Criteria

sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateInstrumentModelDaoSearchIT.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateInstrumentModelDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4161
=> [GLT-4161] Update HibernateInstrumentModelDao to JPA Criteria

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/qc/QcTarget.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultInstrumentService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultQcTypeService.java, pinery-miso/pom.xml, pom.xml, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateInstrumentDaoIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateInstrumentDaoSearchIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateQcTypeDaoIT.java, sqlstore/src/it/resources/db/migration/V9010__test_data.sql, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/InstrumentStore.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateInstrumentDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateQcTypeDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/JpaCriteriaPaginatedDataSource.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4159
=> [GLT-4159] Update HibernateInstrumentDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateInstrumentStatusDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4162
=> [GLT-4162] Update HibernateInstrumentStatusDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryDesignDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4164
=> [GLT-4164] Update Hibernate LibraryDesignDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibrarySelectionDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4165
=> [GLT-4165]Update HibernateLibrarySelectionDao to JPA Criteria

sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryTemplateDaoSearchIT.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryTemplateDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4166
=> [GLT-4166] Update HibernateLibraryTemplateDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryTypeDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4167
=> [GLT-4167] Update HibernateLibraryTypeDao to JPA Criteria

changes/fix_pauseResumeSave.md, miso-web/src/main/webapp/scripts/form.js, miso-web/src/main/webapp/scripts/list.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4174
=> [GLT-4174] fixed list actions operating on temporary ID objects

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateListContainerViewDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4168
=> [GLT-4168] Update HibernateListContainerViewDao to JPA Criteria

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/PaginatedDataSource.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryAliquotService.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryAliquotDaoIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryAliquotDaoSearchIT.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/LibraryAliquotStore.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryAliquotDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/JpaCriteriaPaginatedBoxableSource.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/QueryBuilder.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4163
=> [GLT-4163] Update HibernateLibraryAliquotDao to JPA Criteria

changes/change_boxableChangelog.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/changelog/LibraryAliquotChangeLog.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/changelog/LibraryChangeLog.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/changelog/PoolChangeLog.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/changelog/SampleChangeLog.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/view/box/BoxableView.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/view/box/LibraryAliquotBoxableView.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/view/box/LibraryBoxableView.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/view/box/PoolBoxableView.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/view/box/SampleBoxableView.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultBoxService.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3591
=> [GLT-3591] log boxable location changes on the boxable

sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateListPoolViewDaoSearchIT.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateListPoolViewDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/JpaCriteriaPaginatedDataSource.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/QueryBuilder.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4171
=> [GLT-4171] Update HibernateListPoolViewDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateListTransferViewDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4172
=> [GLT-4172] Update HibernateListTransferViewDao to JPA Criteria

sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateListWorksetViewDaoSearchIT.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateListWorksetViewDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4173
=> [GLT-4173] Update HibernateListWorksetViewDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateMetricDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4175
=> [GLT-4175] Update Hibernate MetricDao to JPA Criteria

changes/add_pineryReqCreated.md, pinery-miso/pom.xml, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllRequisitions.sql
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GR-1526
Ready for review, but requires a Pinery release and version bump before merging
=> [GR-1526] added requisition created date to Pinery

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePipelineDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4178
=> [GLT-4178] Update HibernatePipelineDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePartitionQcTypeDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateProviderDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4177
=> [GLT-4177] Update HibernatePartitionQcTypeDao to JPA Criteria

sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolOrderDaoSearchIT.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolOrderDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4180
=> [GLT-4180] Update HibernatePoolOrderDao to JPA Criteria

miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultPrinterService.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePrintServiceDaoIT.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/PrinterStore.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePrinterDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4181
=> [GLT-4181] Update HibernatePrinterDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateProjectDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4183
=> [GLT-4183] Update HibernateProjectDao to JPA Criteria

miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultPoolService.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolDaoIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolDaoSearchIT.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/PoolStore.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryAliquotDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/JpaCriteriaPaginatedBoxableSource.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4179
=> [GLT-4179] Update HibernatePoolDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateProgressDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4182
=> [GLT-4182] Update HibernateProgressDao to JPA Criteria

sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateListLibraryAliquotViewDaoSearchIT.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateListLibraryAliquotViewDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/QueryBuilder.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4170
=> [GLT-4170] Update HibernateListLibraryAliquotViewDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateQcNodeDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4184
=> [GLT-4184] Update HibernateQcNodeDao to JPA Criteria

sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRequisitionDaoSearchIT.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRequisitionDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4187
=> [GLT-4187] Update HibernateRequisitionDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateContainerQcDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryQcDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolQCDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateQcStore.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRequisitionQcDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleQcDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4185
=> [GLT-4185] Update HibernateQcStore to JPA Criteria

miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleNumberPerProjectService.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleNumberPerProjectDaoIT.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/SampleNumberPerProjectDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleNumberPerProjectDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4197
=> [GLT-4197] Update HibernateSampleNumberPerProjectDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSamplePurposeDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4198
=> [GLT-4198] Update HibernateSamplePurposeDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleTypeDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4199
=> [GLT-4199] Update HibernateSampleTypeDao to JPA Criteria

miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultRunService.java, miso-service/src/test/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultRunServiceTest.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRunDaoIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRunDaoSearchIT.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/RunStore.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRunDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/QueryBuilder.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4188
=> [GLT-4188] Update HibernateRunDao to JPA Criteria

docs/admin/compose-installation-guide.md
Jira ticket or GitHub issue: https://github.com/miso-lims/miso-lims/issues/2923
=> clarify demo instructions

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/QualityControlTypeStore.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateQcTypeDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4186
=> [GLT-4186] Update HibernateQcTypeDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/SampleValidRelationshipDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleValidRelationshipDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4200
=> [GLT-4200] Update HibernateSampleValidRelationshipDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSecurityDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4201
=> [GLT-4201] Update HibernateSecurityDao to JPA Criteria

miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultContainerService.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSequencerPartitionContainerDaoIT.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/SequencerPartitionContainerStore.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSequencerPartitionContainerDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4202
=> [GLT-4202] Update HibernateSequencerPartitionContainerDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/SequencingContainerModelStore.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSequencingContainerModelDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4203
=> [GLT-4203] Update HibernateSequencingContainerModelDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSequencingOrderDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4204
=> [GLT-4204] Update HibernateSequencingOrderDao to JPA Criteria

miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryAliquotService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryService.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryDaoIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryDaoSearchIT.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/LibraryStore.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/QueryBuilder.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4217
=> [GLT-4217] Update HibernateLibraryDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSequencingParametersDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4206
=> [GLT-4206] Update HibernateSequencingParametersDao to JPA Criteria

miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultServiceRecordService.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateServiceRecordDaoIT.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/ServiceRecordStore.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateServiceRecordDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4207
=> [GLT-4207] Update HibernateServiceRecordDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSiblingNumberGenerator.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4208
=> [GLT-4208] Update HibernateSiblingNumberGenerator to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSopDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4209
=> [GLT-4209] Update HibernateSopDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateStainCategoryDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4210
=> [GLT-4210] Update HibernateStainCategoryDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateStainDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4211
=> [GLT-4211] Update HibernateStainDao to JPA Criteria

miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultStorageLocationService.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateStorageLocationDaoIT.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/StorageLocationStore.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateStorageLocationDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4212
=> [GLT-4212] Update HibernateStorageLocationDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/StorageLocationMapDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateStorageLocationMapDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4213
=> [GLT-4213] Update HibernateStorageLocationMapDao to JPA Criteria

miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultStudyService.java, miso-service/src/test/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultStudyServiceTest.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateStudyDaoIT.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/StudyStore.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateStudyDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4214
=> [GLT-4214] Update HibernateStudyDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSubprojectDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4215
=> [GLT-4215] Update HibernateSubprojectDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateTargetedSequencingDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4216
=> [GLT-4216] Update HibernateTargetedSequencingDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateTransferNotificationDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4220
=> [GLT-4220] Update HibernateTransferNotificationDao to JPA Criteria

miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultWorksetService.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateWorksetDaoIT.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/WorksetStore.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateWorksetDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4221
=> [GLT-4221] Update HibernateWorksetDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRunPartitionAliquotDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4189
=> [GLT-4189] Update HibernateRunPartitionAliquotDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateTransferDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4219
=> [GLT-4219] Update HibernateTransferDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateDeletionDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4242
=> [GLT-4242] Update HibernateDeletionDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateArrayDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateArrayRunDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateBoxDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateDeletionDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateIndexDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateInstrumentDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryAliquotDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateListContainerViewDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateListLibraryAliquotViewDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateListPoolViewDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateListTransferViewDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateListWorksetViewDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolOrderDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePrinterDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRequisitionDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRunDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSequencingOrderSummaryViewDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSopDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateStudyDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateTargetedSequencingDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/JpaCriteriaPaginatedDataSource.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4205
=> Update HibernateSequencingOrderSummaryViewDao to JPA Criteria

sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateArrayDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateArrayRunDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateBoxDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateDeletionDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateIndexDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateInstrumentDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateInstrumentModelDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateKitDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryAliquotDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryStrategyDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryTemplateDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateListContainerViewDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateListLibraryAliquotViewDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateListPoolViewDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateListTransferViewDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateListWorksetViewDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolOrderDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePrinterDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateProjectDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRequisitionDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRunDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSopDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateStudyDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSubmissionDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateTargetedSequencingDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/JpaCriteriaPaginatedBoxableSource.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/JpaCriteriaPaginatedDataSource.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4239
=> Refactor getSearchProperties in JpaCriteriaPaginatedDataSource

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/DetailedSampleImpl.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java, miso-service/src/test/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleServiceTest.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDaoIT.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDaoSearchIT.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/SampleStore.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateIndexDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateInstrumentModelDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateKitDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryTemplateDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/QueryBuilder.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4222
=> [GLT-4222] Update HibernateSampleDao to JPA Criteria

changes/add_new_concentration_units.md, changes/add_new_volume_units.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/ConcentrationUnit.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/VolumeUnit.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4233
=> [GLT-4233] New Units

RELEASE_NOTES.md, changes/fix_pinery_targetCellRecovery.md, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java
=> fixed Pinery sample attribute "Target Cell Recovery" value

RELEASE_NOTES.md, changes/fix_storageLocationSave.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultStorageLocationService.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4256
=> [GLT-4256] fixed saving storage locations

changes/fix_importExcelNumbers.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/spreadsheet/ExcelSpreadsheetWrapper.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4254
=> [GLT-4254] fixed Excel wrapper returning numbers in scientific notation

changes/add_assayTest_tissueOrigin.md, changes/note_pinery.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/AssayTest.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/AssayTestDto.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultAssayService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultAssayTestService.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java, miso-web/src/main/webapp/scripts/bulk.js, miso-web/src/main/webapp/scripts/bulk_assaytest.js, miso-web/src/main/webapp/scripts/bulk_containermodel.js, miso-web/src/main/webapp/scripts/bulk_deliverable.js, miso-web/src/main/webapp/scripts/bulk_librarydesigncode.js, miso-web/src/main/webapp/scripts/bulk_partitionqctype.js, miso-web/src/main/webapp/scripts/bulk_subproject.js, miso-web/src/main/webapp/scripts/list_assaytest.js, pinery-miso/pom.xml, pinery-miso/src/main/java/ca/on/oicr/pinery/lims/miso/MisoClient.java, pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllAssayTests.sql, sqlstore/src/main/resources/db/migration/V8501__test_tissueOrigin.sql
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4251
Ready for review, but requires a Pinery release and dependency bump before merging
=> [GLT-4251] added assay test tissue origin fields

changes/fix_sopUrl_characters.md, miso-web/src/main/webapp/scripts/bulk.js, miso-web/src/main/webapp/scripts/bulk_sop.js, miso-web/src/main/webapp/scripts/lims.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4258
=> [GLT-4258] fixed SOP URL validation

miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/AbstractIT.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/BulkPoolPage.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/element/HandsOnTable.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/util/HandsontableUtils.java
Jira ticket or GitHub issue:
Not ready for review. Making PR to run tests
=> [GLT-4262] Fixed tests

changes/fix_externalNameSearch.md, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDao.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/QueryBuilder.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/SubqueryBuilder.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4270
=> [GLT-4270] fixed sample search by external identifier

RELEASE_NOTES.md, changes/fix_subprojects.md, miso-web/src/main/webapp/scripts/bulk_subproject.js, miso-web/src/main/webapp/scripts/list_subproject.js
Jira ticket or GitHub issue: https://github.com/miso-lims/miso-lims/issues/2979
=> [#2979] fixed Project column on list and bulk Subproject tables

changes/fix_ghostSearch.md
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4296
This bug has already been fixed in `develop` - likely with the Hibernate update
=> [GLT-4296] added changelog note for fix already completed

changes/fix_duplicateGhost.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/SampleStore.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4297
=> [GLT-4297] fixed ghost tissue uniqueness validation

RELEASE_NOTES.md, changes/fix_addSupplemental.md, changes/fix_moveToReq.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/TransferService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultRequisitionService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultTransferService.java, miso-service/src/test/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleServiceTest.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/HibernateUtilDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4304
One issue because the items were detached when expected to be persistent, and the other because items were persistent when expected to be detached 😵‍💫
=> Glt 4304 req fixes

RELEASE_NOTES.md, changes/fix_addSupplementalLib.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultRequisitionService.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4304
Previous attempt fixed the issue with samples, but then copied that fix to the wrong place for libraries (removal operation instead of addition; fix is not required for removal)
=> [GLT-4304] fixed error adding supplemental libraries to requisition

changes/fix_exportBox.md, miso-web/src/main/webapp/scripts/0-urls.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4303
=> [GLT-4303] fixed URL for Export Box to Excel

changes/fix_saveReqQcType.md, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateQcTypeDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4310
=> [GLT-4310] fixed error saving requisition QC types

changes/fix_printDecsription_libraryAliquot.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/printing/PrintableField.java
Jira ticket or GitHub issue: n/a, reported by PMGC
=> fixed printing library aliquot descriptions

docs/admin/baremetal-installation-guide.md, docs/admin/compose-installation-guide.md, readme.md
=> misc documentation fixes

RELEASE_NOTES.md, changes/fix_addAssayMetric.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultAssayService.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4330
=> [GLT-4330] fixed error adding assay metrics

changes/add_sampleVolumeConcentration, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkSampleCreateIT.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkSampleEditIT.java, miso-web/src/main/webapp/scripts/bulk_sample.js
=> [GLT-4234] show tissue processing volume and concentration

changes/add_freezer_notes.md, miso-web/src/main/webapp/scripts/form_freezer.js
=> added some help text for freezers

changes/fix_instrument_uniqueBarcode.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultInstrumentService.java, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateInstrumentDaoIT.java, sqlstore/src/it/resources/db/migration/V9010__test_data.sql, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/InstrumentStore.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateInstrumentDao.java, sqlstore/src/main/resources/db/migration/V8501__unique_instruments.sql
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4341
=> [GLT-4341] added unique constraint for instrument barcode

changes/add_qcTypeList_archived.md, changes/fix_qcType_uniqueness.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultQcTypeService.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java, miso-web/src/main/webapp/scripts/list_qctype.js, sqlstore/src/it/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateQcTypeDaoIT.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/QualityControlTypeStore.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateQcTypeDao.java, sqlstore/src/main/resources/db/migration/V8502__unique_qcType.sql
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4347
=> [GLT-4347] added unique constraint for QC type names

docs/admin/site-configuration.md, docs/index.md, miso-web/src/main/webapp/WEB-INF/header.jsp, readme.md
=> remove twitter and gitter links

changes/add_GLT-4229.md, changes/change_GLT-4229.md, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/view/RequisitionController.java, miso-web/src/main/webapp/WEB-INF/pages/editRequisition.jsp, miso-web/src/main/webapp/scripts/0-urls.js, miso-web/src/main/webapp/scripts/list_samples.js
=> [GLT-4229] add prepared samples to edit requisition

changes/add_GC-10645.md, changes/change_GC-10645.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultUserService.java, miso-service/src/test/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultUserServiceTest.java
Jira ticket or GitHub issue: [GC-10645](https://jira.oicr.on.ca/browse/GC-10645)
=> [GC-10645] Make 15 char password min

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Deletable.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/MisoFilesManager.java, docs/developers-manual.md
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4359
=> [GLT-4359] updated developer guide

changes/add_ultima.md, changes/fix_createLibraryType.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/UltimaRun.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/type/PlatformType.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/run/RunDto.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/run/UltimaRunDto.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryTypeService.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkLibraryIT.java, sqlstore/src/main/resources/db/migration/V8503__ultima.sql
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4355
=> [GLT-4355] added Ultima PlatformType

changes/fix_sampleDistribution.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4365
=> [GLT-4365] fixed ClassCastException when distributing samples

changes/fix_distributionLocation.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryAliquotService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultPoolService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultTransferService.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/HibernateUtilDao.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4356
=> [GLT-4356] fixed removing distributed items from boxes

changes/change_mohExtraction_material.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/spreadsheet/SampleSpreadSheets.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4369
=> [GLT-4369] added tissue material to MOH Extraction Tracker download

changes/change_runLibMetrics_displayValue.md, miso-web/src/main/webapp/scripts/lims.js, miso-web/src/main/webapp/scripts/runLibraryMetrics_ajax.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4357
=> [GLT-4357] truncate values on Run-Library Metrics page

changes/fix_reqRunLibs.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/LibraryService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryService.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/LibraryRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/RequisitionRestController.java, sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/JpaCriteriaPaginatedDataSource.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4358
=> [GLT-4358] fixed missing run-libraries on Edit Req page

changes/change_libraryPrepSheets.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/spreadsheet/Column.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/spreadsheet/SampleSpreadSheets.java, pom.xml
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4351
=> [GLT-4351] updated library prep sample download sheets

miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/LibraryPage.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/element/Note.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/element/NotesDataTable.java
=> fixed library note UI tests

changes/change_oicrNaming_ultima.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/naming/generation/OicrBaseLibraryAliasGenerator.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/naming/generation/OicrLibraryAliquotAliasGenerator.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/naming/validation/OicrLibraryAliasValidator.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4380
=> [GLT-4380] updated OICR naming scheme to support Ultima libraries

changes/add_sequencing_parameter.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SequencingParameters.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SequencingParametersDto.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSequencingParametersService.java, miso-web/src/main/webapp/scripts/bulk.js, miso-web/src/main/webapp/scripts/bulk_sequencingparameters.js, sqlstore/src/main/resources/db/migration/V8503__ultima_seqparams.sql
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4377
=> [GLT-4377] added Ultima sequencing parameters Flows field

changes/change_noReqIdentity.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultRequisitionService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleRestController.java, miso-web/src/main/webapp/scripts/list_samples.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4389
=> [GLT-4389] prevent adding identity samples to a requisition

changes/change_pacbio_seqparam_level.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/type/PlatformType.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/run/RunPositionDto.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultRunService.java, miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/RunPageIT.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/ConstantsController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/RunRestController.java, miso-web/src/main/webapp/scripts/form_run.js, miso-web/src/main/webapp/scripts/list_run.js, miso-web/src/main/webapp/scripts/list_run_position.js, sqlstore/src/main/resources/db/migration/V8501__pacbio_seqparams.sql
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4387
=> [GLT-4387] sequencing parameters level depends on platform

changes/add_attachment_files_to_arrayruns.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/ArrayRun.java, docs/user_manual/attachments.md, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultFileAttachmentService.java, miso-web/src/main/webapp/WEB-INF/pages/editArrayRun.jsp, sqlstore/src/main/resources/db/migration/V8502__array_run_attachment.sql
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4237
=> attach files to array runs

changes/add_pacbio_runs.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Run.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SequencerPartitionContainerImpl.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/PoolService.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/RunService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultPoolService.java, miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultRunService.java, miso-service/src/test/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultRunServiceTest.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/service/RunScannerClient.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4392
=> [GLT-4392] save PacBio runs from Run Scanner with multiple SMRT cells

core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/view/ParentLibrary.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/type/CompressionFormat.java, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/IlluminaExperiment.java, docs/admin/site-configuration.md, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/CompressionFormatDto.java, miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/ConstantsController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/PoolRestController.java, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/view/ListPoolsController.java, miso-web/src/main/resources/miso.properties, miso-web/src/main/webapp/scripts/0-urls.js, miso-web/src/main/webapp/scripts/bulk_pool.js, miso-web/src/main/webapp/scripts/lims.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GP-4509
Note: I will rebase after fixes are complete
Looking for feedback:
Download file name (this is standard from outside samplesheets atm, can it change to be more readable?)
=> Gp 4509.samplesheetdragen

changes/fix_reads_section_samplesheets.md, core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/IlluminaExperiment.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GP-4765
- [ x Includes a change file
=> fix reads in samplesheets (allow duplicate lines)

.github/workflows/miso_web_st.yml
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4410
=> [GLT-4410] added workflow to run spring tests

miso-web/src/it/resources/tomcat-config/miso.it.properties, miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/AdminRestController.java, miso-web/src/spring-test/java/uk/ac/bbsrc/tgac/miso/webapp/springtest/AdminRestControllerST.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4430
Spring tests for AdminRestController.java
=> [GLT-4430] added admin-related rest tests

miso-web/src/spring-test/java/uk/ac/bbsrc/tgac/miso/webapp/springtest/DefaultRestControllerST.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4447
Added default unmapped rest endpoint test
=> [GLT-4447] added default unmapped rest test

changes/fix_libraryAliquot_creationDate_validation.md, miso-web/src/main/webapp/scripts/bulk.js, miso-web/src/main/webapp/scripts/bulk_library.js, miso-web/src/main/webapp/scripts/bulk_libraryaliquot.js, miso-web/src/main/webapp/scripts/bulk_sample.js
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4639
=> [GLT-4639] fixed library aliquot creation date validation

miso-web/src/spring-test/java/uk/ac/bbsrc/tgac/miso/webapp/springtest/InstrumentStatusRestControllerST.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4457
=> [GLT-4457] added instrument status rest test

miso-web/src/it/resources/db/migration/clear_test_data.sql, miso-web/src/it/resources/db/migration/integration_test_data.sql, miso-web/src/spring-test/java/uk/ac/bbsrc/tgac/miso/webapp/springtest/AttachmentRestControllerST.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4438
=> [GLT-4438] attachment rest tests added

miso-web/src/spring-test/java/uk/ac/bbsrc/tgac/miso/webapp/springtest/AttachmentCategoryRestControllerST.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4437
Note: can only be reviewed after https://github.com/miso-lims/miso-lims/pull/3075 is merged
=> [GLT-4437] added attachment category rest tests

miso-web/src/spring-test/java/uk/ac/bbsrc/tgac/miso/webapp/springtest/BoxableRestControllerST.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4440
=> [GLT-4440] added boxable rest tests

miso-web/src/it/resources/db/migration/integration_test_data.sql, miso-web/src/spring-test/java/uk/ac/bbsrc/tgac/miso/webapp/springtest/DeletionRestControllerST.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4448
note: #3075 must be merged before this can be reviewed
=> [GLT-4448] added deletion rest test

miso-web/src/spring-test/java/uk/ac/bbsrc/tgac/miso/webapp/springtest/DeliverableRestControllerST.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4450
=> [GLT-4450] added deliverable rest tests

miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultDeliverableCategoryService.java, miso-web/src/spring-test/java/uk/ac/bbsrc/tgac/miso/webapp/springtest/DeliverableCategoryRestControllerST.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4449
Can be reviewed after #3074 is merged
=> [GLT-4449] added deliverable category rest tests

.gitmodules
=> remove outdated git modules file

miso-web/src/it/resources/db/migration/integration_test_data.sql, miso-web/src/spring-test/java/uk/ac/bbsrc/tgac/miso/webapp/springtest/InstrumentRestControllerST.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4456
=> [GLT-4456] added instrument rest tests

miso-web/src/spring-test/java/uk/ac/bbsrc/tgac/miso/webapp/springtest/AbstractST.java, miso-web/src/spring-test/java/uk/ac/bbsrc/tgac/miso/webapp/springtest/KitDescriptorRestControllerST.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4459
=> [GLT-4459] added kit descriptor rest tests

miso-web/src/spring-test/java/uk/ac/bbsrc/tgac/miso/webapp/springtest/LibrarySpikeInRestControllerST.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4467
=> [GLT-4467] added library spike in rest tests

miso-web/src/spring-test/java/uk/ac/bbsrc/tgac/miso/webapp/springtest/PartitionQcTypeRestControllerST.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4474
=> [GLT-4474] added partition QC type rest tests 

miso-web/src/spring-test/java/uk/ac/bbsrc/tgac/miso/webapp/springtest/LibrarySelectionRestControllerST.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4466
=> [GLT-4466] added library selection rest tests

miso-web/src/spring-test/java/uk/ac/bbsrc/tgac/miso/webapp/springtest/LibraryDesignRestControllerST.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4462
#3075 must be merged first
=> [GLT-4462] added library design rest tests

miso-web/src/spring-test/java/uk/ac/bbsrc/tgac/miso/webapp/springtest/AssayTestRestControllerST.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4436
=> [GLT-4436] added assay test rest tests

miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultPipelineService.java, miso-web/src/spring-test/java/uk/ac/bbsrc/tgac/miso/webapp/springtest/AbstractST.java, miso-web/src/spring-test/java/uk/ac/bbsrc/tgac/miso/webapp/springtest/PipelineRestControllerST.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4475
=> [GLT-4475] added pipeline rest tests

miso-web/src/it/resources/db/migration/clear_test_data.sql, miso-web/src/it/resources/db/migration/integration_test_data.sql, miso-web/src/spring-test/java/uk/ac/bbsrc/tgac/miso/webapp/springtest/ExperimentRestControllerST.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4452
Note: #3074 must be merged first
=> [GLT-4452] added experiment rest tests

miso-web/src/spring-test/java/uk/ac/bbsrc/tgac/miso/webapp/springtest/PoolOrderRestControllerST.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4476
=> [GLT-4476] added pool order rest tests

miso-web/src/spring-test/java/uk/ac/bbsrc/tgac/miso/webapp/springtest/MetricRestControllerST.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4471
=> [GLT-4471] added metric rest tests

miso-web/src/spring-test/java/uk/ac/bbsrc/tgac/miso/webapp/springtest/ContactRoleControllerST.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4532
note: depends on #3128
=> [GLT-4532] added contact role view tests

miso-web/src/spring-test/java/uk/ac/bbsrc/tgac/miso/webapp/springtest/AssayControllerST.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4525
note: depends on #3128
=> [GLT-4525] added assay view tests

miso-web/src/spring-test/java/uk/ac/bbsrc/tgac/miso/webapp/springtest/DetailedQcStatusControllerST.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4535
note: depends on #3128
=> [GLT-4535] detailed QC status view tests added

miso-web/src/spring-test/java/uk/ac/bbsrc/tgac/AttachmentCategoryControllerST.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4527
note: depends on #3128
=> [GLT-4527] added attachment category view tests

changes/change_sampleProject_changeMessage.md, sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_sample.sql
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4672
=> [GLT-4672] show project code instead of name in sample changelog
