- miso-external-web/pom.xml
- miso-external-web/src/main/webapp/scripts/external.js
Fix for external webapp's JDBC authentication issue, as described in JIRA issue [MISO-115](https://tracker.tgac.ac.uk/browse/MISO-115). Also includes cleanup of duplicate items in external webapp POM.
> Jdbc auth external

- miso-web/src/main/webapp/pages/editLibrary.jsp
https://tracker.tgac.ac.uk/browse/MISO-161
This applies to /miso/library/ library dilutions panel.
Small UI change, all platforms will show a `create pools` button. Solid and 454 platforms show an `Add emPCR` button.
> Bugfix: MISO-161 Add emPCR

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/security/util/LimsSecurityUtils.java
All database users are now created with lowercase usernames to prevent duplication.
> Bugfix: no more differently cased ldap users

- .gitignore
- sqlstore/pom.xml
Added note in pom describing creation of the flyway credentials file "flyway.properties".
> Ignored database credentials file for flyway. 

- miso-web/src/main/webapp/scripts/library_ajax.js
- miso-web/src/main/webapp/scripts/sample_ajax.js
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/LibraryControllerHelperService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/SampleControllerHelperService.java
Adds hidden columns to the tables on List Samples and List Libraries pages so that they can be searched by barcode
> Search by barcode

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditPlateController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditPoolController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
- miso-web/src/main/resources/external/miso.properties
- miso-web/src/main/resources/sql/db-config.xml
- miso-web/src/main/webapp/WEB-INF/miso-servlet.xml
- miso-web/src/main/webapp/pages/editLibrary.jsp
- miso-web/src/main/webapp/pages/editPlate.jsp
- miso-web/src/main/webapp/pages/editPool.jsp
- miso-web/src/main/webapp/pages/editSample.jsp
- miso-web/src/main/webapp/scripts/library_ajax.js
- miso-web/src/main/webapp/scripts/plate_ajax.js
- miso-web/src/main/webapp/scripts/pool_ajax.js
- miso-web/src/main/webapp/scripts/sample_ajax.js
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/LibraryControllerHelperService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/PlateControllerHelperService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/PoolControllerHelperService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/SampleControllerHelperService.java
- spring/src/test/java/uk/ac/bbsrc/tgac/miso/spring/ajax/test/LibraryControllerHelperServiceTestSuite.java
- spring/src/test/java/uk/ac/bbsrc/tgac/miso/spring/ajax/test/PlateControllerHelperServiceTestSuite.java
- spring/src/test/java/uk/ac/bbsrc/tgac/miso/spring/ajax/test/PoolControllerHelperServiceTestSuite.java
- spring/src/test/java/uk/ac/bbsrc/tgac/miso/spring/ajax/test/SampleControllerHelperServiceTestSuite.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLLibraryDAO.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLPlateDAO.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLPoolDAO.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLSampleDAO.java
Rebasing the other branch broke everything... so this one should work!
> manual entry of identificationBarcodes

- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLLibraryDAO.java
Bugfix to prevent null pointer exceptions when library objects are cahce. 
@froggleston can you please review?  I have tested locally without issue.
> Add fix for library cache null pointers

- miso-web/src/main/webapp/scripts/editProject_sample.js
- miso-web/src/main/webapp/scripts/experiment_ajax.js
- miso-web/src/main/webapp/scripts/library_ajax.js
- miso-web/src/main/webapp/scripts/plate_ajax.js
- miso-web/src/main/webapp/scripts/pool_ajax.js
- miso-web/src/main/webapp/scripts/printer_ajax.js
- miso-web/src/main/webapp/scripts/project_ajax.js
- miso-web/src/main/webapp/scripts/run_ajax.js
- miso-web/src/main/webapp/scripts/sample_ajax.js
jQueryUI dialog creation had been wrapped in an anonymous jQuery
function and then opened, but the anonymous jQuery function was not
immediately executed (and would sometimes not execute, causing the
reported behavior).
Since the jQueryUI dialog creation will only be invoked when the
surrounding JavaScript function is called, the anonymous jQuery function
and the "autoOpen: false" flag are not required.
> Fix for MISO-193: popup windows occasionally don't pop up

- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLLibraryDAO.java
Please sneak this one in ahead of the merge freeze!
> Fix for accidental removal of SQLLibraryDAO imports

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/MisoRequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/RequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/UserAuthMisoRequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/LibraryDilutionStore.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLEmPCRDilutionDAO.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLLibraryDilutionDAO.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLPoolDAO.java
- sqlstore/src/main/resources/db/migration/V0009__drop_old_pool.sql
Add useful changelogs to pools that include information on their contents.
> Pool changelogs

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractLibrary.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractPool.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Library.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Pool.java
- miso-web/src/main/webapp/pages/editLibrary.jsp
- miso-web/src/main/webapp/pages/readyPools.jsp
- miso-web/src/main/webapp/styles/style.css
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/PoolControllerHelperService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/PoolSearchService.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLLibraryDAO.java
- sqlstore/src/main/resources/db/migration/V0005__library_low_quality.sql
This is described in GLT-277.  The idea is that a library might be lousy and shouldn't be put on the sequencer again. This change adds that flag and then highlights pools containing such libraries.
> Add a “low quality” flag

- miso-web/src/main/webapp/pages/editStudy.jsp
Otherwise, the change logs contents are cut-off.
> Move change log into main part of the study page

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditRunController.java
- miso-web/src/main/webapp/pages/editLibrary.jsp
- miso-web/src/main/webapp/pages/editSample.jsp
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLRunDAO.java
For GLT-283, we wanted the run's status to show on the Library and Sample pages.
> Show status for runs and fix some bugs

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditRunController.java
GLT-369 - Created URL mapping that uses run alias instead of ID for easy linking to runs from JIRA, etc.
> Add /miso/run/alias/{runAlias} url mapping

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/naming/AllowAnythingEntityNamingScheme.java
- core/src/test/java/uk/ac/bbsrc/tgac/miso/core/test/NamingTests.java
Ironically, the “allow anything” scheme was rather restrictive.
> Make allow anything naming scheme allow anything

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditRunController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSequencerPartitionContainerController.java
- spring/src/test/java/uk/ac/bbsrc/tgac/miso/spring/ajax/test/LibraryControllerHelperServiceTestSuite.java
- spring/src/test/java/uk/ac/bbsrc/tgac/miso/spring/ajax/test/PlateControllerHelperServiceTestSuite.java
- spring/src/test/java/uk/ac/bbsrc/tgac/miso/spring/ajax/test/PoolControllerHelperServiceTestSuite.java
- spring/src/test/java/uk/ac/bbsrc/tgac/miso/spring/ajax/test/ProjectControllerHelperServiceTestSuite.java
- spring/src/test/java/uk/ac/bbsrc/tgac/miso/spring/ajax/test/SampleControllerHelperServiceTestSuite.java
Fixes brokenness in current develop branch by adding in the (hopefully) final additions required for changelogs.
* updates ControllerHelperServiceTests that require User
* adds missing last modifiers for run and partition container saves
> More lastModifier additions

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/UserAuthMisoRequestManager.java
- core/src/test/java/uk/ac/bbsrc/tgac/miso/core/manager/UserAuthMisoRequestManagerTestSuite.java
- miso-web/src/main/webapp/WEB-INF/miso-config.xml
Inheritance was an awkward way to go about this. I've switched to a delegation model and discovered lots of methods weren't covered before. I invented policy to cover those cases and am open to changing it as I was mostly guessing.
> Make the UserAuthMisoRequestManager use delegation

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/MenuController.java
- miso-web/src/main/webapp/pages/adminMenu.jsp
- miso-web/src/main/webapp/pages/editLibrary.jsp
- miso-web/src/main/webapp/pages/editPlate.jsp
- miso-web/src/main/webapp/pages/editPool.jsp
- miso-web/src/main/webapp/pages/editSample.jsp
- miso-web/src/main/webapp/pages/myAccount.jsp
- hide "Regenerate All Barcodes" option if autogenerateIdentificationBarcodes is turned off in miso.properties
- hide option to update an identificationBarcode until the item has been created.
> GLT-407 more autogenerate identification barcodes

- sqlstore/src/main/resources/db/migration/afterMigrate.sql
I forgot all of them long ago.
> Add missing DROP TRIGGER commands

- miso-web/src/main/webapp/pages/editLibrary.jsp
- miso-web/src/main/webapp/pages/editSample.jsp
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/LibraryControllerHelperService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/PoolControllerHelperService.java
Add aliases to places where only names are present (except for in breadcrumbs)
> GLT-408 display parent aliases

- miso-web/src/main/webapp/pages/editIlluminaPool.jsp
- miso-web/src/main/webapp/pages/editLibrary.jsp
- miso-web/src/main/webapp/pages/editProject.jsp
- miso-web/src/main/webapp/pages/editSample.jsp
- miso-web/src/main/webapp/pages/editStudy.jsp
- miso-web/src/main/webapp/pages/listKitDescriptors.jsp
- miso-web/src/main/webapp/pages/listPlates.jsp
- miso-web/src/main/webapp/pages/listSubmissions.jsp
- miso-web/src/main/webapp/pages/readyPools.jsp
- miso-web/src/main/webapp/scripts/box_ajax.js
- miso-web/src/main/webapp/scripts/experiment_ajax.js
- miso-web/src/main/webapp/scripts/library_ajax.js
- miso-web/src/main/webapp/scripts/pool_ajax.js
- miso-web/src/main/webapp/scripts/project_ajax.js
- miso-web/src/main/webapp/scripts/run_ajax.js
- miso-web/src/main/webapp/scripts/sample_ajax.js
- miso-web/src/main/webapp/scripts/sequencer_partition_container_ajax.js
- miso-web/src/main/webapp/scripts/study_ajax.js
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/ContainerControllerHelperService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/ExperimentControllerHelperService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/LibraryControllerHelperService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/PlateControllerHelperService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/PoolControllerHelperService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/ProjectControllerHelperService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/RunControllerHelperService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/SampleControllerHelperService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/StudyControllerHelperService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/TableHelper.java
Instead of having to move the mouse to the far side of the screen to click a tiny pencil icon, users can now click on the Name or Alias of their chosen item to navigate to its page.
> Hyperlinkify names and aliases in listing tables

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/UserAuthMisoRequestManager.java
- core/src/test/java/uk/ac/bbsrc/tgac/miso/core/manager/UserAuthMisoRequestManagerTestSuite.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLLibraryDAOTest.java
UserAuthMisoRequestManager changes introduced in the sample_hierarchy branch.
> GLT-432 Updated unit tests to match code that was modified by the

- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLSampleDAO.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/AllTestsSuite.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLSampleDAOTest.java
- sqlstore/src/test/resources/db/test_migration/V9000__miso_test_data.test.sql
Squashed commits:
[5e6d1fd] added unit tests for  SampleDAO
> added unit tests for SampleDAO (+1 squashed commit)

- miso-web/src/main/webapp/scripts/library_ajax.js
- miso-web/src/main/webapp/scripts/plate_ajax.js
- miso-web/src/main/webapp/scripts/pool_ajax.js
- miso-web/src/main/webapp/scripts/sample_ajax.js
[MISO-193](https://tracker.tgac.ac.uk/browse/MISO-193) describes modal windows for location barcode modal windows occasionally not opening. This is the fix for identification barcode modal windows, which were implemented in the same way as the broken location barcode modal windows.
> GLT-409 fix potential breaking of idbc modal windows

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SampleGroupId.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleGroupImpl.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleGroupDto.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/SampleGroupService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleGroupService.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleGroupController.java
- sqlstore/src/main/resources/db/migration/V0010__sample_hierarchy.sql
fix SampleGroup-Subproject foreign key datatype
(this code was actually written by @apmasell )
> Add subprojects as part of sample groups

- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/SampleAdditionalInfoDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/SampleAnalyteDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleAdditionalInfoDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleAnalyteDao.java
> Allow getting analytes and information by sample id

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SampleTissue.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleTissueImpl.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleTissueDto.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/SampleTissueService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleTissueService.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/TissueSampleController.java
- miso-web/src/main/resources/sql/db-config.xml
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/SampleTissueDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleTissueDao.java
- sqlstore/src/main/resources/db/migration/V0010__sample_hierarchy.sql
> Added SampleTissue table, model, WS, and DAO

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/LimsUtils.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleOptionsDto.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/ui/SampleOptionsController.java
Checks whether two sampleClasses have a parent-child relationship
(Merge 4)
> Sample valid relationship checker

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Lab.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SampleTissue.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/InstituteImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/LabImpl.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/LabDto.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleTissueDto.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/LabService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultInstituteService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLabService.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/LabController.java
- miso-web/src/main/resources/sql/db-config.xml
- miso-web/src/main/webapp/pages/instituteDefaults.jsp
- miso-web/src/main/webapp/scripts/instituteDefaults_ajax.js
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/LabDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLabDao.java
- sqlstore/src/main/resources/db/migration/V0010__sample_hierarchy.sql
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/AllTestsSuite.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateInstituteDaoTest.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLabDaoTest.java
- sqlstore/src/test/resources/db-test-context.xml
- sqlstore/src/test/resources/db/test_migration/V9000__miso_test_data.test.sql
> Add Lab and link SampleTissue to Lab instead of Institute

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleAdditionalInfoController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleAnalyteController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleTissueController.java
* rename TissueSampleController to SampleTissueController
* change endpoints for SampleAdditionalInfo, SampleAnalyte and SampleTissue Controllers to be more RESTful
* write URLs only if referent is not null
> updates for REST Sample*Controllers (OICR Sample Hierarchy)

- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/LabDto.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleOptionsDto.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/LabService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLabService.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/InstituteController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/KitDescriptorController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/LabController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/QcPassedDetailController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleAdditionalInfoController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleAnalyteController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleClassController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleGroupController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleIdentityController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleNumberPerProjectController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SamplePurposeController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleValidRelationshipController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SubprojectController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/TissueMaterialController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/TissueOriginController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/TissueTypeController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/ui/SampleOptionsController.java
- miso-web/src/main/webapp/pages/instituteDefaults.jsp
- miso-web/src/main/webapp/pages/myAccount.jsp
- miso-web/src/main/webapp/scripts/instituteDefaults_ajax.js
- Labs and Institutes are now editable by admins
- all empty collection return an empty list instead of a 404
- fixed some small typos
> Update Lab-Institute connection & add Lab front end

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleAdditionalInfoImpl.java
It caused difficulty with hibernate mapping.
> Glt 463 remove unused 'volume' from SampleAdditionalInfoImpl

- miso-web/src/main/webapp/pages/instituteDefaults.jsp
- miso-web/src/main/webapp/pages/myAccount.jsp
- miso-web/src/main/webapp/scripts/instituteDefaults_ajax.js
Clicking on anchor links for the Institute Defaults page now expands the table and jumps to the table.
> Expand table if anchor link was clicked

- miso-web/src/main/webapp/pages/editPlate.jsp
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLPlateDAO.java
- sqlstore/src/main/resources/db/migration/afterMigrate.sql
- Hide Options menu after plate creation
- Add text explaining when to upload doc (before creation)
> MISO-203 add text to plate

- miso-web/src/main/webapp/pages/editUser.jsp
> namepsace validateUser correctly

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractBoxable.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractSample.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Boxable.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/LimsUtils.java
- core/src/test/java/uk/ac/bbsrc/tgac/miso/core/util/LimsUtilsTest.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleDto.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleValidRelationshipService.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLLibraryDAO.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLSampleDAO.java
Also updated Sample and SampleDto to write volume. Updated SampleRelationshipValidation to permit simple samples as valid.
> GLT-459 Update Sample WS to create un-parented samples

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/UserAuthMisoRequestManager.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/context/RestSignatureFilter.java
- miso-web/src/main/resources/external/miso.properties
- miso-web/src/main/resources/internal/miso.properties
- notification-consumer-services/src/main/java/uk/ac/bbsrc/tgac/miso/notification/consumer/service/mechanism/PacBioNotificationMessageConsumerMechanism.java
- run-tools/src/main/java/uk/ac/bbsrc/tgac/miso/tools/run/RunFolderConstants.java
- sqlstore/src/main/resources/db/migration/V0017__notification_user.sql
Notification server message consumption was broken due to missing lastModifier after we added the field. Added a 'notification' user to use for this.
Also made PacBio RunFolderConstants more flexible, so that they'll work for both OICR and TGAC folder name patterns (date format yyyyMMdd or yyyy_MM_dd)
> Glt 449 notification fix

- pom.xml
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLStudyDAO.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/AllTestsSuite.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLStudyDAOTest.java
- sqlstore/src/test/resources/db/test_migration/V9000__miso_test_data.test.sql
> GLT-490 Added tests for SQLStudyDAO

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/MisoRequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/RequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/UserAuthMisoRequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/LibraryDilutionStore.java
- core/src/test/java/uk/ac/bbsrc/tgac/miso/core/manager/UserAuthMisoRequestManagerTestSuite.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/PoolSearchService.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLLibraryDilutionDAO.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/AllTestsSuite.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/LimsDAOTestCase.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLLibraryDilutionDAOTest.java
Involved fixing some queries (some methods that were supposed to filter by platform weren't doing this), removing unused methods, and renaming unclearly-named methods in the DAO
> LibraryDilution DAO tests

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/kit/KitDescriptor.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditKitDescriptorController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/KitDescriptorController.java
- miso-web/src/main/resources/sql/db-config.xml
- miso-web/src/main/webapp/pages/editKitDescriptor.jsp
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLKitDAO.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLStudyDAO.java
- sqlstore/src/main/resources/db/migration/V0018__kit_change_logs.sql
- sqlstore/src/main/resources/db/migration/afterMigrate.sql
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLKitDAOTest.java
Add them to kits and avoid blank log entries
> Improve change logs

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractLibrary.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/LibraryAdditionalInfo.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/LibraryAdditionalInfoImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/LibraryImpl.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/LibraryAdditionalInfoDto.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/LibraryAdditionalInfoService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryAdditionalInfoService.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/LibraryAdditionalInfoController.java
- miso-web/src/main/resources/sql/db-config.xml
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/LibraryAdditionalInfoDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryAdditionalInfoDao.java
- sqlstore/src/main/resources/db/migration/V0010__sample_hierarchy.sql
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/AllTestsSuite.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryAdditionalInfoDaoTest.java
- sqlstore/src/test/resources/db-test-context.xml
- sqlstore/src/test/resources/db/test_migration/V9000__miso_test_data.test.sql
> Library additional info

- miso-web/src/main/webapp/pages/poolWizard.jsp
- miso-web/src/main/webapp/scripts/pool_ajax.js
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/PoolControllerHelperService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/PoolWizardControllerHelperService.java
A Library can have multiple dilutions which differ only in their concentrations. Show concentration of library dilutions when displaying all dilutions in a table.
> Add concentration to Poolable Elements tables

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractPool.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditPoolController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditProjectController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/ListPoolsController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/PoolWizardController.java
- miso-web/src/main/webapp/pages/editLibrary.jsp
- miso-web/src/main/webapp/pages/editPool.jsp
- miso-web/src/main/webapp/pages/editProject.jsp
- miso-web/src/main/webapp/pages/editSample.jsp
- miso-web/src/main/webapp/pages/listPools.jsp
- miso-web/src/main/webapp/pages/poolWizard.jsp
- miso-web/src/main/webapp/scripts/editProject_library.js
- miso-web/src/main/webapp/scripts/pool_ajax.js
Concentration was labelled "Results" in several places, and the units were missing in most places. Will now be labelled consistently: Concentration (nM)
> Made pool and ldi concentration labels consistent

- miso-web/src/main/webapp/pages/adminsub.jsp
- miso-web/src/main/webapp/pages/editProject.jsp
- miso-web/src/main/webapp/pages/flexreport.jsp
- miso-web/src/main/webapp/pages/listAnalysisTasks.jsp
- miso-web/src/main/webapp/pages/listProjects.jsp
- miso-web/src/main/webapp/pages/projectMenu.jsp
- miso-web/src/main/webapp/pages/reporting.jsp
This fixes a few missing nav bars.
> Add navigation menu on all pages

- miso-web/src/main/webapp/pages/editRun.jsp
- miso-web/src/main/webapp/pages/editSequencerReference.jsp
- miso-web/src/main/webapp/pages/editServiceRecord.jsp
- miso-web/src/main/webapp/scripts/library_ajax.js
- miso-web/src/main/webapp/scripts/pool_ajax.js
- miso-web/src/main/webapp/scripts/printer_ajax.js
- miso-web/src/main/webapp/scripts/run_ajax.js
- miso-web/src/main/webapp/scripts/sample_ajax.js
- miso-web/src/main/webapp/scripts/sequencer_reference_ajax.js
> Fix broken javascript

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractPool.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/FormUtils.java
Some bug fixes discovered debugging plate uploading
> Plate and pool bug fixes

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/MisoRequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/RequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/UserAuthMisoRequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/SampleStore.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
- miso-web/src/main/webapp/pages/bulkEditSamples.jsp
- miso-web/src/main/webapp/pages/editSample.jsp
- miso-web/src/main/webapp/pages/listSamples.jsp
- miso-web/src/main/webapp/scripts/sample_ajax.js
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/SampleControllerHelperService.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDao.java
- provides a controller method for getting samples from a list of IDs from the database for bulk editing.
- creates a new page for bulk editing.
> GLT-522 Bulk edit samples

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleImpl.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
- miso-web/src/main/webapp/pages/bulkEditSamples.jsp
- miso-web/src/main/webapp/pages/editSample.jsp
- miso-web/src/main/webapp/scripts/instituteDefaults_ajax.js
- miso-web/src/main/webapp/scripts/sample_hot.js
Samples no longer get stuck "saving forever" in Handsontable. Dates are also saved properly.
> Fix for Handsontable save not working properly

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SampleAdditionalInfo.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SampleTissue.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleAdditionalInfoImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleTissueImpl.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleAdditionalInfoDto.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleTissueDto.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleAdditionalInfoService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleTissueService.java
- miso-web/src/main/webapp/scripts/sample_hot.js
- sqlstore/src/main/resources/db/migration/V0010__sample_hierarchy.sql
GLT-542: remove BioBankId from SampleTissueDto
GLT-543: remove SampleTissue.instituteTissueName and add SampleAdditionalInfo.externalInstituteIdentifier
> Remove BioBankId and move instituteTissueName

- miso-web/src/main/webapp/scripts/sample_hot.js
Added a serial function to execute an array of functions in order. Used this to bulk samples.
> GLT-535 Save detailed samples sequentially

- miso-web/src/main/webapp/scripts/library_ajax.js
- miso-web/src/main/webapp/scripts/sample_ajax.js
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/LibraryControllerHelperService.java
- also adds additional bulk action options to Samples
- several of these are placeholders for now, to be implemented later.
> GLT-274 add select checkboxes to List Libraries page

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractSample.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleImpl.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleAdditionalInfoDto.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
- miso-web/src/main/webapp/pages/bulkEditSamples.jsp
- miso-web/src/main/webapp/pages/editSample.jsp
- miso-web/src/main/webapp/scripts/instituteDefaults_ajax.js
- miso-web/src/main/webapp/scripts/library_ajax.js
- miso-web/src/main/webapp/scripts/sample_ajax.js
- miso-web/src/main/webapp/scripts/sample_hot.js
- `/miso/bulk/create/{sampleIds}&scid={sampleClassId}` for propagating samples from other samples
- `/miso/bulk/edit/{sampleIds}` for editing samples in place
> GLT-537 && GLT-552 Bulk edit and bulk propagate samples

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractSample.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-web/src/main/webapp/scripts/sample_hot.js
- fixes issues identified in PR #177
> GLT-553 fixes for Sample builder and Dto

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/LibraryDilution.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/TargetedResequencing.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/factory/DataObjectFactory.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/factory/TgacDataObjectFactory.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/MisoRequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/RequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/UserAuthMisoRequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/TargetedResequencingStore.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java
- miso-web/src/main/resources/ehcache.xml
- miso-web/src/main/resources/sql/db-config.xml
- miso-web/src/main/webapp/pages/editLibrary.jsp
- miso-web/src/main/webapp/scripts/library_ajax.js
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/LibraryControllerHelperService.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLLibraryDilutionDAO.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLTargetedResequencingDAO.java
- sqlstore/src/main/resources/db/migration/V0021__targeted_resequencing.sql
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLLibraryDilutionDAOTest.java
Added db, dao and ui. Ui is available when displaying a single library from the list of libraries.
> GLT-418 Add Targeted Resequencing to Library Dilutions

- miso-web/src/main/resources/external/miso.properties
- miso-web/src/main/webapp/pages/bulkEditSamples.jsp
- miso-web/src/main/webapp/pages/editSample.jsp
- miso-web/src/main/webapp/scripts/sample_hot.js
- GLT-559: fixes JSON parse error in bulk saving plain samples
- GLT-561: permits empty aliases if a sample alias generator is avilable
> Fixes for GLT-559, GLT-561

- miso-web/src/main/webapp/pages/editSample.jsp
Added note to indicate that these attributes can only be modified in the
bulk edit form.
> GLT-452 Added read-only fields to display detailed sample attributes.

- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryAdditionalInfoDao.java
> Avoid NPE when library kit is null

- miso-web/src/main/webapp/scripts/library_ajax.js
Removes a null element reference so that library bulk action actually work.
> GLT-595 remove null reference

- miso-web/src/main/webapp/pages/bulkEditSamples.jsp
- miso-web/src/main/webapp/scripts/sample_hot.js
- GLT-586 display parent alias in Sample handsontable
- GLT-617 stop JS from freezing page during sample Handsontable creation
- also allows user to edit samples belonging to multiple samples of the same class so long as they are in the same category (ex. Primary & Reference **Tissue**)
> GLT-586 & GLT-617

- miso-web/src/main/webapp/scripts/library_hot.js
- miso-web/src/main/webapp/scripts/sample_hot.js
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDao.java
- fixes "save forever" issue. (once and for all?)
- displays correct numbers of items which have been saved
> GLT-568 improve save message

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractSample.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Identity.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SampleAnalyte.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SampleTissue.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleAdditionalInfoImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/naming/OicrSampleAliasGenerator.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/naming/OicrSampleNamingScheme.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleDto.java
- miso-service/pom.xml
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/SampleService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java
- miso-service/src/test/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleServiceTestSuite.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/ui/SampleOptionsController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/util/form/SelectTag.java
- miso-web/src/main/webapp/pages/editSample.jsp
- miso-web/src/main/webapp/scripts/sample_ajax.js
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/HibernateSampleClassDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/SampleClassDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/SampleDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDao.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDaoTest.java
Create and edit detailed samples on the Create/Edit Sample (single) page. Includes major refactoring of the sample service and DAO (with tests!)
> Glt 578 edit detailed sample

- miso-web/src/main/webapp/pages/bulkEditLibraries.jsp
- miso-web/src/main/webapp/pages/bulkEditSamples.jsp
- miso-web/src/main/webapp/pages/editSample.jsp
- miso-web/src/main/webapp/scripts/library_hot.js
- miso-web/src/main/webapp/scripts/sample_hot.js
- miso-web/src/main/webapp/scripts/shared_hot.js
Extracts code shared between Sample and Library uses of Handsontable. Includes changes made in response to comments on PR #222 .
> GLT-664 Refactor shared Handsontable code to own module

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractLibrary.java
- miso-web/src/main/webapp/pages/editLibrary.jsp
- miso-web/src/main/webapp/scripts/library_ajax.js
plus bonus fix for libraryKit, which wasn't getting marked as required.
> GLT-720 fix set tagbarcode error

- miso-web/src/main/webapp/pages/editRun.jsp
- miso-web/src/main/webapp/pages/editSequencerPartitionContainer.jsp
- miso-web/src/main/webapp/pages/listSequencerReferences.jsp
- miso-web/src/main/webapp/scripts/library_ajax.js
- miso-web/src/main/webapp/scripts/plate_ajax.js
- miso-web/src/main/webapp/scripts/pool_ajax.js
- miso-web/src/main/webapp/scripts/project_ajax.js
- miso-web/src/main/webapp/scripts/run_ajax.js
- miso-web/src/main/webapp/scripts/sample_ajax.js
- miso-web/src/main/webapp/scripts/sequencer_partition_container_ajax.js
- fix for the occasion when you click a second time on the "edit ID Barcode" pencil for a container, and it fills the container's ID Barcode text field with HTML to make the text field
- also contains JS formatting fixes
> GLT-676 fix partition container pencil bug

- miso-web/src/main/webapp/pages/editLibrary.jsp
This prevents the missing index select box problem
> Set barcode family on page load

- miso-web/src/main/webapp/scripts/library_hot.js
- miso-web/src/main/webapp/scripts/sample_hot.js
Well, more helpful than the existing nothing. At least it lets the user know it wasn't their fault.
> GLT-693 show helpful message for HOT 500-series errors

- analysis-server/pom.xml
- core/pom.xml
- integration-tools/pom.xml
- miso-dto/pom.xml
- miso-web/pom.xml
- notification-server/pom.xml
- pom.xml
- run-tools/pom.xml
- runstats-client/pom.xml
- spring/pom.xml
- sqlstore/pom.xml
Also updated for one-jar and open symphony oscore as they are no longer available from googlecode.
> GLT-731 updated maven config for metrix dependency

- core/src/test/java/uk/ac/bbsrc/tgac/miso/core/test/FormUtilsTests.java
- notification-server/src/test/java/uk/ac/bbsrc/tgac/miso/notification/service/IlluminaTransformerTestSuite.java
- pom.xml
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLStatusDAOTest.java
Tests are failing!
These need investigation.  I have @Ignored them for now.
I also added some changes to cobertura to generate coverage reports.
You can see the report by running:
`mvn cobertura:cobertura`
> Enable cobertura / Ignore Tests

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/StatsController.java
(instead of to awkward alternate List Sequencers page)
> GLT-738 redirect to sequencer ref after saving it

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/LibraryRestController.java
- miso-web/src/main/webapp/pages/bulkEditLibraries.jsp
- miso-web/src/main/webapp/scripts/library_hot.js
* update TagBarcodes ModelAttribute to contain all barcodes
(and Handsontable code to match); reduces AJAX calls
* EditLibraryController: change (TagBarcode)Strategy to TagBarcodeFamily
* add "No barcode" option for each platform
* update LibAddInfoService to set library before save
> GLT-566 Make all barcodes available on page

- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/IdentityService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/SampleAdditionalInfoService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/SampleAnalyteService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/SampleTissueService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultIdentityService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleAdditionalInfoService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleAnalyteService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleTissueService.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleAdditionalInfoController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleAnalyteController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleTissueController.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/IdentityDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/SampleAdditionalInfoDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/SampleAnalyteDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/SampleTissueDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateIdentityDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleAdditionalInfoDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleAnalyteDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleTissueDao.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateIdentityDaoTest.java
These creates/updates are done through the Sample controller/service/dao
> removed SAI/Identity/Tissue/Analyte create/edit methods

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractLibrary.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/LibraryAdditionalInfo.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/TagBarcode.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/TagBarcodeFamily.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/LibraryAdditionalInfoImpl.java
- core/src/test/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractLibraryTestSuite.java
Adds annotations between Library & LibraryAdditionalInfo, and TagBarcode & TagBarcodeFamily.
> GLT-702 fix recursion

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/MisoRequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/RequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/UserAuthMisoRequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/PoolStore.java
- miso-web/src/main/webapp/pages/mainMenu.jsp
- miso-web/src/main/webapp/scripts/search.js
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/DashboardHelperService.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLLibraryDilutionDAO.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLPoolDAO.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLPoolDAOTest.java
Hmm, I wrote methods in this one that are instantly deprecated.  We should probably discuss that!
> Add pool search to home page.

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/naming/OicrSampleAliasGenerator.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/LimsUtils.java
- core/src/test/java/uk/ac/bbsrc/tgac/miso/core/service/naming/OicrSampleAliasGeneratorTest.java
Changes made in advance of moving fields. Should not disrupt current name generation
> updated OICR sample alias generation

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/DetailedSampleBuilder.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
- miso-web/src/main/webapp/pages/editSample.jsp
- miso-web/src/main/webapp/scripts/sample_ajax.js
Creating analyte stock on create single sample page will work again. Bulk page will be fixed in GLT-767
> updated Edit Sample (single) for required tissue in hierarchy

- sqlstore/src/main/resources/db/migration/afterMigrate.sql
> GLT-783 RunPartitionsByHealth was failing

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/LibraryAdditionalInfo.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SampleAdditionalInfo.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SampleTissue.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/DetailedSampleBuilder.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/LibraryAdditionalInfoImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleAdditionalInfoImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleTissueImpl.java
- migration/src/main/java/uk/ac/bbsrc/tgac/miso/migration/destination/MisoServiceManager.java
- migration/src/main/java/uk/ac/bbsrc/tgac/miso/migration/source/LoadGeneratorSource.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleAdditionalInfoDto.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleAnalyteDto.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleIdentityDto.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleTissueDto.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryAdditionalInfoService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleAdditionalInfoService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleTissueService.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java
- miso-web/src/main/webapp/pages/editSample.jsp
- sqlstore/src/main/resources/db/migration/V0028__model_refactor.sql
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryAdditionalInfoDaoTest.java
- sqlstore/src/test/resources/db/test_migration/V9000__miso_test_data.test.sql
Fields moved:
* timesReceived
* tubeNumber
* passageNumber
* tissueOrigin
* tissueType
* externalInstituteIdentifier
* lab
> moved some sampleAdditionalInfo fields to sampleTissue

- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
- miso-web/src/main/webapp/pages/editSample.jsp
- miso-web/src/main/webapp/scripts/sample_ajax.js
- miso-web/src/main/webapp/scripts/sample_hot.js
List Samples
* removed Tissue classes from child class options for propagation
Edit Sample (single)
* volume is no longer a required field
Edit Sample (detailed)
* fixed Sample JSON serialisation, so groupId is no longer set to 0 when it should be null
* set STR Status default to 'Not Submitted' instead of null (invalid)
* removed receivedDate field when propagating
* removed hardcoded EST timezone from receivedDate
Misc
* removed some javascript that seemed to be setting default scientificName and sampleClassId, but that was actually doing nothing while the defaults were set elsewhere
> misc sample form adjustments

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/type/PlatformType.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/MisoRequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/RequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/UserAuthMisoRequestManager.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditPoolController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditRunController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/ListPoolsController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/PoolWizardController.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/ContainerControllerHelperService.java
See https://jira.oicr.on.ca/browse/GLT-672 for screenshots of cases in the UI where the platforms displayed were filtered.
> GLT-672 Only display platforms that have associated sequencers

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractSequencerPartitionContainer.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SequencerPartitionContainer.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/MisoRequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/RequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/UserAuthMisoRequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/SequencerPartitionContainerStore.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/ContainerDto.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/ContainerRestController.java
- miso-web/src/main/webapp/scripts/sequencer_partition_container_ajax.js
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/ContainerControllerHelperService.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLRunDAO.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLSequencerPartitionContainerDAO.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLSequencerPartitionContainerDAOTest.java
- sqlstore/src/test/resources/db/test_migration/V9000__miso_test_data.test.sql
> GLT-818 Paginate List Partition Containers page

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractPool.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Boxable.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/BoxUtils.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/DilutionDto.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/LibraryDto.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/PoolDto.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleDto.java
- miso-web/src/main/webapp/pages/editSample.jsp
- miso-web/src/main/webapp/pages/listPlates.jsp
- miso-web/src/main/webapp/pages/listPoolOrders.jsp
- miso-web/src/main/webapp/pages/listTagBarcodes.jsp
- miso-web/src/main/webapp/scripts/box_ajax.js
- miso-web/src/main/webapp/scripts/experiment_ajax.js
- miso-web/src/main/webapp/scripts/library_ajax.js
- miso-web/src/main/webapp/scripts/pool_ajax.js
- miso-web/src/main/webapp/scripts/run_ajax.js
- miso-web/src/main/webapp/scripts/sample_ajax.js
- miso-web/src/main/webapp/scripts/sequencer_partition_container_ajax.js
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDao.java
* add location column to Sample, Library and Pool
* fix backwards ordering of pagination buttons
> GLT-248 fix List X pages

- miso-web/src/main/webapp/scripts/library_ajax.js
- miso-web/src/main/webapp/scripts/pool_ajax.js
- miso-web/src/main/webapp/scripts/run_ajax.js
- miso-web/src/main/webapp/scripts/sample_ajax.js
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLLibraryDAO.java
Sorting by name now works as intended.
> GLT-648 Fix DataTables sort by name

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractPool.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Pool.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/PoolDto.java
- miso-web/src/main/webapp/pages/editPool.jsp
- miso-web/src/main/webapp/scripts/pool_ajax.js
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLPoolDAO.java
- sqlstore/src/main/resources/db/migration/V0035__add_description_to_pool.sql
- sqlstore/src/test/resources/db/test_migration/V9000__miso_test_data.test.sql
- hides/shows pooled elements
- shows tagbarcodes on libraries
- adds a `description` field to Pool
> GLT-275 update List Pools page

- miso-web/src/main/webapp/pages/bulkEditLibraries.jsp
- miso-web/src/main/webapp/pages/bulkEditSamples.jsp
- miso-web/src/main/webapp/scripts/handsontable/dist/handsontable.full.js
- miso-web/src/main/webapp/scripts/library_hot.js
- miso-web/src/main/webapp/scripts/sample_hot.js
- no longer jitters and freezes when filling down rows by double-clicking cell corner
- incidentally, supports multi-column fill-down
- no longer adds new rows when user drags down
> GLT-994 improve UX for Handsontable bulk entry

- miso-web/src/main/webapp/scripts/pool_ajax.js
Get the correct library id in the URL. Also, rename the collection so the
function doesn't have a variable with the same name in it.
> Fix incorrect library URL and confusing name

- miso-web/pom.xml
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/context/MisoAppListener.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/context/PrometheusCollectionFilter.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/context/PrometheusInterceptor.java
- miso-web/src/main/webapp/WEB-INF/event-config.xml
- miso-web/src/main/webapp/WEB-INF/web.xml
Exports per URL stats and per DAO method stats via `/metrics` for Prometheus to scrape.
> Prometheus monitoring

- miso-web/src/main/webapp/scripts/library_ajax.js
- miso-web/src/main/webapp/scripts/lims.js
- miso-web/src/main/webapp/scripts/pool_ajax.js
- miso-web/src/main/webapp/scripts/run_ajax.js
- miso-web/src/main/webapp/scripts/sample_ajax.js
- miso-web/src/main/webapp/scripts/scriptaculous/prototype.js
Particularly, the ones that have callbacks
> Remove columns that aren't helpful

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/type/PlatformType.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/MisoRequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/RequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/UserAuthMisoRequestManager.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/DilutionDto.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditProjectController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/LibraryDilutionRestController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/LibraryRestController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/RunRestController.java
- miso-web/src/main/resources/sql/db-config.xml
- miso-web/src/main/webapp/pages/bulkEditDilutions.jsp
- miso-web/src/main/webapp/pages/bulkEditSamples.jsp
- miso-web/src/main/webapp/scripts/dilution_hot.js
- miso-web/src/main/webapp/scripts/library_ajax.js
- miso-web/src/main/webapp/scripts/library_hot.js
- miso-web/src/main/webapp/scripts/sample_hot.js
- miso-web/src/main/webapp/scripts/shared_hot.js
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/LibraryControllerHelperService.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLLibraryDilutionDAO.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLPoolDAO.java
- also GLT-1002 fix library save
- speeds up edit project load time
- fixed up the platform emPCR check (H/T @apmasell )
> GLT-773 bulk create library dilutions

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
- miso-web/src/main/webapp/pages/bulkEditLibraries.jsp
- miso-web/src/main/webapp/scripts/library_hot.js
- miso-web/src/main/webapp/scripts/sample_hot.js
- miso-web/src/main/webapp/scripts/shared_hot.js
Still somewhat slow after Platform Name autofill, but at least it all works.
> GLT-1011 Handsontable correct sources after autofill

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/LibraryAdditionalInfo.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SampleAdditionalInfo.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/DetailedSampleBuilder.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/LibraryAdditionalInfoImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleAdditionalInfoImpl.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/LibraryAdditionalInfoDto.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleAdditionalInfoDto.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryAdditionalInfoService.java
- miso-web/src/main/webapp/pages/editLibrary.jsp
- miso-web/src/main/webapp/scripts/sample_ajax.js
- miso-web/src/main/webapp/scripts/sample_hot.js
- sqlstore/src/main/resources/db/migration/V8018__alphanumeric_group_IDs.sql
- sqlstore/src/main/resources/db/migration/afterMigrate.sql
- also removes Group IDs from LibraryAdditionalInfo
> GLT-982 allow alphanumeric group IDs

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/LibraryAdditionalInfo.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SampleAdditionalInfo.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/DetailedSampleBuilder.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/LibraryAdditionalInfoImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleAdditionalInfoImpl.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/LibraryAdditionalInfoDto.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleAdditionalInfoDto.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
- miso-web/src/main/webapp/pages/bulkEditLibraries.jsp
- miso-web/src/main/webapp/pages/bulkEditSamples.jsp
- miso-web/src/main/webapp/pages/editLibrary.jsp
- miso-web/src/main/webapp/pages/editSample.jsp
- miso-web/src/main/webapp/scripts/library_hot.js
- miso-web/src/main/webapp/scripts/sample_ajax.js
- miso-web/src/main/webapp/scripts/sample_hot.js
- miso-web/src/main/webapp/scripts/shared_hot.js
- miso-web/src/main/webapp/styles/style.css
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLLibraryDAO.java
- sqlstore/src/main/resources/db/migration/V8019__nonstandard_alias.sql
Legacy malformed aliases will need to be maintained, so they and their children can't be run through the alias validators during save.
> GLT-1005 Handle non-standard aliases

- miso-web/src/main/webapp/scripts/library_hot.js
Handsontable no longer completely obliterates values after paste. Also, improved TagBarcode validators.
> GLT-1053 don't obliterate values on paste

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Platform.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SequencingContainer.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SequencerPartitionContainerImpl.java
- docs/_posts/2016-01-12-user-manual.md
- docs/_site/usr/user-manual.html
- migration/src/main/java/uk/ac/bbsrc/tgac/miso/migration/source/LoadGeneratorSource.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/context/MisoAppListener.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/ListSequencerPartitionContainerController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/RunRestController.java
- miso-web/src/main/webapp/pages/adminsub.jsp
- miso-web/src/main/webapp/pages/editSequencerPartitionContainer.jsp
- miso-web/src/main/webapp/pages/listSequencerPartitionContainers.jsp
- miso-web/src/main/webapp/scripts/sequencer_partition_container_ajax.js
- notification-consumer-services/src/main/java/uk/ac/bbsrc/tgac/miso/notification/consumer/service/mechanism/IlluminaNotificationMessageConsumerMechanism.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/ContainerControllerHelperService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/SubmissionControllerHelperService.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLSequencerPartitionContainerDAO.java
Removes all instances of it from the user's view.
> GLT-1064 replace Partition Container on front end

- miso-web/src/main/webapp/pages/editSample.jsp
- miso-web/src/main/webapp/scripts/sample_hot.js
- miso-web/src/main/webapp/scripts/shared_hot.js
Fields now have labels and samples can be batch entered without having to refresh the page.
> GLT-1041 Improve UI for bulk create samples

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SequencerPartitionContainer.java
> fix the build

- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/SampleControllerHelperService.java
> Revert "GLT-1071 Display error message for duplicate barcode."

- miso-web/src/main/webapp/scripts/library_hot.js
Library Kits have names, not aliases.
> GLT-1087 show kit on library dropdown

- compact-migrations
The URL it was detecting was specific to SSH. This URL detection will match both
> Allow compact-migrations to work with HTTP

- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/LibraryControllerHelperService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/PoolControllerHelperService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/SampleControllerHelperService.java
Checking barcode across Samples, Libraries and Pools to ensure uniqueness.
> GLT-1071 Improved improvement to ensure barcode uniqueness

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/UserAuthMisoRequestManager.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditServiceRecordController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/ViewSequencerReferenceController.java
- miso-web/src/main/webapp/pages/editSequencerReference.jsp
- miso-web/src/main/webapp/pages/editServiceRecord.jsp
Reverts TGAC/miso-lims#406 : Reverting to add JSP changes too
> Revert "GLT-1091 make service records CRUDable by all"

- miso-web/src/main/webapp/pages/editSequencerReference.jsp
- miso-web/src/main/webapp/pages/editServiceRecord.jsp
> GLT-1091 create and edit service records for all internal

- miso-web/src/main/webapp/pages/editBox.jsp
- miso-web/src/main/webapp/scripts/box_ajax.js
So you can scan the barcode, hit enter, and select your next box position.
> GLT-1120 shift focus after barcode lookup

- miso-web/src/main/webapp/scripts/dilution_hot.js
- miso-web/src/main/webapp/scripts/handsontable/dist/handsontable.full.css
- miso-web/src/main/webapp/scripts/library_hot.js
- miso-web/src/main/webapp/scripts/sample_hot.js
- miso-web/src/main/webapp/scripts/shared_hot.js
- increases arrow contrast in autocomplete cells
- visually highlights required cells
- thoughts on colour scheme? Light orange is already used for nonstandard aliases
- fixes error where second index is marked as required for dual index families
> GLT-1112 & GLT-1113 HoT UI update

- sqlstore/src/main/resources/db/migration/V8088__small_changes.sql
- add `PacBio RS II` platform
- update Nextera indices
> GLT-1133 & GLT-1142

- miso-web/src/main/webapp/pages/editLibrary.jsp
- miso-web/src/main/webapp/scripts/library_hot.js
(editLibrary.jsp: adds in one missing `}` and some formatting changes)
> GLT-1145 fix bulk create libs datatables & lib nonstandard alias

- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLLibraryDAO.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLLibraryDilutionDAO.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLPlateDAO.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLPoolDAO.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLProjectDAO.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLRunDAO.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLSequencerPartitionContainerDAO.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLStudyDAO.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/util/DbUtils.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLRunDAOTest.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLStudyDAOTest.java
> Make all search boxes trim spaces and ignore case

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractSequencerPartitionContainer.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/ContainerDto.java
- miso-web/src/main/webapp/pages/editRun.jsp
- miso-web/src/main/webapp/pages/editSequencerPartitionContainer.jsp
- miso-web/src/main/webapp/scripts/run_ajax.js
- miso-web/src/main/webapp/scripts/sequencer_partition_container_ajax.js
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/ContainerControllerHelperService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/RunControllerHelperService.java
The back end (and Java expressions in JSPs) still refer to the property as `identificationBarcode` since the container implements Barcodable.
> GLT-1132 change "ID Barcode" to "Serial Number" on sequencing containers front end

- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLLibraryDilutionDAO.java
Specifically, name, alias, and description.
> Allow searching library dilutions by library properties (GLT-1153)

- miso-web/src/main/webapp/pages/editRun.jsp
- miso-web/src/main/webapp/pages/editSequencerPartitionContainer.jsp
- miso-web/src/main/webapp/scripts/run_ajax.js
- miso-web/src/main/webapp/scripts/sequencer_partition_container_ajax.js
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/ContainerControllerHelperService.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLSequencerPartitionContainerDAO.java
- sqlstore/src/main/resources/db/migration/V8000__container_constraints.sql
added to the database.
- Added Container constraints to db including FK and UNIQUE for the serial
number.
- When deleting a container ensured that the container is unlinked from
other tables before the delete takes place to satisfy the FKs.
- Prevented form buttons from submitting the form. We'll let js
handle that.
- Looked up the container serial number to ensure it's unique. If
not report an error via parsley.
> GLT-1178 Preventing containers with duplicate Serial Numbers from being

- sqlstore/src/main/resources/db/migration/V8200__remove_externalName_unique_constraint.sql
NoTest because I was unable to find syntax to make HQL happy.
> drop unique constraint on external name

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/BoxImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/MisoRequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/RequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/UserAuthMisoRequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/BoxStore.java
- miso-web/src/main/webapp/pages/editLibrary.jsp
- miso-web/src/main/webapp/pages/editPool.jsp
- miso-web/src/main/webapp/pages/editSample.jsp
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLBoxDAO.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLBoxDAOTest.java
- remove unused box methods
- update location of "Location" row and improve pluralization on JSPs for Sample, Library, Pool
> more GLT-1206: remove unused box methods; update UI in JSPs

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SamplePurpose.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/TissueMaterial.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/IdentityImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SamplePurposeImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/TissueMaterialImpl.java
- core/src/test/java/uk/ac/bbsrc/tgac/miso/core/data/IdentityBuilderTest.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SamplePurposeDto.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/TissueMaterialDto.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSamplePurposeService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultTissueMaterialService.java
- miso-web/src/main/webapp/pages/editExperiment.jsp
- miso-web/src/main/webapp/pages/editLibrary.jsp
- miso-web/src/main/webapp/pages/editRun.jsp
- miso-web/src/main/webapp/pages/editSample.jsp
- miso-web/src/main/webapp/pages/instituteDefaults.jsp
- miso-web/src/main/webapp/scripts/experiment_ajax.js
- miso-web/src/main/webapp/scripts/instituteDefaults_ajax.js
- miso-web/src/main/webapp/scripts/library_ajax.js
- miso-web/src/main/webapp/scripts/library_hot.js
- miso-web/src/main/webapp/scripts/pool_ajax.js
- miso-web/src/main/webapp/scripts/run_ajax.js
- miso-web/src/main/webapp/scripts/sample_ajax.js
- miso-web/src/main/webapp/scripts/sample_hot.js
- miso-web/src/main/webapp/scripts/study_ajax.js
- sqlstore/src/main/resources/db/migration/V8510__nullable_descriptions.sql
* Removed description field from
* SamplePurpose
* TissueMaterial
* Made description nullable for
* Sample
* Library
* Pool
* Run
* Experiment
* Platform
* Subproject
* Study
* Made Run alias NOT nullable
> GLT-1021: description field modifications

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditPoolController.java
@callunity tested this and it behaves as requested.
> Order library dilutions by id rather than name

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java
- miso-web/src/main/webapp/pages/editLibrary.jsp
A quick test and this seems to work good.
Unless @apmasell has other plans?
> Pull bulk library creation tab back in.

- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/ProjectControllerHelperService.java
Remove plate reference from PoolControllerHelperService.generateSampleDeliveryForm.
> Fix no plate in JSON

- migration/src/main/java/uk/ac/bbsrc/tgac/miso/migration/Migration.java
Currently exits with 0's when migration fails.
> Exits migration with errorful exit codes on exception

- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLSequencerPoolPartitionDAO.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/AllTestsSuite.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLSequencerPoolPartitionDAOTest.java
- sqlstore/src/test/resources/db/test_migration/V9000__miso_test_data.test.sql
> Add tests for SequencerPoolPartitionDAO

- miso-web/src/main/webapp/pages/editSample.jsp
> Add edit sample breadcrumbs back in.

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/ListPoolsController.java
display all platformTypes if no squencers are present in db (friendlier for new people trying out MISO)
> GLT-1331 always display some platform tabs in Pools page

- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/PoolSearchService.java
> Attempt to avoid NPE that shouldn't exist

- Dockerfile
- docs/_posts/2016-01-11-admin-manual.md
Added notes how to build the Dockerfile into the admin manual.
> Move the Dockerfile into the main repository

- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/AllTestsSuite.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLWatcherDAOTest.java
> Add tests for SQLWatcherDAO

- docs/_posts/2016-01-11-admin-manual.md
- docs/_site/adm/admin-manual.html
This PR is only for the commit marked GLT-1266. Others are included in PR #580
> Glt 1266 docs

- migration/src/main/java/uk/ac/bbsrc/tgac/miso/migration/destination/MisoServiceManager.java
- sqlstore/src/main/resources/db/migration/V8000__hibernate.sql
- sqlstore/src/main/resources/db/migration/V8900__hibernatize_everything.sql
> fixup for Hibernate branch

- sqlstore/src/main/resources/db/migration/afterMigrate.sql
These procedures will be added to production and run before the next release.
> Create procedures to delete sample or library

- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/FlexReportingControllerHelperService.java
> Fix NPE when library description is null

- miso-web/src/main/webapp/pages/editLibrary.jsp
If a user has permissions enough to view the library, they should be able to edit the dilution too (write check against the dilution's security profile will happen at the service level)
> GLT-1396 allow library editor to edit dilutions

- core/src/main/java/com/eaglegenomics/simlims/core/Note.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractLibrary.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractRun.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractSample.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/KitImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/PoolImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/ProjectOverview.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/MisoRequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/RequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/UserAuthMisoRequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/PoolStore.java
- core/src/test/java/uk/ac/bbsrc/tgac/miso/core/manager/UserAuthMisoRequestManagerTestSuite.java
- migration/src/main/java/uk/ac/bbsrc/tgac/miso/migration/destination/MisoServiceManager.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/RunControllerHelperService.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolDao.java
- sqlstore/src/main/resources/db/migration/V8900__hibernatize_everything.sql
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolDaoTest.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLPoolQCDAOTest.java
- sqlstore/src/test/resources/db/test_migration/V9000__miso_test_data.test.sql
This fixes most of the pool and pool QC tests and changes notes across all the users.
> Pool tests

- pom.xml
- spring/.settings/org.eclipse.core.resources.prefs
- sqlstore/pom.xml
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLStatusDAOTest.java
- sqlstore/src/test/resources/db-test-context.xml
* fixed test
* updated surefire plugin version
* disabled hibernate walloftext mode during tests
> fixed test, updated surefire plugin

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/MisoRequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/UserAuthMisoRequestManager.java
Didn't touch kit-related methods as they are covered by PR #662
> GLT-1482: temp fixes for Note-related things in RequestManager

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/naming/DefaultMisoEntityPrefix.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/naming/generation/DefaultNameGenerator.java
Sample save+load via the UI works after this change
> GLT-1490: fixed DefaultNameGenerator

- sqlstore/src/main/resources/db/migration/afterMigrate.sql
After approval, I will drop and recreate the one affected trigger on stage, verify that it works, and then do the same on production
> fixed bad trigger

- sqlstore/pom.xml
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/db/migration/V0168__StatusXmlToRunTable.java
Configure flyway to run Java migrations as well as SQL migrations.
> GLT-1518 Copy values from Status table xml to new fields in the Run table.

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/PoolOrderCompletion.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/LimsUtils.java
- miso-web/src/main/webapp/WEB-INF/db-config.xml
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolOrderCompletionDao.java
- sqlstore/src/test/resources/db-test-context.xml
They id keys were wrong in Hibernate and it was throwing away data
JIRA: GLT-1522
> Fix bug causing pool order completions to be incorrect

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/MisoRequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/RequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/UserAuthMisoRequestManager.java
- core/src/test/java/uk/ac/bbsrc/tgac/miso/core/manager/UserAuthMisoRequestManagerTest.java
- migration/src/main/java/uk/ac/bbsrc/tgac/miso/migration/destination/DefaultMigrationTarget.java
- migration/src/main/java/uk/ac/bbsrc/tgac/miso/migration/destination/MisoServiceManager.java
- migration/src/main/java/uk/ac/bbsrc/tgac/miso/migration/destination/ValueTypeLookup.java
- migration/src/test/resources/test-utils.sql
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/BoxControllerHelperService.java
also contains a couple post-Hibernatization bug-fixes
> GLT-1510: migrate pool data, merge duplicate pools

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Partition.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SequencerPartitionContainer.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/PartitionImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SequencerPartitionContainerImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/UserAuthMisoRequestManager.java
- core/src/test/java/uk/ac/bbsrc/tgac/miso/core/manager/UserAuthMisoRequestManagerTest.java
- notification-consumer-services/src/main/java/uk/ac/bbsrc/tgac/miso/notification/consumer/service/mechanism/IlluminaNotificationMessageConsumerMechanism.java
- notification-consumer-services/src/main/java/uk/ac/bbsrc/tgac/miso/notification/consumer/service/mechanism/LS454NotificationMessageConsumerMechanism.java
- notification-consumer-services/src/main/java/uk/ac/bbsrc/tgac/miso/notification/consumer/service/mechanism/PacBioNotificationMessageConsumerMechanism.java
- notification-consumer-services/src/main/java/uk/ac/bbsrc/tgac/miso/notification/consumer/service/mechanism/SolidNotificationMessageConsumerMechanism.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/ContainerControllerHelperService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/RunControllerHelperService.java
- sqlstore/src/main/resources/db/migration/V8500__drop_partition_securityProfile.sql
- sqlstore/src/test/resources/db/test_migration/V9000__miso_test_data.test.sql
Also
* fixes errors occurring when trying to save a new container
* removed SecurityProfiles from partitions (they were never set separately from the container)
> GLT-1184: fix partition numbers and ordering

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/TargetedSequencing.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/kit/KitDescriptor.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/LibraryControllerHelperService.java
- sqlstore/src/main/resources/db/migration/V8000__ts_many_to_many.sql
- sqlstore/src/main/resources/db/migration/beforeMigrate.sql
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/sqlstore/SQLTargetedSequencingDAOTest.java
- sqlstore/src/test/resources/db/test_migration/V9000__miso_test_data.test.sql
prep kits to a many-to-many relationship.
> GLT-1561 Convert relationship between targeted sequencing and library

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Dilution.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/LibraryDilution.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryDilutionService.java
- sqlstore/src/main/resources/db/migration/V8555__dilution_volume.sql
For migration purposes. Will be added to UI in a separate PR in the future
> GLT-1574: added LibraryDilution.volume field

- miso-web/src/main/webapp/scripts/project_ajax.js
> Fix project name sorting

- notification-server/src/test/java/uk/ac/bbsrc/tgac/miso/notification/util/PossiblyGzippedFileUtilsTest.java
> Allow spaces in class resource paths

- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java
> GLT-1601 fixup: re-allow saving of duplicate alias if non-standard

- miso-web/src/main/webapp/header.jsp
This uses the existing bugUrl property that never went anywhere
JIRA: GLT-1537
> Add a link to file a ticket

- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultExperimentService.java
- miso-service/src/test/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultExperimentServiceTest.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/ExperimentWizardController.java
- miso-web/src/main/webapp/pages/experimentWizard.jsp
- miso-web/src/main/webapp/scripts/experiment_ajax.js
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/ExperimentWizardControllerHelperService.java
> Make Experiment Wizard save correctly

- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java
> Update qcPassed based on detailedQcStatus changes

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/MisoRequestManager.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditRunController.java
- sqlstore/src/main/resources/db/migration_afterMigrate/05_standard.sql
> Update run's changelog when a status is changed

- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSubmissionDao.java
> Add wiring for JdbcTemplate to avoid NPE

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/MisoRequestManager.java
> Allow updating the security profile for a project

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractSequencerServiceRecord.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/BoxDerivedInfo.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/ContainerDerivedInfo.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/InstituteImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/LabImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/LibraryDerivedInfo.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/PoolDerivedInfo.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/PoolOrderImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/ReferenceGenomeImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/RunDerivedInfo.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleDerivedInfo.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleNumberPerProjectImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SamplePurposeImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleValidRelationshipImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SequencerServiceRecordImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SubprojectImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/TissueMaterialImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/TissueOriginImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/TissueTypeImpl.java
- miso-web/src/main/webapp/login.jsp
- miso-web/src/main/webapp/pages/mainMenu.jsp
This is all Heather's code that I've pulled out of a larger set of changes. I approve it.
> Misc fixups

- migration/src/main/java/uk/ac/bbsrc/tgac/miso/migration/destination/ValueTypeLookup.java
Required for https://github.com/oicr-gsi/pinery-miso-migration/pull/157
> adjust TissueOrigin resolve visibility

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/MisoRequestManager.java
> Fix transient object exception when saving new container

- Dockerfile
- miso-web/src/main/webapp/scripts/fluxion-ajax/fluxion-ajax.js
This happens when navigating to a new page.
JIRA: GLT-1620
> Don't display an error if an XHR is aborted prematurely

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/MisoRequestManager.java
- miso-web/src/main/webapp/pages/editSequencerPartitionContainer.jsp
- miso-web/src/main/webapp/scripts/sequencer_partition_container_ajax.js
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/ContainerControllerHelperService.java
The sequencer was only ever used as a proxy for the platform
> Choose platform for container rather than seqencer

- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryService.java
> Fix suprious indices in library change logs

- core/src/main/java/com/eaglegenomics/simlims/core/Note.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractLibrary.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractSample.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/IndexFamily.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/KitImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/LibraryDilution.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/PoolImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/kit/KitDescriptor.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditProjectController.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolDao.java
This greatly improves the loading time of the Edit Project page, but it is still slow. Loading libraries takes the most time
> Hibernate fixups to improve performance

- miso-web/src/main/webapp/WEB-INF/jdbc-security-config.xml
- miso-web/src/main/webapp/WEB-INF/ldap-security-config.xml
Concurrent sessions don't cause problems for MISO and the filter causes NPEs
> Drop concurrency filter from authentication

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleController.java
- miso-web/src/main/webapp/pages/editProject.jsp
- miso-web/src/main/webapp/scripts/project_ajax.js
- miso-web/src/main/webapp/scripts/sample_ajax.js
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/ProjectControllerHelperService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/SampleControllerHelperService.java
> Paginate samples list on edit project page

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Dilution.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/BoxImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/LibraryDilution.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/MisoRequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/RequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/UserAuthMisoRequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/LibraryDilutionStore.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/LibraryStore.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/PoolStore.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/SampleStore.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/BoxControllerHelperService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/LibraryControllerHelperService.java
- spring/src/test/java/uk/ac/bbsrc/tgac/miso/spring/ajax/test/BoxControllerHelperServiceTest.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryDilutionDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDao.java
- sqlstore/src/main/resources/db/migration/V8800__dilution_barcodes.sql
> Make dilutions boxable

- miso-web/src/main/webapp/pages/exportSampleSheet.jsp
This seemed to be missing a few lines of code to be able to function correctly.  I have re-added them.
> fix export functionality

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractLibrary.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Library.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/PartitionImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/PoolImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/PoolQCImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleCVSlideImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/UserImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/LimsUtils.java
- core/src/test/java/uk/ac/bbsrc/tgac/miso/core/service/naming/generation/OicrSampleAliasGeneratorTest.java
- core/src/test/java/uk/ac/bbsrc/tgac/miso/core/util/LimsUtilsTest.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java
> Evade Hibernate proxies when doing heirarchy checks

- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/ProjectDto.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/ProjectRestController.java
- miso-web/src/main/webapp/scripts/instituteDefaults_ajax.js
This is to avoid infinite recursion trying to seralise the project model object.
> Create project DTO

- miso-web/src/main/webapp/scripts/pool_ajax.js
> Indicate when a dilution is being added/removed from a pool

- RELEASE_NOTES.md
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/PoolOrderCompletion.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
> Fix join column mismatch in order completions

- miso-web/src/main/webapp/pages/editPool.jsp
- miso-web/src/main/webapp/scripts/lims.js
- miso-web/src/main/webapp/scripts/pool_ajax.js
- miso-web/src/main/webapp/scripts/project_ajax.js
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/PoolControllerHelperService.java
> Allow bulk addition/deletion of a pool's dilutions

- sqlstore/src/main/resources/db/migration_afterMigrate/05_standard.sql
> Use dilution's own last modifier for change logs

- miso-web/src/main/webapp/scripts/library_ajax.js
- miso-web/src/main/webapp/scripts/lims.js
- miso-web/src/main/webapp/scripts/sample_ajax.js
Available on the pool page as well as on the project sample list.
> GLT-1415 Added multi-select

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/AgoMatcher.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/PaginationFilter.java
> Allow seaches to operate on “ago” ranges

- .travis.yml
Build passing with this yml file: https://travis-ci.org/TGAC/miso-lims
> Added Travisci support

- notification-consumer-services/src/main/java/uk/ac/bbsrc/tgac/miso/notification/consumer/service/mechanism/IlluminaNotificationMessageConsumerMechanism.java
> Ignore unknown health types sent by notification server

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
- miso-web/src/main/webapp/header.jsp
- miso-web/src/main/webapp/pages/editSample.jsp
- miso-web/src/main/webapp/scripts/sample_ajax.js
> Add relations table for samples

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/BoxSize.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/BoxImpl.java
- miso-web/src/main/webapp/scripts/box_ajax.js
- miso-web/src/main/webapp/scripts/box_visualization.js
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/BoxControllerHelperService.java
- spring/src/test/java/uk/ac/bbsrc/tgac/miso/spring/ajax/test/BoxControllerHelperServiceTest.java
> Allow saving a box that has scan errors

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/PoolWizardController.java
- miso-web/src/main/webapp/pages/poolWizard.jsp
> Fix exception on pool wizard page

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleTissueImpl.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java
- miso-web/src/main/webapp/pages/editSample.jsp
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/LimsBindingInitializer.java
- sqlstore/src/main/resources/db/migration/V8803__tissue_nullability.sql
> Force a tissue type and origin, but allow editing

- miso-web/src/main/webapp/scripts/lims.js
> Use mouse events to access shift-key state in multi-selects

- miso-web/src/main/webapp/pages/editRun.jsp
Reverts some changes that weren't quite ready for prime time.
> GLT-1782 fix Interop Metrics display

- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/DetailedSampleDto.java
- miso-web/src/main/webapp/scripts/dilution_hot.js
- miso-web/src/main/webapp/scripts/library_hot.js
- miso-web/src/main/webapp/scripts/lims.js
- miso-web/src/main/webapp/scripts/sample_ajax.js
- miso-web/src/main/webapp/scripts/sample_hot.js
- miso-web/src/main/webapp/scripts/shared_hot.js
Only `<>&` should be always-restricted characters now. Some fields maintain stricter validation of course
> GLT-1751 santization/validation fixes

- miso-web/src/main/webapp/scripts/library_ajax.js
- miso-web/src/main/webapp/scripts/pool_ajax.js
- miso-web/src/main/webapp/scripts/project_ajax.js
- miso-web/src/main/webapp/scripts/run_ajax.js
- miso-web/src/main/webapp/scripts/sample_ajax.js
- autofocus on input when dialog opens
- don't save if note is empty
> Improve notes GUI

- miso-web/src/main/webapp/scripts/run_ajax.js
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRunDao.java
> Sort Runs by Start Date

- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java
- sqlstore/src/main/resources/db/migration/V8801__fix_detailed_qc.sql
> Set sample QC passed for new detailed samples

- sqlstore/src/main/resources/db/migration_afterMigrate/05_standard.sql
> Fix aggregation of order completions to not include update time

- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultKitService.java
> Set lastModifier on KitDescriptor before save

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SampleSlide.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Stain.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/StainCategory.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/DetailedSampleBuilder.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleSlideImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/naming/validation/OicrSampleAliasValidator.java
- core/src/test/java/uk/ac/bbsrc/tgac/miso/core/util/LimsUtilsTest.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleDto.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleSlideDto.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/StainDto.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/StainService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultStainService.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/MenuController.java
- miso-web/src/main/webapp/pages/editSample.jsp
- miso-web/src/main/webapp/scripts/sample_ajax.js
- miso-web/src/main/webapp/scripts/sample_hot.js
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/LimsBindingInitializer.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/StainDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateStainDao.java
- sqlstore/src/main/resources/db/migration/V8805__merge_slides.sql
- sqlstore/src/main/resources/db/migration_afterMigrate/05_standard.sql
- sqlstore/src/test/resources/db/test_migration/V9000__miso_test_data.test.sql
> Unify all CV and HE slides into a single class

- miso-web/src/main/webapp/pages/editBox.jsp
- miso-web/src/main/webapp/scripts/box_ajax.js
- miso-web/src/main/webapp/scripts/box_visualization.js
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/BoxControllerHelperService.java
> Allow filling a box by user-defined barcodes

- miso-web/src/main/webapp/pages/editRun.jsp
- miso-web/src/main/webapp/scripts/run_ajax.js
> Allow adjusting run dates if admin or new run

- miso-web/src/main/webapp/pages/editSample.jsp
- miso-web/src/main/webapp/scripts/sample_ajax.js
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/LibraryControllerHelperService.java
> Remove broken bulk dilution table

- miso-web/src/main/webapp/scripts/hot.js
- miso-web/src/main/webapp/scripts/hot_library.js
> Create function for Boolean HoT columns

- docs/_posts/2016-01-11-admin-manual.md
* Update Flyway classpath
* Fix table formatting
> Update admin documentation

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/MenuController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/UploadController.java
- miso-web/src/main/webapp/pages/editPool.jsp
- miso-web/src/main/webapp/pages/editProject.jsp
- miso-web/src/main/webapp/scripts/pool_ajax.js
> Use platform-specific term for partitions on Pool page; hide project files by default

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractBox.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractLibrary.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractSample.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Library.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Pool.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Run.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/PoolImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SequencerPartitionContainerImpl.java
- migration/src/main/java/uk/ac/bbsrc/tgac/miso/migration/destination/DefaultMigrationTarget.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/ContainerRestController.java
- miso-web/src/main/webapp/pages/editRun.jsp
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/ContainerControllerHelperService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/ImportExportControllerHelperService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/LibraryControllerHelperService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/PoolSearchService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/PoolWizardControllerHelperService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/RunControllerHelperService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/util/FormUtils.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateBoxDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRunDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSequencerPartitionContainerDao.java
- sqlstore/src/main/resources/db/migration/V8501__derivedInfo_removal.sql
- sqlstore/src/test/resources/db/test_migration/V9000__miso_test_data.test.sql
Fixed field names and un-removed Library and Pool creationDate
* creationDate = user-specified
* creationTime = generated save time
> GLT-1845: fixed creationDate/creationTime fields

- .travis.yml
* removing SonarQube because it's failing consistently
* only clone the last 3 git commits
* cache m2 dependencies
* adding sudo: required because Travis needs it now
* setting M2_OPTs to increase available memory for Maven https://stackoverflow.com/questions/29201549/travis-ci-ignoring-maven-opts
> Pulling useful things into the .travis.yml file

- miso-web/src/main/webapp/scripts/hot.js
> Fix duplicated save in Handsontables

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Pool.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/PoolImpl.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/PoolDto.java
- miso-web/src/main/webapp/scripts/list_completions.js
> Show longest index on completions page

- miso-web/src/main/webapp/pages/editPool.jsp
- miso-web/src/main/webapp/scripts/list_completions.js
> Add pool description to orders page

- miso-web/src/main/webapp/scripts/hot_library.js
> Add library name column

- miso-web/src/main/webapp/scripts/list.js
> Show count of selected items

- miso-web/src/main/webapp/scripts/library_ajax.js
> Fix indices list for single library

- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultBoxService.java
- miso-web/src/main/webapp/pages/editBox.jsp
- miso-web/src/main/webapp/scripts/box_ajax.js
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/BoxControllerHelperService.java
> Allow box location change

- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java
- miso-web/src/main/webapp/scripts/hot_sample.js
> bulk identity edit fixes

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
- miso-web/src/main/webapp/scripts/hot_sample.js
> fix identity lookup for samples from Edit Project page

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
- miso-web/src/main/webapp/scripts/hot_sample.js
> Always show sample received date

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/MisoRequestManager.java
> Fix save new runs via notification server bug

- miso-web/src/main/webapp/scripts/hot_sample.js
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDao.java
> Correctly filter by external name and project

- miso-web/src/main/webapp/scripts/list.js
> Fix of-by-one error in multiselect

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/ListCompletionsController.java
> Change 'Active' tab header to 'All' for List Orders page

- miso-web/src/main/webapp/scripts/list_completions.js
> Don't hide sortable columns

- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryDao.java
> Fix sorting by sample alias on library page

- .travis.yml
added an if statement to turn off sonar for forks
> Turning off Sonar for forks

- miso-web/src/main/webapp/scripts/list.js
And increase the search time delay
JIRA: GC-1166
> Disable filter box when search is in progress

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/MisoRequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/RequestManager.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/manager/UserAuthMisoRequestManager.java
- core/src/test/java/uk/ac/bbsrc/tgac/miso/core/manager/UserAuthMisoRequestManagerTest.java
- migration/src/main/java/uk/ac/bbsrc/tgac/miso/migration/destination/DefaultMigrationTarget.java
- notification-consumer-services/pom.xml
- notification-consumer-services/src/main/java/uk/ac/bbsrc/tgac/miso/notification/consumer/service/mechanism/IlluminaNotificationMessageConsumerMechanism.java
- notification-consumer-services/src/main/java/uk/ac/bbsrc/tgac/miso/notification/consumer/service/mechanism/LS454NotificationMessageConsumerMechanism.java
- notification-consumer-services/src/main/java/uk/ac/bbsrc/tgac/miso/notification/consumer/service/mechanism/PacBioNotificationMessageConsumerMechanism.java
- notification-consumer-services/src/main/java/uk/ac/bbsrc/tgac/miso/notification/consumer/service/mechanism/SolidNotificationMessageConsumerMechanism.java
- notification-consumer-services/src/main/java/uk/ac/bbsrc/tgac/miso/notification/consumer/service/strategy/IlluminaNotificationConsumerStrategy.java
- notification-consumer-services/src/main/java/uk/ac/bbsrc/tgac/miso/notification/consumer/service/strategy/LS454NotificationConsumerStrategy.java
- notification-consumer-services/src/main/java/uk/ac/bbsrc/tgac/miso/notification/consumer/service/strategy/PacBioNotificationConsumerStrategy.java
- notification-consumer-services/src/main/java/uk/ac/bbsrc/tgac/miso/notification/consumer/service/strategy/SolidNotificationConsumerStrategy.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/StatsControllerHelperService.java
Now with less Request Manager!
> GLT-1979: fix bulk saving runs from notification server

- core/src/test/java/uk/ac/bbsrc/tgac/miso/core/util/LimsUtilsTest.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
- miso-web/src/main/webapp/pages/editSample.jsp
- miso-web/src/main/webapp/scripts/hot_sample.js
- miso-web/src/main/webapp/scripts/sample_ajax.js
GLT-1945
I propose we hotfix this into OICR production once approved.
> Fix stacktrace on receive slide

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Aliasable.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Pool.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/AliasComparator.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/AlphanumericComparator.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditPoolController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/util/BulkEditTableBackend.java
> Enforce ordering in Handsontables

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/PacBioRun.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/LimsUtils.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/WhineyFunction.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/NotificationDto.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/PacBioNotificationDto.java
- miso-dto/src/test/java/uk/ac/bbsrc/tgac/miso/dto/IlluminaNotificationDtoTest.java
- miso-dto/src/test/java/uk/ac/bbsrc/tgac/miso/dto/PacBioNotificationDtoTest.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultRunService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/RunService.java
- miso-web/src/it/resources/tomcat-config/miso.it.properties
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditRunController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/service/RunScannerClient.java
- miso-web/src/main/resources/external/miso.properties
- miso-web/src/main/resources/internal/miso.properties
- miso-web/src/main/webapp/pages/editRun.jsp
- miso-web/src/main/webapp/scripts/run_ajax.js
- miso-web/src/main/webapp/scripts/run_graph.js
- runscanner/README.md
- runscanner/src/main/java/uk/ac/bbsrc/tgac/miso/runscanner/Main.java
- runscanner/src/main/java/uk/ac/bbsrc/tgac/miso/runscanner/RestController.java
- runscanner/src/main/java/uk/ac/bbsrc/tgac/miso/runscanner/RunProcessor.java
- runscanner/src/main/java/uk/ac/bbsrc/tgac/miso/runscanner/Scheduler.java
- runscanner/src/main/java/uk/ac/bbsrc/tgac/miso/runscanner/UserInterfaceController.java
- runscanner/src/main/java/uk/ac/bbsrc/tgac/miso/runscanner/processors/PacBioProcessor.java
- runscanner/src/main/java/uk/ac/bbsrc/tgac/miso/runscanner/processors/StandardIllumina.java
- runscanner/src/main/java/uk/ac/bbsrc/tgac/miso/runscanner/processors/Testing.java
- sqlstore/src/main/resources/db/migration/V8806__pacbio.sql
> Add PacBio support to Run Scanner

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SampleClass.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/AbstractIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/SampleBulkCreateIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/AbstractPage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/BulkSamplePage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/SamplePage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/element/AbstractElement.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/element/HandsOnTable.java
- miso-web/src/it/resources/db/migration/V9000__integration-test_data.test.sql
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
- miso-web/src/main/webapp/pages/editSample.jsp
- miso-web/src/main/webapp/pages/handsontables.jsp
- miso-web/src/main/webapp/scripts/hot.js
- miso-web/src/main/webapp/scripts/hot_sample.js
- miso-web/src/main/webapp/scripts/list.js
> Integration tests for bulk create samples

- sqlstore/src/main/resources/db/migration_afterMigrate/05_standard.sql
Companion to changes made in this file: https://github.com/TGAC/miso-lims/blob/develop/sqlstore/src/main/resources/db/migration/V8806__pacbio.sql
> fix trigger

- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultRunService.java
- miso-web/src/main/webapp/pages/editRun.jsp
- miso-web/src/main/webapp/scripts/run_graph.js
- runscanner-illumina/README.md
- runscanner-illumina/main.cpp
> Add graphs and summary information for Illumina runs

- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BoxPageIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/AbstractPage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/BoxPage.java
- miso-web/src/it/resources/db/migration/V9000__integration-test_data.test.sql
- miso-web/src/main/webapp/pages/editBox.jsp
> Integration UI tests for Edit Box

- miso-web/src/main/webapp/scripts/list.js
- miso-web/src/main/webapp/scripts/list_container.js
Instead of "RUNnull" and "null"
GLT-1904
> Show empty cells on Containers page when no last run present

- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/SampleBulkCreateIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/element/HandsOnTable.java
- miso-web/src/it/resources/db/migration/V9000__integration-test_data.test.sql
Also works around Chromedriver bug entering digits by avoiding character '2' (this and other characters may still cause issue if not avoided)
> fix selecting locked HOT cells

- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkLibraryIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ErrorCrawlerIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/AbstractPage.java
- miso-web/src/it/resources/db/migration/V9000__integration-test_data.test.sql
> Crawl for errors

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/IonTorrentRun.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/HomePageIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ProjectPageIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/AbstractPage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/BulkDilutionPage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/BulkLibraryPage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/ProjectPage.java
- miso-web/src/it/resources/db/migration/V9000__integration-test_data.test.sql
- miso-web/src/main/webapp/pages/editProject.jsp
> Test creating & editing projects

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditRunController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/util/JsonArrayCollector.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/util/RunMetricsSource.java
- miso-web/src/main/webapp/pages/editRun.jsp
- miso-web/src/main/webapp/scripts/run_graph.js
> Make a pluggable metrics mechanism

- miso-web/src/main/webapp/scripts/run_graph.js
- runscanner-illumina/main.cpp
> Add yield bar graph

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/BoxUtils.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/DetailedLibraryDto.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkLibraryIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/BulkLibraryPage.java
- miso-web/src/it/resources/db/migration/V9000__integration-test_data.test.sql
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java
- miso-web/src/main/webapp/scripts/hot.js
- miso-web/src/main/webapp/scripts/hot_dilution.js
- miso-web/src/main/webapp/scripts/hot_library.js
- miso-web/src/main/webapp/scripts/hot_pool.js
- miso-web/src/main/webapp/scripts/hot_sample.js
- miso-web/src/main/webapp/scripts/lims.js
- miso-web/src/main/webapp/scripts/list_samples.js
> make sample box location sortable for bulk libraries

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditRunController.java
- miso-web/src/main/webapp/scripts/run_graph.js
These are some small changes from the STATDB changes that are useful whatever becomes of it.
> Runscanner useful stats bits

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/view/BoxableView.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/BoxableDto.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-web/src/main/webapp/pages/editBox.jsp
- miso-web/src/main/webapp/scripts/box_ajax.js
- sqlstore/src/main/resources/db/migration_afterMigrate/05_standard.sql
> Add bulk actions to box

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/LibraryStore.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/RunStore.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/SampleStore.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/LibraryService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/SampleService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultRunService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/RunService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/DashboardHelperService.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRunDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDao.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryDaoTest.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRunDaoTest.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDaoTest.java
> order runs in home page widget by start date

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Pool.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/PoolImpl.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/PoolDto.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditPoolController.java
- miso-web/src/main/webapp/pages/editPool.jsp
- miso-web/src/main/webapp/scripts/list_pool.js
- miso-web/src/main/webapp/scripts/list_poolelements.js
> better indicators for duplicate indices

- sqlstore/src/main/resources/db/migration_afterMigrate/05_standard.sql
So it doesn't changelog every cycle
> shorten Illumina run changelog trigger

- miso-web/src/main/webapp/pages/editSequencerPartitionContainer.jsp
- miso-web/src/main/webapp/scripts/sequencer_partition_container_ajax.js
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/ContainerControllerHelperService.java
> Remove container delete button

- runscanner/src/main/java/uk/ac/bbsrc/tgac/miso/runscanner/Scheduler.java
Just in case it was a transient failure
> Retry failed directories every so often

- core/.settings/org.eclipse.core.resources.prefs
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/view/PoolableElementView.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/DilutionDto.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkDilutionIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/AbstractListPage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/BulkDilutionPage.java
- miso-web/src/main/webapp/scripts/hot_dilution.js
- miso-web/src/main/webapp/scripts/list_dilution.js
- runscanner/.settings/org.eclipse.core.resources.prefs
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolableElementViewDao.java
- sqlstore/src/main/resources/db/migration_afterMigrate/05_standard.sql
> Add volume column to dilutions

- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BoxPageIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/LibraryPageIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/AbstractPage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/BoxPage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/BoxVisualization.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/LibraryPage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/util/MoreExpectedConditions.java
- miso-web/src/it/resources/db/migration/V9000__integration-test_data.test.sql
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditBoxController.java
- miso-web/src/main/webapp/pages/editBox.jsp
- miso-web/src/main/webapp/scripts/box_ajax.js
- miso-web/src/main/webapp/scripts/box_visualization.js
- miso-web/src/main/webapp/scripts/library_ajax.js
- miso-web/src/main/webapp/scripts/lims.js
- miso-web/src/main/webapp/styles/style-full.css
GLT-1972
bulk actions are still outstanding
> UI test tubes in boxes

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/RunStore.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRunDao.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRunDaoTest.java
> remove unused RunStore.addAll method

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/printing/Backend.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/printing/Driver.java
- sqlstore/src/main/resources/db/migration/V8803__printer_rename.sql
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePrintServiceDaoTest.java
And rename existing ones to be more understandable
> Add new printer drivers

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/util/JsonArrayCollector.java
This probably will never occur, but good to have a correct implementation
> Fix flaw in JsonArrayCollector

- miso-web/src/it/resources/tomcat-config/miso.it.properties
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
- miso-web/src/main/resources/external/miso.properties
- miso-web/src/main/webapp/pages/editSample.jsp
- miso-web/src/main/webapp/scripts/hot.js
- miso-web/src/main/webapp/scripts/hot_sample.js
> Allow a default scientificName (configuration change in miso.properties)

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SampleTissue.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/DetailedSampleBuilder.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleTissueImpl.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleTissueDto.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/AbstractBulkSampleIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/SampleBulkCreateIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/SampleBulkEditIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/BulkSamplePage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/SamplePage.java
- miso-web/src/it/resources/db/migration/V9000__integration-test_data.test.sql
- miso-web/src/main/webapp/pages/editSample.jsp
- miso-web/src/main/webapp/scripts/hot_sample.js
- miso-web/src/main/webapp/scripts/sample_ajax.js
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDao.java
- sqlstore/src/main/resources/db/migration/V8202__ext_inst_id_to_secondary_id.sql
- sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_sample.sql
> Rename "external institute identifier" to "secondary identifier"

- miso-web/src/main/webapp/scripts/hot_sample.js
> Fix array bound check

- miso-web/src/main/webapp/scripts/list_container.js
- miso-web/src/main/webapp/scripts/list_group.js
- miso-web/src/main/webapp/scripts/list_samples.js
- miso-web/src/main/webapp/scripts/list_sequencer.js
> Pluralize titles on list pages

- runscanner/src/main/java/uk/ac/bbsrc/tgac/miso/runscanner/processors/DefaultPacBio.java
> Update PacBio dashboard link

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SequencerPartitionContainer.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SequencerPartitionContainerImpl.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultContainerService.java
- sqlstore/src/main/resources/db/migration/V8844__drop_container_barcodes.sql
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSequencerPartitionContainerDaoTest.java
- sqlstore/src/test/resources/db/test_migration/V9000__miso_test_data.test.sql
> Drop unused barcodes from containers

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/util/form/QcTableTag.java
This prevented the “Add” button from showing on the edit pages.
JIRA: GLT-2030
> Fix incorrect property name in QC Add

- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultInstituteService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLabService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSamplePurposeService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSubprojectService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultTissueMaterialService.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/util/ListItemsPageWithAuthorization.java
- miso-web/src/main/webapp/scripts/list_institute.js
- miso-web/src/main/webapp/scripts/list_lab.js
- miso-web/src/main/webapp/scripts/list_samplepurpose.js
- miso-web/src/main/webapp/scripts/list_subproject.js
- miso-web/src/main/webapp/scripts/list_tissuematerial.js
> Allow internal users to create institute defaults

- miso-web/src/main/webapp/scripts/run_graph.js
- runscanner-illumina/main.cpp
> Change Illumina cluster density chart and graph

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SequencerPartitionContainer.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SequencerPartitionContainerImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/kit/KitDescriptor.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/ContainerDto.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultContainerService.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSequencerPartitionContainerController.java
- miso-web/src/main/webapp/pages/editSequencerPartitionContainer.jsp
- sqlstore/src/main/resources/db/migration/V8802__add_kits_to_containers.sql
> Add clustering and multiplexing kits to containers

- miso-web/src/main/webapp/scripts/hot_library.js
This matches the single edit page
> Don't allow changing the platform type of a library through bulk edit after creation

- miso-web/src/main/webapp/scripts/list_poolelement.js
> Add targeted sequencing to edit pool page

- migration/src/main/java/uk/ac/bbsrc/tgac/miso/migration/destination/DefaultMigrationTarget.java
TIL deproxify does not initialize the lazy collections within an entity
> fix merging boxes during migration

- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java
- miso-web/src/main/webapp/scripts/list_dilution.js
> Reorder dilution table columns

- miso-web/src/main/webapp/scripts/list_container.js
> Change label in add container dialog

- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/PoolDto.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/AbstractListPage.java
- miso-web/src/main/webapp/scripts/list_partition.js
- miso-web/src/main/webapp/scripts/list_pool.js
> Add dilution counts to pools

- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/PartitionDto.java
- miso-web/src/main/webapp/scripts/list_partition.js
> Make container a hyperlink in partition list on run page

- sqlstore/src/main/resources/db/migration_beforeMigrate/05_add_qc.sql
> update addQC procedure

- miso-web/src/main/webapp/header.jsp
Functionality in these tabs is not guaranteed to be correct or used by OICR/EI. Hide them for now; can be re-displayed once functionality has been verified.
> Hide Analysis and Reports tabs

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SequencingParameters.java
- miso-web/pom.xml
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ProjectPageIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/RunPageIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/SampleBulkCreateIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/AbstractListPage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/AbstractPage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/ProjectPage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/RunPage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/element/DataTable.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/util/FormPageTestUtils.java
- miso-web/src/it/resources/db/migration/V9000__integration-test_data.test.sql
- miso-web/src/main/webapp/pages/editRun.jsp
- miso-web/src/main/webapp/scripts/lims.js
- miso-web/src/main/webapp/scripts/list_group.js
- miso-web/src/main/webapp/scripts/list_indices.js
- miso-web/src/main/webapp/scripts/list_kits.js
- miso-web/src/main/webapp/scripts/list_partition.js
- miso-web/src/main/webapp/scripts/list_sequencer.js
- miso-web/src/main/webapp/scripts/list_user.js
- miso-web/src/main/webapp/scripts/run_ajax.js
- sqlstore/src/main/resources/db/migration/V8235__seq_params_paired_not_null.sql
> Integration tests for run page

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/view/PoolableElementView.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/LimsUtils.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ProjectPageIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/RunPageIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/AbstractListPage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/ListPage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/ListTabbedPage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/ProjectPage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/RunPage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/element/DataTable.java
- miso-web/src/it/resources/db/migration/V9000__integration-test_data.test.sql
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolableElementViewDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSequencerPartitionContainerDao.java
- sqlstore/src/main/resources/db/migration_afterMigrate/05_view_pool.sql
> integration test table search

- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/IlluminaNotificationDto.java
- runscanner-illumina/main.cpp
- runscanner/README.md
- runscanner/src/main/java/uk/ac/bbsrc/tgac/miso/runscanner/processors/DefaultIllumina.java
- runscanner/src/test/java/uk/ac/bbsrc/tgac/miso/runscanner/processors/IlluminaProcessorTest.java
- runscanner/src/test/resources/illumina/130417_M00146_0021_000000000-A2WDF/reference.json
- runscanner/src/test/resources/illumina/140923_SN7001179_0208_BC59Y4ACXX/reference.json
- runscanner/src/test/resources/illumina/170609_NB551051_0017_AHLFFJBGX2/reference.json
> Avoid expensive directory scan for Illumina run completion

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/printing/Driver.java
> Add new Brady THT-179-492 labels

- miso-web/src/main/webapp/scripts/sequencer_service_record_ajax.js
- sqlstore/src/main/resources/db/migration/V8220__increase_service_record_title_length.sql
> Remove character limit to service record Title field

- miso-web/src/main/webapp/scripts/list.js
> Add more numbers for pagination items per page

- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ProjectPageIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/ProjectPage.java
- miso-web/src/it/resources/db/migration/V9000__integration-test_data.test.sql
- miso-web/src/main/webapp/pages/editProject.jsp
- miso-web/src/main/webapp/scripts/project_ajax.js
> Fix add ProjectOverview + UI test

- miso-web/src/it/resources/db/migration/V9000__integration-test_data.test.sql
- miso-web/src/it/resources/db/migration/V9000__integration-test_plain_data.test-plain.sql
- miso-web/src/it/resources/db/migration/afterAfterMigrate.sql
- miso-web/src/it/resources/db/scripts/schema_translator.groovy
- sqlstore/src/main/resources/db/migration/V8202__add_default_box_use_and_size.sql
- sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_box.sql
- sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_container.sql
- sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_library.sql
- sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_librarydilution.sql
- sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_partitionqc.sql
- sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_pool.sql
- sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_run.sql
- sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_sample.sql
- sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_sampleqc.sql
And call Pinery stored procedures only during tests, not during regular migration.
> Add default BoxUse and BoxSize

- runscanner-illumina/main.cpp
and it's new start date format
> Add support for NovaSeq

- miso-web/src/main/webapp/scripts/hot_pool.js
> Redirect to List Pools page after creating an order from bulk pools or list pools pages

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/printing/Driver.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/PrinterRestController.java
> Print the name if no barcode is provided

- .travis.yml
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkErrorCrawlerIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkSampleCreateIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkSampleEditIT.java
- pom.xml
- travis_jobs.sh
> Split up Travis CI jobs

- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/AbstractBulkSampleIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkSampleCreateIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/SampleBulkPropagateIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/BulkSamplePage.java
- miso-web/src/it/resources/db/migration/integration_test_data.sql
> UI tests for bulk propagating samples

- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/PlainSampleITs.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/BulkLibraryPage.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java
- miso-web/src/main/webapp/scripts/hot_library.js
> Fix NPE in plain library receipt

- sqlstore/src/main/resources/db/migration/8243__add_missing_spcp_fk.sql
Apologies in advance to Sven and EI.
> add missing SPC_Partition FK to _Partition

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/UserImpl.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditUserController.java
- miso-web/src/main/webapp/pages/editUser.jsp
- miso-web/src/main/webapp/scripts/user_ajax.js
Fixes #1225 as well as weirdness with password changes when using local (database) authentication
> Add/Edit User Fixes

- runscanner/src/main/java/uk/ac/bbsrc/tgac/miso/runscanner/processors/DefaultIllumina.java
> Check for CopyComplete.txt on Illumina NextSeq machines

- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/AbstractListPage.java
- miso-web/src/main/webapp/scripts/list_container.js
Also updated integration tests to look for this new column.
> GLT-1825: Add ID column to list sequencing containers page

- miso-web/src/it/resources/db/migration/plainSample_integration_test_data.sql
Not sure how this ever worked on the OICR branch, but it's no longer working now and this fixes it.
> Fix for plain sample integration test script

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/PoolOrderCompletion.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/PaginationFilter.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/PaginationFilterSink.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/PoolOrderCompletionDto.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkErrorCrawlerIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/PlainSampleITs.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/AbstractListPage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/ListTabbedPage.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/ListCompletionsController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/PoolOrderRestController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/util/TabbedListItemsPage.java
- miso-web/src/main/webapp/pages/adminsub.jsp
- miso-web/src/main/webapp/scripts/list_completion.js
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePaginatedDataSource.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolOrderCompletionDao.java
- sqlstore/src/main/resources/db/migration_afterMigrate/05_view_order_completions.sql
These are paritions that are loaded in a container that is not associated with a run
JIRA: GLT-2139
> Display "pending" partition count

- runscanner/src/main/java/uk/ac/bbsrc/tgac/miso/runscanner/RestController.java
> Add run metrics endpoint

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Index.java
- core/src/test/java/uk/ac/bbsrc/tgac/miso/core/data/impl/IndexTest.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/IndexDistanceToolController.java
- miso-web/src/main/webapp/pages/adminsub.jsp
- miso-web/src/main/webapp/pages/indexDistanceTool.jsp
- miso-web/src/main/webapp/scripts/indexDistance_ajax.js
- miso-web/src/main/webapp/scripts/list_indices.js
This is for checking indices before library prep. Pool-level warnings will be added in GLT-2101
> GLT-2173: added tool to check index edit distance

- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/AbstractListPage.java
- miso-web/src/main/webapp/scripts/list_run.js
> Add sequencing parameters column to run page

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractLibrary.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/service/printing/Driver.java
This rotates all the text and uses less of the label to fit on the tube
> Redesign THT-155-490 labels

- miso-web/src/main/webapp/scripts/run_graph.js
> Enforce ticks on cycles

- docs/_posts/2016-01-11-admin-manual.md
- integration-tools/src/main/java/uk/ac/bbsrc/tgac/miso/integration/BoxScannerConfigurer.java
- miso-web/src/it/resources/tomcat-config/miso.it.properties
- miso-web/src/it/resources/tomcat-plain-config/miso.it.plain.properties
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/context/MisoAppListener.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditBoxController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/BoxRestController.java
- miso-web/src/main/resources/external/miso.properties
- miso-web/src/main/resources/internal/miso.properties
- miso-web/src/main/webapp/WEB-INF/integration-config.xml
- miso-web/src/main/webapp/pages/editBox.jsp
- miso-web/src/main/webapp/scripts/box_ajax.js
- miso-web/src/main/webapp/scripts/box_visualization.js
- miso-web/src/test/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/BoxRestControllerTest.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/BoxControllerHelperService.java
- spring/src/test/java/uk/ac/bbsrc/tgac/miso/spring/ajax/test/BoxControllerHelperServiceTest.java
Also, I looked at `MisoAppListener` and its naming scheme config copy pasta (I did it!) was ugly, and had mistakes in it
> GLT-2171: support multiple bulk barcode scanners

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Barcodable.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/LibraryDilution.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/view/BarcodableView.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/BarcodableService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/BarcodableViewService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/BoxService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/ContainerService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/LibraryDilutionService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/LibraryService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/PoolService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/SampleService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultBarcodableViewService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/context/WebConfig.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/BarcodableViewDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/SampleDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateBarcodableViewDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDao.java
- sqlstore/src/main/resources/db/migration_afterMigrate/05_view_barcodable.sql
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateBarcodableViewDaoTest.java
Solution sketch is available in the associated ticket: https://jira.oicr.on.ca/browse/GLT-2182
> GLT-2182: Backend for search by barcode

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/InstrumentStatusRestController.java
> Fix NPE when completionDate isn't set for completed runs

- runscanner/src/main/java/uk/ac/bbsrc/tgac/miso/runscanner/processors/DefaultIllumina.java
It returns null, and that makes `Stream.array` unhappy
> Don't perform `listFiles` on non-existent directory

- miso-web/src/main/webapp/scripts/tile.js
> Make pool error messages more obvious when adding to run lane

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/LimsUtils.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/LibraryDilutionRestController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/LibraryRestController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/ParentFinder.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleRestController.java
- miso-web/src/main/webapp/scripts/hot.js
- miso-web/src/main/webapp/scripts/hot_dilution.js
- miso-web/src/main/webapp/scripts/hot_library.js
- miso-web/src/main/webapp/scripts/hot_sample.js
- miso-web/src/main/webapp/scripts/lims.js
> Add parent selection button to libraries and dilutions

- miso-web/src/main/webapp/scripts/run_graph.js
> Change tick marks on per-cycle graphs

- miso-web/src/main/webapp/scripts/hot.js
This makes the sort buttons look like the other buttons and disappear once the
page is saved.
> Improve UI consistency in bulk HoT pages

- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePaginatedDataSource.java
> Fix counts in some tables

- miso-web/src/main/webapp/scripts/box_visualization.js
Otherwise it chokes instead of retrying.
> Use name of scanner in scan retry

- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultRunService.java
- miso-web/src/main/resources/external/miso.properties
- miso-web/src/main/resources/internal/miso.properties
...for real this time.
Also fixes the runscanner endpoint in `miso.properties`
> Save runBasesMask

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/workflow/AbstractProgressStep.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/workflow/Progress.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/workflow/ProgressStep.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/workflow/Workflow.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/workflow/impl/PoolProgressStep.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/workflow/impl/ProgressImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/workflow/impl/SampleProgressStep.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/ProgressStore.java
- core/src/test/java/uk/ac/bbsrc/tgac/miso/core/data/workflow/impl/ProgressImplTest.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateProgressDao.java
- sqlstore/src/main/resources/db/migration/V8100__workflowProgress.sql
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateProgressDaoTest.java
- sqlstore/src/test/resources/db/test_migration/test_data.sql
Associated ticket: https://jira.oicr.on.ca/browse/GLT-2198
Commits will be squashed/renamed before merging.
> GLT-2198: Create backend for storing workflow progress

- miso-web/src/main/webapp/scripts/lims.js
> Make the AJAX working dialog not closeable

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/workflow/AbstractWorkflow.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/workflow/ProgressStep.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/workflow/Workflow.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/workflow/WorkflowExecutor.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/workflow/impl/LoadSequencerWorkflow.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/workflow/impl/ProgressImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/ProgressStore.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/LimsUtils.java
- core/src/test/java/uk/ac/bbsrc/tgac/miso/core/data/workflow/impl/TestWorkflow.java
- core/src/test/java/uk/ac/bbsrc/tgac/miso/core/data/workflow/impl/TestWorkflowTest.java
- migration/src/main/java/uk/ac/bbsrc/tgac/miso/migration/destination/MigrationAuthorizationManager.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultWorkflowExecutor.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/security/AuthorizationManager.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/security/DefaultAuthorizationManager.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/workflow/DefaultWorkflowManager.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/workflow/WorkflowManager.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/workflow/factory/BarcodableProgressStepFactory.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/workflow/factory/IntegerProgressStepFactory.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/workflow/factory/ProgressStepFactory.java
- miso-service/src/test/java/uk/ac/bbsrc/tgac/miso/service/workflow/DefaultWorkflowManagerTest.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/context/WebConfig.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateProgressDao.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateProgressDaoTest.java
- sqlstore/src/test/resources/db/test_migration/test_data.sql
Associated issue: https://jira.oicr.on.ca/browse/GLT-2200
Notes:
* The only tests added are for `WorkflowManager#makeProgressStep`.
Commits will be squashed and renamed before merging.
> GLT-2200: Create WorkflowManager

- miso-web/src/main/webapp/scripts/hot_dilution.js
> Don't put '(None)' in the targeted sequencing list if not allowed

- miso-web/src/main/webapp/scripts/hot_library.js
> Filter indices by position when packing

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/BarcodableSearchRestController.java
- miso-web/src/main/webapp/scripts/pane_barcode.js
> Make dilution search tile link to correct library page

- miso-web/src/main/webapp/pages/editProject.jsp
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSequencerPartitionContainerDao.java
Runscanner should be able to find old (archived) sequencingContainerModels otherwise saving the run automatically via runscanner fails.
> Misc fixes

- sqlstore/src/main/resources/db/migration_beforeMigrate/05_add_index.sql
> make addIndex procedure fail loudly on error

- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java
- miso-web/src/main/webapp/scripts/list_box.js
> Display description column on List Boxes page

- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultQualityControlService.java
- sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_containerqc.sql
- sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_libraryqc.sql
- sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_poolqc.sql
And `setChangeDetails` on QC update
> GLT-2288 add QC changelogs for Library, Pool, Container

- sqlstore/src/main/resources/db/migration_beforeMigrate/05_add_kit.sql
Once we release v0.2.117 to production, I'd like to update the `addKitDescriptor` procedure with these changes.
> update addKitDescriptor procedure

- sqlstore/src/main/resources/db/migration_afterMigrate/05_view_box.sql
It is not supported in newer versions of mySQL
> Remove `FROM` clause in `BoxableView`

- pom.xml
These changes are already in the OICR fork
> Clean up POM file

- runscanner-illumina/main.cpp
> Add total cluster count to summary table

- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkPoolIT.java
- miso-web/src/main/webapp/scripts/hot_pool.js
Similar to how library creation defaults to today.
> Default pool creation date to today

- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/ProjectService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultProjectService.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleRestController.java
> Fixup identity search by project

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/PoolRestController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/ProjectRestController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/RunRestController.java
Tested and all seems to be working.
> Use Dto for Run REST endpoint, and add new Project REST API calls

- miso-web/src/main/webapp/scripts/run_graph.js
- runscanner-illumina/main.cpp
> Add Illumina clusters per lane plot

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/AbstractInstituteDefaultsController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/DownloadController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditBoxController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditExperimentController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditInstrumentController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditKitDescriptorController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditPoolController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditProjectController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSequencerPartitionContainerController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditServiceRecordController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditStudyController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditUserController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/WorkflowController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/component/PageNotFoundAdvice.java
- miso-web/src/main/webapp/header.jsp
- miso-web/src/main/webapp/notFound.jsp
- miso-web/src/main/webapp/pages/notFound.jsp
GLT-2317
Deliberately didn't add an `alias` endpoint because there's no guarantee that an alias won't have spaces in it.
> Add URL for linking to project by shortname

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java
- miso-web/src/main/webapp/scripts/box_ajax.js
- miso-web/src/main/webapp/scripts/hot.js
- miso-web/src/main/webapp/scripts/hot_library.js
- miso-web/src/main/webapp/scripts/hot_sample.js
when propagating libraries from the box page
> GLT-2252: auto-sort by sample box column

- miso-web/src/main/webapp/scripts/box_ajax.js
> Allow skipping to the next box when pasting into box update

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractBox.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Box.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/StorageLocation.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/StorageLocationStore.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/StorageLocationDto.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/StorageLocationService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultBoxService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultStorageLocationService.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditBoxController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditFreezerController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/StorageLocationRestController.java
- miso-web/src/main/webapp/pages/editBox.jsp
- miso-web/src/main/webapp/pages/editFreezer.jsp
- miso-web/src/main/webapp/scripts/box_ajax.js
- miso-web/src/main/webapp/scripts/freezer_ajax.js
- miso-web/src/main/webapp/scripts/lims.js
- miso-web/src/main/webapp/styles/style-full.css
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateStorageLocationDao.java
- sqlstore/src/main/resources/db/migration/V8500__freezers.sql
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateBoxDaoTest.java
Note: this is missing some components and functionality that will be added separately - most notably a List Freezers page
> Freezer tracking

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/ListStorageLocationsController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/util/TabbedListItemsPage.java
- miso-web/src/main/webapp/pages/adminsub.jsp
- miso-web/src/main/webapp/pages/listTabbedStatic.jsp
- miso-web/src/main/webapp/scripts/freezer_ajax.js
- miso-web/src/main/webapp/scripts/list_storage_location.js
> Add list freezers and rooms page

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/LibraryDilutionRestController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/LibraryRestController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/ParentFinder.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/PoolRestController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/RelationFinder.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleRestController.java
- miso-web/src/main/webapp/scripts/hot.js
- miso-web/src/main/webapp/scripts/hot_dilution.js
- miso-web/src/main/webapp/scripts/hot_library.js
- miso-web/src/main/webapp/scripts/hot_pool.js
- miso-web/src/main/webapp/scripts/hot_sample.js
Jira:
GLT-2239
GLT-2241
GLT-2238
> Modify find parents and add find children

- miso-web/src/main/webapp/scripts/hot.js
- miso-web/src/main/webapp/scripts/hot_sample.js
> Add Autocomplete to Tissue Origin and Tissue Type Columns

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/spreadsheet/LibraryDilutionSpreadSheets.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/spreadsheet/LibrarySpreadSheets.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/spreadsheet/PoolSpreadSheets.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/MenuController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/LibraryDilutionRestController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/LibraryRestController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/PoolRestController.java
- miso-web/src/main/webapp/scripts/hot_dilution.js
- miso-web/src/main/webapp/scripts/hot_library.js
- miso-web/src/main/webapp/scripts/hot_pool.js
Jira:
GLT-2239
GLT-1998
GLT-2110
> Add spreadsheets for libraries and dilutions with external name

- miso-web/src/main/webapp/scripts/hot_library.js
> GLT_2238 autocomplete indices

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractSample.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/SampleStore.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/SampleService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java
- miso-service/src/test/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleServiceTest.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleRestController.java
- miso-web/src/main/webapp/pages/identitySearchTool.jsp
- miso-web/src/main/webapp/scripts/hot_sample.js
- miso-web/src/main/webapp/scripts/identitySearch_ajax.js
- miso-web/src/main/webapp/scripts/sample_ajax.js
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDao.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDaoTest.java
> Add identity search partial match and fix exact match by project bug

- miso-web/src/main/webapp/scripts/hot.js
> Fix Bulk Pools and Dilutions Concentration Validation Bug

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/spreadsheet/SpreadSheetFormat.java
> Use .xlsx extension for spreadsheets

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/StorageLocation.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/BoxStore.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/BoxDto.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/StorageLocationDto.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/BoxService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultBoxService.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/AbstractListPage.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditBoxController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditFreezerController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/ListBoxesController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/BoxRestController.java
- miso-web/src/main/webapp/pages/editBox.jsp
- miso-web/src/main/webapp/pages/editFreezer.jsp
- miso-web/src/main/webapp/scripts/freezer_ajax.js
- miso-web/src/main/webapp/scripts/hot_boxable.js
- miso-web/src/main/webapp/scripts/list_box.js
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateBoxDao.java
> Add Box Management to Edit Freezers Page

- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultKitService.java
Fixes #1496
IT tests to follow.
> Fix SQL error when saving new kits

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/kit/KitDescriptor.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/KitDescriptorDto.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/KitDescriptorPageIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/KitDescriptorPage.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditFreezerController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditKitDescriptorController.java
- miso-web/src/main/webapp/pages/editKitDescriptor.jsp
- miso-web/src/main/webapp/scripts/kitDescriptor_ajax.js
> Integration tests for Kits

- miso-web/src/main/webapp/scripts/list_partition.js
> Display order platform on pool tiles when filling sequencing containers

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/Project.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/ProjectImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/TargetedSequencing.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/LibraryDto.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultProjectService.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkDilutionIT.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditProjectController.java
- miso-web/src/main/webapp/pages/editProject.jsp
- miso-web/src/main/webapp/scripts/hot_dilution.js
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/LimsBindingInitializer.java
- sqlstore/src/main/resources/db/migration/V8801__Default_Targeted_Sequencing.sql
>  Add Default Targeted Sequencing setting for Projects

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/SampleRestController.java
- miso-web/src/main/webapp/scripts/identitySearch_ajax.js
- miso-web/src/main/webapp/styles/style-full.css
> Fix table filtering and make results copyable in identity search

- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/BoxService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultBoxService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryDilutionService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultPoolService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java
This attempts to update the boxable only if it's changed and monitors the time
it takes to reduce the time.
> Try to reduce saving time for boxables

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/type/QcType.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/QualityControlTypeStore.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/QcTypeService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultQcTypeService.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/MenuController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/QcTypeDefaultsController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/QcTypeController.java
- miso-web/src/main/webapp/pages/adminsub.jsp
- miso-web/src/main/webapp/scripts/hot_qctype.js
- miso-web/src/main/webapp/scripts/list_qctype.js
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateQcTypeDao.java
> Allow adding QcTypes through the front-end

- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/DashboardHelperService.java
> Add project shortname to home page project tiles

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/workflow/ProgressStep.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/workflow/Workflow.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/workflow/WorkflowExecutor.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/workflow/WorkflowStep.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/workflow/impl/BoxPositionProgressStep.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/workflow/impl/BoxProgressStep.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/workflow/impl/LoadSequencerWorkflow.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/workflow/impl/PositiveDoubleProgressStep.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/workflow/impl/PositiveIntegerProgressStep.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/workflow/impl/SamplesReceivedWorkflow.java
- core/src/test/java/uk/ac/bbsrc/tgac/miso/core/data/workflow/impl/TestWorkflow.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/QualityControlService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/SampleService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultQualityControlService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultWorkflowExecutor.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/workflow/DefaultWorkflowManager.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/workflow/factory/BarcodableProgressStepFactory.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/workflow/factory/BoxPositionProgressStepFactory.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/workflow/factory/PositiveDoubleProgressStepFactory.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/workflow/factory/PositiveIntegerProgressStepFactory.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/workflow/factory/StockProgressStepFactory.java
- miso-web/src/main/webapp/WEB-INF/db-config.xml
- miso-web/src/main/webapp/scripts/hot_sample.js
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateProgressDao.java
- sqlstore/src/main/resources/db/migration/V8800__Samples_Recieved_Workflow.sql
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateProgressDaoTest.java
Jira: GLT-2336
This workflow takes in a Stock Barcode, a Qubit QC value, and a number of Aliquots.
It then applies the QC to the Stock and propgates the Stock into the specified number of Aliquots.
> Samples Received Workflow

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/LibraryDilution.java
- miso-web/src/main/webapp/scripts/hot_dilution.js
- sqlstore/src/main/resources/db/migration/V8805__Optional_Dilution_Concentration.sql
> Make dilution concentration optional

- miso-web/src/main/webapp/scripts/hot_pool.js
- miso-web/src/main/webapp/scripts/pool_ajax.js
- sqlstore/src/main/resources/db/migration/V8806__Optional_Pool_Concentration.sql
> Make Pool Concentration Optional

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/LibraryDilution.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/view/PoolableElementView.java
- core/src/test/java/uk/ac/bbsrc/tgac/miso/core/data/LibraryDilutionTest.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/DilutionDto.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryDilutionService.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkDilutionIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/PlainSampleITs.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/AbstractListPage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/BulkDilutionPage.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditPoolController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditProjectController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/MenuController.java
- miso-web/src/main/webapp/scripts/hot_dilution.js
- miso-web/src/main/webapp/scripts/list_dilution.js
- miso-web/src/main/webapp/scripts/list_poolelement.js
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolableElementViewDao.java
- sqlstore/src/main/resources/db/migration/V8809__Dilution_Concentration_Units.sql
- sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_librarydilution.sql
- sqlstore/src/main/resources/db/migration_afterMigrate/05_view_pool.sql
> Store concentration units within Library Dilutions

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/QcCorrespondingField.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/QcTarget.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/type/QcType.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/QcTargetDto.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/QcTypeDto.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultQcTypeService.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/MenuController.java
- miso-web/src/main/webapp/scripts/hot_qctype.js
- miso-web/src/main/webapp/scripts/list_qctype.js
- sqlstore/src/main/resources/db/migration/V8808__QCType_Corresponding_Field.sql
> Add Corresponding Field columns for QCTypes

- miso-web/src/main/webapp/pages/editLibrary.jsp
- miso-web/src/main/webapp/scripts/library_ajax.js
> Remove concentration units from edit library page

- miso-web/src/main/webapp/scripts/hot_qctype.js
> Remove Auto Update Field for boolean QCs

- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultRunService.java
- runscanner-illumina/main.cpp
- runscanner/src/main/java/uk/ac/bbsrc/tgac/miso/runscanner/processors/DefaultIllumina.java
> Handle missing extraction metric dates on NovaSeq

- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/AbstractListPage.java
- miso-web/src/main/webapp/scripts/list_dilution.js
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePoolableElementViewDao.java
> Add ng Lib Used and Vol Lib Used to List Dilutions

- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkDilutionIT.java
- miso-web/src/it/resources/db/migration/integration_test_data.sql
- miso-web/src/main/webapp/scripts/hot_dilution.js
> Add warnings for dilution volume library used exceeding parent library volume

- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryDilutionService.java
> Fix update dilution bug

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/PoolImpl.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkDilutionIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkLibraryIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/PoolPageIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/RunPageIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/AbstractListPage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/PoolPage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/RunPage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/element/DataTable.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/util/FormPageTestUtils.java
- miso-web/src/it/resources/db/migration/integration_test_data.sql
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditPoolController.java
- miso-web/src/main/webapp/pages/editPool.jsp
- miso-web/src/main/webapp/scripts/list_pool.js
> Show no index warning

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditPoolController.java
- miso-web/src/main/webapp/pages/editPool.jsp
- miso-web/src/main/webapp/scripts/list_completion.js
- miso-web/src/main/webapp/scripts/list_experiment_run_partition.js
- miso-web/src/main/webapp/scripts/list_partition.js
- miso-web/src/main/webapp/scripts/list_pool.js
- miso-web/src/main/webapp/scripts/list_poolelement.js
- miso-web/src/main/webapp/scripts/warning.js
- miso-web/src/main/webapp/scripts/warning_completion.js
- miso-web/src/main/webapp/scripts/warning_experiment.js
- miso-web/src/main/webapp/scripts/warning_partition.js
- miso-web/src/main/webapp/scripts/warning_pool.js
- miso-web/src/main/webapp/scripts/warning_poolelement.js
> Centralize Warning Handling

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/DetailedSample.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/DetailedSampleBuilder.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/DetailedSampleImpl.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/DetailedLibraryDto.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/DetailedSampleDto.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkLibraryIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkSampleEditIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/BulkLibraryPage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/BulkSamplePage.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
- miso-web/src/main/webapp/pages/editLibrary.jsp
- miso-web/src/main/webapp/pages/editSample.jsp
- miso-web/src/main/webapp/scripts/hot_library.js
- miso-web/src/main/webapp/scripts/hot_sample.js
GLT-2042
* displays the effective (nearest) sample Group ID on both
> Make sample group ID more visible on library (DetailedSample)

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/BoxStore.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultBoxService.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateBoxDao.java
- sqlstore/src/main/resources/db/migration_afterMigrate/10_move_box_item.sql
- sqlstore/src/main/resources/db/migration_afterMigrate/10_remove_box_item.sql
> Use a stored procedure to move items in boxes

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/PaginationFilter.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/PaginationFilterSink.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java
- miso-web/src/main/webapp/scripts/list.js
- miso-web/src/main/webapp/scripts/list_container.js
- miso-web/src/main/webapp/scripts/list_library.js
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateKitDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePaginatedDataSource.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSequencerPartitionContainerDao.java
> Add Search by Kit Name

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/PoolImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/type/PlatformType.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/AbstractListPage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/BulkLibraryPage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/BulkPoolPage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/BulkSamplePage.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditPoolController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditProjectController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/MenuController.java
- miso-web/src/main/webapp/scripts/hot_library.js
- miso-web/src/main/webapp/scripts/hot_pool.js
- miso-web/src/main/webapp/scripts/hot_sample.js
- miso-web/src/main/webapp/scripts/list_pool.js
> Remove Constant Units For Samples, Libraries, and Pools

- sqlstore/src/main/resources/db/migration_afterMigrate/05_view_order_completions.sql
> Fix pending pool orders calculation

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/store/BoxStore.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/BoxDto.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/BoxService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultBoxService.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditBoxController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/BoxRestController.java
- miso-web/src/main/webapp/scripts/hot.js
- miso-web/src/main/webapp/scripts/hot_box.js
- miso-web/src/main/webapp/scripts/list_box.js
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateBoxDao.java
> Add multiple box creation

- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/LibraryPageIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/AbstractListPage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/LibraryPage.java
- miso-web/src/it/resources/db/migration/integration_test_data.sql
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java
- miso-web/src/main/webapp/pages/editLibrary.jsp
- miso-web/src/main/webapp/pages/editPool.jsp
- miso-web/src/main/webapp/scripts/list_library.js
- miso-web/src/main/webapp/scripts/warning_library.js
> Add Negative Library Volume Warning

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/IndexFamily.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/IndexFamilyDto.java
- miso-web/src/main/webapp/scripts/hot_library.js
- sqlstore/src/main/resources/db/migration/V8801__AutoFill_Dual_Index.sql
> Automatically Fill Second Index For Unique Dual Indexed Kits

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/spreadsheet/SampleSpreadSheets.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleSpreadSheetDto.java
- miso-web/src/main/webapp/scripts/hot.js
- miso-web/src/main/webapp/scripts/hot_dilution.js
- miso-web/src/main/webapp/scripts/hot_library.js
- miso-web/src/main/webapp/scripts/hot_pool.js
- miso-web/src/main/webapp/scripts/hot_sample.js
> Add Transfer List Download Form

- miso-web/src/main/webapp/pages/editPool.jsp
> Fix create pool page javascript error

- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkPoolIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/BulkPoolPage.java
- miso-web/src/main/webapp/scripts/hot_pool.js
> Add Description To Bulk Pools Table

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/PaginationFilter.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/PaginationFilterSink.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java
- miso-web/src/main/webapp/scripts/list.js
- miso-web/src/main/webapp/scripts/list_library.js
- miso-web/src/main/webapp/scripts/list_samples.js
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePaginatedDataSource.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateSampleDao.java
> Filter search by subproject

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/SamplePurpose.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SamplePurposeImpl.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SamplePurposeDto.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
- miso-web/src/main/webapp/scripts/hot_sample.js
- sqlstore/src/main/resources/db/migration/V8804__Archive_Sample_Purposes.sql
> Add Archived Sample Purposes

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/SampleIdentityImpl.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/DetailedSampleDto.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/SampleIdentityDto.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java
- miso-web/src/main/webapp/scripts/hot.js
- miso-web/src/main/webapp/scripts/hot_sample.js
- miso-web/src/main/webapp/styles/style-full.css
> Add updating identities with new external names placed on children

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/AbstractLibrary.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryService.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkLibraryIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/PlainSampleITs.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/BulkLibraryPage.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/LibraryPage.java
- miso-web/src/main/webapp/pages/editLibrary.jsp
- miso-web/src/main/webapp/scripts/hot_library.js
- miso-web/src/main/webapp/scripts/library_ajax.js
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryDao.java
- sqlstore/src/main/resources/db/migration/V8802__Edit_Library_creationDate.sql
> Allow Adding and Editing Library Creation Date

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/LibraryDilution.java
- migration/src/main/java/uk/ac/bbsrc/tgac/miso/migration/source/LoadGeneratorSource.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryDilutionService.java
- miso-web/src/it/resources/db/migration/integration_test_data.sql
- miso-web/src/it/resources/db/migration/plainSample_integration_test_data.sql
- pinery-miso/src/it/resources/db/migration/pinery-miso_plain_test_data.sql
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/ajax/ImportExportControllerHelperService.java
- spring/src/main/java/uk/ac/bbsrc/tgac/miso/spring/util/FormUtils.java
- sqlstore/src/main/resources/db/migration/V8803__Dilution_Creator_Id.sql
- sqlstore/src/main/resources/db/migration_afterMigrate/05_view_pool.sql
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryDilutionDaoTest.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/util/TimeShiftingInterceptorTest.java
- sqlstore/src/test/resources/db/test_migration/test_data.sql
> Change LibraryDilution table to use User Id instead of Name

- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/DetailedSampleDto.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkLibraryIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkSampleCreateIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkSampleEditIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/BulkSamplePage.java
- miso-web/src/main/webapp/scripts/hot_library.js
- miso-web/src/main/webapp/scripts/hot_sample.js
> Add subproject to bulk sample tables (DetailedSample)

- miso-web/src/main/webapp/scripts/hot.js
- miso-web/src/main/webapp/scripts/hot_boxable.js
- miso-web/src/main/webapp/scripts/hot_qctype.js
- miso-web/src/main/webapp/scripts/hot_sample.js
> Add HOT field descriptions to quick help dropdown

- miso-web/src/it/resources/tomcat-config/miso.it.properties
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/context/ExternalUriBuilder.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/context/WebConfig.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditRunController.java
- miso-web/src/main/resources/external/miso.properties
- miso-web/src/main/resources/internal/miso.properties
- miso-web/src/main/webapp/pages/editRun.jsp
> Add links to external services for Runs [CONFIG CHANGE]

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/view/PoolableElementView.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-web/src/main/webapp/scripts/list_poolelement.js
- sqlstore/src/main/resources/db/migration_afterMigrate/05_view_pool.sql
> Add Library QC Status Column to Pool Page Dilutions Table

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/PaginationFilter.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/PaginationFilterSink.java
- miso-web/src/main/webapp/scripts/list.js
- miso-web/src/main/webapp/scripts/list_run.js
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernatePaginatedDataSource.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRunDao.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateRunDaoTest.java
- sqlstore/src/test/resources/db/test_migration/test_data.sql
> Add Run Look Up By Sequencing Parameters

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/LibraryTemplate.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/LibraryTemplateDto.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateTemplateDao.java
- sqlstore/src/main/resources/db/migration/V8812__LibraryTemplate_Multiple_Projects.sql
- sqlstore/src/test/resources/db/test_migration/test_data.sql
> Allow Library Templates to be associated with multiple projects

- miso-web/src/main/webapp/pages/editLibrary.jsp
- miso-web/src/main/webapp/pages/editPool.jsp
- miso-web/src/main/webapp/pages/editProject.jsp
- miso-web/src/main/webapp/pages/editRun.jsp
- miso-web/src/main/webapp/pages/editSample.jsp
- miso-web/src/main/webapp/styles/style-full.css
Also fixed deletion icons appearing too high, or clipping through the creator name in the case of Pools
Jira: GLT-1018
> Improved Notes Display on Project Overview

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/LibraryDilution.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryDilutionService.java
- pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllSamples.sql
- sqlstore/src/main/resources/db/migration/V8813__Dilution_CreatedDate.sql
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateLibraryDilutionDaoTest.java
- sqlstore/src/test/java/uk/ac/bbsrc/tgac/miso/persistence/impl/util/TimeShiftingInterceptorTest.java
> Add generated creation date to dilutions

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/workflow/Workflow.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/WorkflowNameDto.java
- miso-web/src/main/webapp/scripts/pane.js
- miso-web/src/main/webapp/scripts/pane_barcode.js
> Start Workflows from Search Widget

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/ReferenceGenome.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/ReferenceGenomeImpl.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/ProjectDto.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
- miso-web/src/main/webapp/scripts/hot_sample.js
- sqlstore/src/main/resources/db/migration/V8816__ReferenceGenome_defaultSciName.sql
> Samples Inherit Species from Project

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/workflow/impl/SamplesReceivedWorkflow.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/BarcodableViewService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultBarcodableViewService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/workflow/factory/BarcodableProgressStepFactory.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/BarcodableViewDao.java
- sqlstore/src/main/java/uk/ac/bbsrc/tgac/miso/persistence/impl/HibernateBarcodableViewDao.java
> Add search by alias to workflows

- RELEASE_NOTES.md
Cancelled tests as this is a documentation-only change.
> Update release notes with config change for external run services

- miso-web/src/main/webapp/scripts/hot_library.js
> Filter library templates by sample class of parent

- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultWorkflowExecutor.java
> Fix Samples Received Workflow

- miso-web/src/main/webapp/scripts/list.js
> Use checkbox for automatic box creation

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/QC.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/QcDto.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkLibraryQCIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkPoolQCIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/BulkSampleQCIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/BulkQCPage.java
- miso-web/src/main/webapp/scripts/hot_qc.js
- miso-web/src/main/webapp/scripts/list_qc.js
- sqlstore/src/main/resources/db/migration/V8817__QC_Notes.sql
> Add QC Notes

- miso-web/src/main/webapp/scripts/hot_library.js
Templates provide a name but the column requies a key
JIRA: GLT-2443
> Use platform key in cell value instead of platform name

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/PoolImpl.java
- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/impl/view/PoolableElementView.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/PoolDto.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/PoolPageIT.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditPoolController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
- miso-web/src/main/webapp/pages/editLibrary.jsp
- miso-web/src/main/webapp/pages/editSample.jsp
- miso-web/src/main/webapp/scripts/list_dilution.js
- miso-web/src/main/webapp/scripts/list_poolelement.js
- miso-web/src/main/webapp/scripts/list_samples.js
- miso-web/src/main/webapp/scripts/warning_dilution.js
- miso-web/src/main/webapp/scripts/warning_pool.js
- miso-web/src/main/webapp/scripts/warning_poolelement.js
- miso-web/src/main/webapp/scripts/warning_sample.js
- sqlstore/src/main/resources/db/migration_afterMigrate/05_view_pool.sql
> Migrate Consent Revoked Warnings to New Warning System

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/ListLibraryTemplatesController.java
> Fix Library Templates List Page

- miso-web/src/it/resources/db/migration/integration_test_data.sql
- pinery-miso/src/it/resources/db/migration/pinery-miso_detailed_test_data.sql
- pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllSamples.sql
- sqlstore/src/main/resources/db/migration/V8820__Drop_DetailedSample_Concentration.sql
- sqlstore/src/main/resources/db/migration_afterMigrate/05_trigger_sample.sql
> Drop DetailedSample Concentration Column

- miso-web/src/it/resources/tomcat-config/miso.it.properties
- miso-web/src/it/resources/tomcat-plain-config/miso.it.plain.properties
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/context/ExternalUriBuilder.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/context/WebConfig.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditProjectController.java
- miso-web/src/main/resources/external/miso.properties
- miso-web/src/main/resources/internal/miso.properties
- miso-web/src/main/webapp/pages/editProject.jsp
> Add links to external services for Projects [CONFIG CHANGE]

- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/rest/WorksetRestController.java
> Fix "Mine" tab on List Worksets page

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/data/PoolOrderCompletion.java
- miso-dto/src/main/java/uk/ac/bbsrc/tgac/miso/dto/Dtos.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/AbstractListPage.java
- miso-web/src/main/webapp/scripts/list_completion.js
- sqlstore/src/main/resources/db/migration_afterMigrate/05_view_order_completions.sql
- Aggregate comments, separated by '; ', in OrderCompletion schema
- Display aggregated comments on All Orders, Pending Orders, and Active Orders in 'Order Description' column
- Update ListTablesIT to accommodate new column
> [GLT-1373] Aggregate Comments into OrderCompletion view

- miso-web/pom.xml
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/util/TestListener.java
- miso-web/src/it/resources/log4j.properties
Does not fix anything, but will help to troubleshoot. Also disables ScriptUtils logging
> log test names

- pinery-miso/src/main/resources/ca/on/oicr/pinery/lims/miso/queryAllSamples.sql
> Correct project shortname in Pinery for libs and dilutions

- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultArrayRunService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultArrayService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultContainerService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultKitService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultLibraryService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultRunService.java
- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/DefaultSampleService.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditBoxController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditExperimentController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditInstrumentController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditKitDescriptorController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditLibraryController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditPoolController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditProjectController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditRunController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSampleController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSequencerPartitionContainerController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditServiceRecordController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditStudyController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditSubmissionController.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditUserController.java
Use AuthorizationManager for authorization calls.
Use Timestamped interface to remove duplicated setChangeDetails methods.
> Minor code cleanup

- miso-web/src/main/webapp/scripts/list.js
Note: The diff is entirely autoformat except the last line which adds a call to `updateSelectedLabel` in the `fnDrawCallback` function
> GLT-2474: fixed selected items count on page size change

- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/ListTablesIT.java
- miso-web/src/it/java/uk/ac/bbsrc/tgac/miso/webapp/integrationtest/page/AbstractListPage.java
- miso-web/src/main/webapp/scripts/list_worksets.js
> Display number of items in workset on List Worksets page

- miso-service/src/main/java/uk/ac/bbsrc/tgac/miso/service/impl/ValidationUtils.java
> Don't validate units for non-real measurements

- core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/SampleSheet.java
- miso-web/src/main/java/uk/ac/bbsrc/tgac/miso/webapp/controller/EditRunController.java
> Correct index 2 sequences on sample sheet
